### PR TITLE
fix: Fixing navbar on scrolling

### PR DESCRIPTION
**Pull request by itzabhinavarya**
## What does this PR do?

This PR resolve the Feature no. #1170 

Fixes # (issue)

Expected Behaviour
In Light Mode:
image

In Dark Mode:
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala & @jobenjada I request you to please review the changes. 
For more clearification you can head over to the following reference point 
#1170 #1054

**Comment by jobenjada** [comment]
@itzabhinavarya please resolve the merge conflict
@ShubhamPalriwala if this is smooth and doesnt bug, we can merge it :)

**Comment by itzabhinavarya** [comment]
@jobenjada I am not able to resolve this conflict, because the resolve conflicts button is disabled.
Also i want a little help from you that suppose i create a branch name A
make changes , added the file , commited and then pushed on github , make a PR . Everything is good. only that file is coming in the File changed section. 

But when i created a second Branch suppose branch name B 
Switched to that branch , make some changes, added , commited and pushed that branch , after that when i create another PR with the B branch the in file changes section, the file i have made changes in A is also comming in the B branch , why this is happening idk. I am finding the solution but didn't get that. If you help me with this problem i'll be very thankful to yours.
 
First of all Kindly, let me know how can i resolve this conflict.Please guide me.

image

**Comment by jobenjada** [comment]
Hey! Did you delete the Docs Footer? :D

**Comment by itzabhinavarya** [comment]
Yes, Should i revert it back?
If so then i have to create a new PR i think.

**Comment by jobenjada** [comment]
Well we obviously need the Footer in the Docs so yes, please revert that.

It might be the easiest to make a new branch of main and only add the sitcky header code again. 

Now that I look at your code again, do you really need that much JS? There should be a Tailwind only solution (class "sticky")

Thanks!

**Comment by ShubhamPalriwala** [comment]
Hey @itzabhinavarya whats the update here?

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala Sir, I wasn't active yesterday, I will create a new PR for this issue by EOD.

**Comment by itzabhinavarya** [comment]
new pr generated for this #1266

**Pull request closed without merging**
