### PR TITLE
Relocate Files from components/ to app/ Directory

### LINKED ISSUE #527: [Improvement] Relocate Files from components to app directory
**Is your feature request related to a problem? Please describe.**
In the previous versions of next.js pages went into the `/pages` directory and by convention if you build components you put them into a `/components` folder.
But with next.js 13 and the app directory you can put all the components next to the pages in the `app` directory to have everything at one place and show where these files are used. It's a much cleaner approach.
We already store our reusable UI components in `packages/ui` and for us currently there isn't much need for `components` directory, but we still have files there.

**Describe the solution you'd like**
We still have a lot of files in the `apps/web/components` folder. Please move them into the `apps/web/app` directory into the routes where they are needed / referenced.
In an ideal world, we can get rid of the `components` folder completely 😊

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## What does this PR do?
This PR moves components according to the new Nextjs standards!
I have followed the foundation of:
- If a component is ONLY used by a similar group of elements inside a subdirectory, then the component is moved to that directory
- Else, the component is shifted to the `formbricks/ui` directory for reusability!

The only components that are left now are the ones that have a similar existing component already in the `ui` directory!

Fixes # (issue)
Closes #527 

## Type of change
- [x] Chore (refactoring code, technical debt, workflow improvements)

## Checklist
- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@ShubhamPalriwala PR looks great on first sight 😊 Is it already ready for review (since it's still a draft)?
Can you please also solve the merge conflicts before the final review? 😊

**Comment by ShubhamPalriwala** [comment]
Hey @mattinannt, I'm still left with a few components that I am not sure where to move them to! Do you want me to mark the PR as Ready for Review and tackle those later?

**Comment by mattinannt** [comment]
> Hey @mattinannt, I'm still left with a few components that I am not sure where to move them to! Do you want me to mark the PR as Ready for Review and tackle those later?

yes, let's do it that way :-)

**Comment by mattinannt** [comment]
for now; we will probably move the files again when the codebase settles down more.

**Pull request closed without merging**
