### PR TITLE
Fix/close survey after x responses

### LINKED ISSUE #561: [FIX] Close survey on X responses to check for current number of responses
**Is your feature request related to a problem? Please describe.**
As a user I want to Formbricks to stop me from making faulty inputs. Currently, the "Close survey after X responses" allows me to set a number lower than the current count of responses.

grafik

**Describe the solution you'd like**
If the status of the survey is "inProgress" the input should check the current number of responses and only accept a higher number.

**Additional context**
- We did a similar validation for the QuestionId input in the Survey Editor, for reference.
- **Additionally**: Please widen the input a bit so that 3 numbers can fit in easily

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

### PR DESCRIPTION
**Pull request by Pradumn27**
## What does this PR do?

This PR fixes the issue where a user was able to enter the limit of close survey after x responses less than or equal to the current number of responses.

Technical Details:
Have updated the useSurvey hook to take in a parameter for analytics where based on that we can query the analytics field from the survey when needed. Have used this analytics to check for the number of responses. 

https://github.com/formbricks/formbricks/assets/47187878/a3c84d9e-5eb0-4286-a325-3baf4376c552

Fixes #561 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a survey
- Add some responses to it
- Now edit this survey 
- Go to setting under the response options
- Click on Close survey on response limit
- See that you are not able to enter a number lesser than your current number of responses.

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — CHANGES_REQUESTED** [review]
@Pradumn27 thanks a lot for the fix PR 🎉 While testing I have the issue that if I - let's say - currently have 5 responses in my survey and try to insert a `4`, a `5` appears in the input field. But that makes it impossible to add a limit of, e.g. `42`, because I always get a `52`.
I think it would make more sense to e.g. show an error onChange or onBlur.

**Comment by Pradumn27** [comment]
> @Pradumn27 thanks a lot for the fix PR 🎉 While testing I have the issue that if I - let's say - currently have 5 responses in my survey and try to insert a `4`, a `5` appears in the input field. But that makes it impossible to add a limit of, e.g. `42`, because I always get a `52`. I think it would make more sense to e.g. show an error onChange or onBlur.

Thanks for the review @mattinannt, apologies for the late reply was really busy this week, have added the error on blur and also added validation for it on save: 

https://github.com/formbricks/formbricks/assets/47187878/aaea96f7-3514-42ef-af5d-2ea9083f2ea1

**Comment by Pradumn27** [comment]
Hey @jobenjada yeah the minimum count is set to the number of responses received, how do you wish to show it?

**Comment by Pradumn27** [comment]
> Hey @Pradumn27
> 
> Thanks for your contribution :)
> 
> The limit check works well now.
> 
> However, I do have an issue with the numbers field: https://tella.video/johanness-video-awli
> 
> When the count is below 10, the down icon doesnt do anything. If I click up, it goes up to 10. Is that because the minimum count has to be 10? If so, please display the toast, when a user clicks on either of the errors, so that the user understands that it isn't broken :)
> 
> Thanks!!

Hey @jobenjada, I understand your argument here but the issue is that the native html input element does not provide any listeners for the up and down button presses as per my short research in the past 1 hour, I was able to create a workaround with the onPointerDown event listener which basically listens whenever anything on the input element is clicked, but the issue with this is that it also gets triggered even when you just click on your input text box, also in the case described by you above it does not have hold of the changed value at the time of press but it has the previous value which also causes an issue if a user presses on the increment button from a previously lesser value they will still be prompted with an error toast, thus this solution also does not seem like the correct approach. Another approach was to listen to the keyDown events but that did not provide any credible change for our desired behavior.          
Open to any other suggestions.

**Comment by jobenjada** [comment]
@Pradumn27 I've added the response count to the toast message, this should be enough for now :) Thanks a lot!!

@mattinannt This is ready from UI/UX point of view.

**Review by mattinannt — APPROVED** [review]
@Pradumn27 thanks a lot for this PR 🤗 Great job! Just fixed that it only counts the completed responses when setting the limit 😊

I will merge the changes into main now! 💪🎉

**Pull request merged**
