### PR TITLE
feature/auto close survey

### PR DESCRIPTION
**Pull request by moritzrengert**
## What does this PR do?

Adds the option to set an autoClose delay in seconds, that closes the in-product survey if it is not hovered or clicked within the specified time. Also prepared the logic to include in the survey preview.

image

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Check if it isnt closing if autoClose is off
- Check if it is closing after x seconds for a few times
- Check if it isnt closing if the survey is hovered within the time 

## Checklist

- [x] I have read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have added comments to my code, particularly in hard-to-understand bits
- [x] I ran `pnpm build` and `pnpm lint` and checked for build and linting errors
- [x] My contribution does not cause any warnings
- [x] I have removed all `console.logs`
- [x] I have merged the latest changes from main onto my branch with `git pull origin main`
- [x] My contribution causes changes to the Formbricks Docs

### CODE REVIEW

**Review by mattinannt — CHANGES_REQUESTED** [review]
@moritzrengert thanks for the feature and for providing detailed screenshots 😊🙏 I have a few suggestions and bugs I would like you to solve first before we can merge:

* When auto-close is activated we need to display some kind of indicator to the user that the modal is closing automatically. My first idea was a reverse progress bar on top (in brand color) that starts full, gets smaller and ends empty when the number of seconds to auto-close elapsed.

Screenshot 2023-05-26 at 15 22 26

* I have a problem with auto-close when the survey is triggered by a button click: Create a survey that is triggered on an event that is send on button click, go to the app and click the button, the modal opens and auto-closes correctly. but when I press again the widget closes after a very short (random) time and I don't see the closing animation and it just disappears.

* When edit the auto-close time, click into the input field, delete the current value (6) and then write another value (e.g. 2), I always get a 0 in front. I would like to have it without the 0:
Screenshot 2023-05-26 at 15 30 45

* Please also fix the merge conflicts that just come up 😊

**Comment by moritzrengert** [comment]
Fixed the mentioned bugs and added the countdown progress bar. 🙂 

image

**Comment by moritzrengert** [comment]
Please check the countdown behaviour in the SurveyPreview, as I was not sure about the expected result @mattinannt.
Currently it runs once on load and also when the autoClose value is modified but has no effect once it's finished. I thought it would make the effect more clear to the user.

**Review by mattinannt — APPROVED** [review]
@moritzrengert thanks a lot for the changes 🤗 Works great and I am going to merge it now 😊
Only the stop-motion progressbar doesn't really feel nice, but I will let Johannes check if he can fix that with a smoother CSS animation.

**Pull request merged**
