### PR TITLE
fix: Loading Skeleton for survey summary page

### PR DESCRIPTION
**Pull request by RajuGangitla**
## What does this PR do?

This pr will add the loading.tsx in summary page in survey 

Fixes # (issue)
#3085

### Appreciated

[364928629-5fb65d05-b02e-47e4-8fd1-b282c1a0ec4c.webm](https://github.com/user-attachments/assets/4fe44cfa-29e4-4e20-86a0-73a5c71ae07b)

### CODE REVIEW

**Comment by jobenjada** [comment]
@RajuGangitla I've cleaned up the loading skeleton a bit and moved the loading into the StatCard because we'd see the hyphon for most of the time waiting for the data.

@gupta-piyush19 I also parallelized the API calls to speed up the data loading. Pls check. It seems like after each intervall we're making 8 API calls? Not sure if that's how it's intended but you know that better ;)

**Comment by RajuGangitla** [comment]
@jobenjada do i need to start working on any other issue or do i need to change anything here

**Comment by jobenjada** [comment]
@RajuGangitla I've awarded you the points and unassigend you from the issue so that you can pick up another one - thanks!

**Comment by gupta-piyush19** [comment]
LGTM 🚀

**Review by gupta-piyush19 — APPROVED** [review]

**Comment by RajuGangitla** [comment]
@jobenjada done

**Pull request merged**
