### PR TITLE
chore: Follow Formbricks LinkedIn Page 

### LINKED ISSUE #3530: [🕹️]  Follow Formbricks LinkedIn Page
### What side quest or challenge are you solving?

 Follow Formbricks LinkedIn Page 

### Points

50

### Description

I have followed Formbricks from my profile 

### Provide proof that you've completed the task

https://github.com/user-attachments/assets/b31ee87c-6996-4c00-99a0-7d9ad29f1a5e

### PR DESCRIPTION
**Pull request by hurairamuzammal**
Closes #3530

### CODE REVIEW

**Review by hurairamuzammal — COMMENTED** [review]
added proof folder in images folder instead of stand alone

**Comment by hurairamuzammal** [comment]
fix pull request title

**Comment by hurairamuzammal** [comment]
Please review my PR

**Comment by jobenjada** [comment]
next time pls open an issue, not a PR :)

/award 50

**Pull request closed without merging**
