### PR TITLE
feat: increase rate limit for client api endpoints

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## What does this PR do?
Increases the client side API (including response submissions) rate limits to 100 per 5 mins! 🤞🏼 

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — APPROVED** [review]
@ShubhamPalriwala looks great, thanks for the fix 😊

**Comment by connorwinston** [comment]
Is there anyway to override these constants with environment variables?

**Comment by mattinannt** [comment]
@connorwinston Why do you want to overwrite them? what problem are you facing?

**Comment by connorwinston** [comment]
@mattinannt I would like to increase the number of requests that can be made specifically for shares and the other limits in general, they are pretty low. Additionally, the way I have this hosted/internally protected on our intranet means that some routes receive the same ip regardless of the user, which kind of breaks this. It would be nice to either configure the rate limiter amounts via ENV or disable/enable the ratelimit in general via ENV.

**Pull request merged**
