### PR TITLE
[FOR-819] [FEATURE] Extensive Filtering of Responses

### PR DESCRIPTION
**Pull request by gitstart-formbricks**
## What does this PR do?

Fixes https://github.com/formbricks/formbricks/issues/434

Loom Video: https://www.loom.com/share/edc9182de9d8494ea0d80fba79bc7055?sid=85ae6a91-82f4-42fe-8c9e-410603fb6006

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [X] This change requires a documentation update

## How should this be tested?

It should accomplish requirements specified in https://github.com/formbricks/formbricks/issues/434

## Checklist

- [X] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [X] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by gitstart-formbricks** [comment]
Not yet ready for review.

**Comment by gitstart-formbricks** [comment]
This looks strange at first - selection appearing on both months. Days of the previous month grayed out showing the selection. It looked like an error at first.  If it isn't an issue we can leave it.
Screenshot 2023-07-03 at 19 40 21

An alternative is to hide days of the previous month
Screenshot 2023-07-04 at 10 35 39

**Comment by mattinannt** [comment]
Thanks a lot for the PR 🎉 
The date picker is a bit confusing for me. As a user I would expect to always choose the start and the end date when I open the date picker instead of only choosing the end and need to `Reset` the range for everything else.
Please see the first datepicker at [kayak.com](https://kayak.com) for reference: When the date picker is opened, the user sees the current selection. To update the range the user always needs to select the first date (from) (first click) and then end second date (to) (second click) and the picker closes automatically and applies the filter. 
Please change the datepicker to this behaviour and also remove the `Reset` option within the date picker.

**Comment by mattinannt** [comment]
The filters doesn't reset when I switch the survey.
Expected behaviour: The filters are only active for the current survey and as soon as I leave the page or switch to another survey, they get resetted.

https://github.com/formbricks/formbricks/assets/675065/6b665962-36bc-463c-8f13-8bb21e040620

**Comment by mattinannt** [comment]
The selection of personAttribute values doesn't work as expected. They show the same options for every attribute:
Screenshot 2023-07-06 at 11 11 59

Screenshot 2023-07-06 at 11 13 13

Screenshot 2023-07-06 at 11 13 26

**Comment by mattinannt** [comment]
When I have a multiple choice question with other-option and I select to show me all answers that chose this other option, I always filter out all responses and get zero results. Maybe because it checks if the value is `Other` but the value is a custom string/answer given by the user?
Screenshot 2023-07-06 at 11 34 18

Expected behaviour: Show all answers where the user choose the other option and provided a custom answer.

**Comment by gitstart-formbricks** [comment]
Recording of fixed issues
https://jam.dev/c/84d9bee8-6768-4283-ac58-68ef7c46f0d1

**Comment by mattinannt** [comment]
@gitstart thanks for the changes :-) But it seems something went wrong with your last update to the newest changes from main as the commits got pulled into this PR and also in list of changed files.

**Comment by gitstart-formbricks** [comment]
> @gitstart thanks for the changes :-) But it seems something went wrong with your last update to the newest changes from main as the commits got pulled into this PR and also in list of changed files.

Resolved

**Comment by mattinannt** [comment]
Thanks 😊💪
I have notices one issue with the selection of the filter for multiple choice questions. The user can only select one value, but should be able to select multiple options to say, "The value of the field is either X or Y"
In app:
Screenshot 2023-07-11 at 11 21 37
In Figma:
Screenshot 2023-07-11 at 11 23 23
----

For the Date-Picker, is it possible that we show a hover effect that selects the dates from the first selected date to the hovered date to make it clear to the user that he/she selects this range.
Kayak.com example:

https://github.com/formbricks/formbricks/assets/675065/2657bb04-c8d4-40fe-9dfb-8d54f2a3dcf9


In app:

https://github.com/formbricks/formbricks/assets/675065/9e4848fe-02ce-4033-b224-0008b8298cec

**Comment by mattinannt** [comment]
Thanks a lot for the changes 😊 The filters works really great 😊💪🎉 I changed a few small things but one thing is still an issue:

When a user opens a survey, he can select all the surveys questions in the filter. When he then moves into another survey there are not survey questions in the filter dropdown:

https://github.com/formbricks/formbricks/assets/675065/fae61f80-1e53-4269-8913-ed563e356e80

When this is fixed we can merge the feature 😊🚀

**Review by mattinannt — CHANGES_REQUESTED** [review]
Please fix the bug described in the comment above. After that we can merge the changes 😊

**Comment by gitstart-formbricks** [comment]
### demo video for resolving the issue 

https://jam.dev/c/b661f6c3-c314-42c9-b081-921dfdae620e

**Pull request merged**
