### PR TITLE
feat: keyboard usablity

### LINKED ISSUE #882: [FormTribe 🔥][500 Points] Keyboard Usability
### Welcome to the FormTribe!

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------
### Issue

Currently, the surveys are not properly keyboard accessible.

### Describe the solution you'd like

Provide a good keyboard UX

The easiest to get an understanding of the UX issue is experiencing it yourself. Here is a survey with one question of each question type:

https://formbricks.com/cln3gj0c77119od0ffeuvd4cu

### Tasks

Build a keyboard UX which consists mostly of TAB, ENTER and typing. Here is the walk through:

1. Welcome Page (and CTA question): ENTER to go to next question:

image

2. Free Text: 
- Default focus in text area (already works)
- TAB to jumps to NEXT button
- ENTER to go to next question
- hitting TAB a second time before ENTER the focus shifts to Back button before jumping to other elements on the page

image

3. Single Select: 
- Default: no option focussed 
- TAB to focus first option: Currently, the focus state is not shown but you can use the current hover state as the focus state.
- with every TAB jump through all options
- ENTER on any option selects it
- If possible, next TAB should directly jump to NEXT button instead of having to loop through all options
- after last option, jump to NEXT button
- ENTER goes to next question

image

4. Multi Select: Same UX like above just without jumping to Next button after selecting an option

image

5.  NPS Question: 
- Default: no option focussed
- TAB: Focus jumps to 1 (also needed to add current hover state as focus state)
- Every TAB jumps to next option
- ENTER selects option and goes to next question

image

6. Rating Question: Same UX

image

7. Consent Question: 
- Default: Nothing selected
- TAB focusses checkbox. Here we're missing both a hover and a focus state, please make a suggestion that matches the overall UI
- Enter checks box
- TAB to select button, ENTER to submit

image

### Technical requirements

The keyboard accessibility will be part of our survey package (@formbricks/surveys) which is part of formbricks-js. Formbricks-js is not only used to the link survey but also for in app surveys. This is why we are very cautious about the package size of formbricks-js.

**Any solution which does NOT install a bloated 3rd party lib to handle keyboard accessibility is heavily favoured. We want to keep the bundle size as tiny as possible.**

Please also make sure that the keyboard usability work in both web-app surveys and link surveys.

### PR DESCRIPTION
**Pull request by joyal007**
## What does this PR do?

Fixes #882

Adding keyboard usage inside survey form 
Inprogress

https://www.loom.com/share/83678422f8c54803be2b33bf59feb785?sid=8eb48c85-03be-489e-8c91-95fdbaf8112c

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
Hey @joyal007, thanks a lot for opening up a PR! 💯  I see that you have mentioned "in progress", in your PR description. Is it still in progress? Or is it ready for review? If it's still in progress, can you convert it to a draft PR please? thanks.

**Comment by joyal007** [comment]
> Hey @joyal007, thanks a lot for opening up a PR! 💯 I see that you have mentioned "in progress", in your PR description. Is it still in progress? Or is it ready for review? If it's still in progress, can you convert it to a draft PR please? thanks.

It's ready for review

**Comment by xnsei** [comment]
@joyal007 some optional improvements:


- <button /> don't need `tabIndex={0}` as its already focusable
  ```
  packages/surveys/src/components/CTAQuestion.tsx
  <button
      tabIndex={0}
      type="button" 
  />
  ```

- I see you added `tabIndex={idx+1}` for labels. We can simply do `tabIndex={0}` since they'll receive focus in the same order they appear
  ```
  packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
  <label
      key={choice.id}
      tabIndex={idx + 1} 
  />
  ```
- since we can simply use `tabIndex={0}` in case of choice/rating questions, simply pass 1/2 as the tabIndex for buttons
  ```
  packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
  <BackButton
      tabIndex={questionChoices.length + 3}
      backButtonLabel={question.backButtonLabel}
      onClick={onBack}
  />
  ```

**Comment by joyal007** [comment]
> @joyal007 some optional improvements:
> 
> * don't need `tabIndex={0}` as its already focusable
>   ```
>   packages/surveys/src/components/CTAQuestion.tsx
>   <button
>       tabIndex={0}
>       type="button" 
>   />
>   ```
> * I see you added `tabIndex={idx+1}` for labels. We can simply do `tabIndex={0}` since they'll receive focus in the same order they appear
>   ```
>   packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
>   <label
>       key={choice.id}
>       tabIndex={idx + 1} 
>   />
>   ```
> * since we can simply use `tabIndex={0}` in case of choice/rating questions, simply pass 1/2 as the tabIndex for buttons
>   ```
>   packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
>   <BackButton
>       tabIndex={questionChoices.length + 3}
>       backButtonLabel={question.backButtonLabel}
>       onClick={onBack}
>   />
>   ```

I have tried setting `tabIndex={0}` but when it set so, browser show some abnormal behaviour to press Tab twice to move to next option. I don't know whether this issue only exist in my browser only.

**Comment by xnsei** [comment]
@joyal007 if I'm not wrong, you're facing this with choice/rating questions, right? I've tried implementing it on local, and it was working fine. What browser you're using? Maybe try using Chrome/Firefox?

**Comment by joyal007** [comment]
> @joyal007 if I'm not wrong, you're facing this with choice/rating questions, right? I've tried implementing it on local, and it was working fine. What browser you're using? Maybe try using Chrome/Firefox?

Okay, i am using brave

**Comment by joyal007** [comment]
> > @joyal007 some optional improvements:
> > 
> > * don't need `tabIndex={0}` as its already focusable
> >   ```
> >   packages/surveys/src/components/CTAQuestion.tsx
> >   <button
> >       tabIndex={0}
> >       type="button" 
> >   />
> >   ```
> > * I see you added `tabIndex={idx+1}` for labels. We can simply do `tabIndex={0}` since they'll receive focus in the same order they appear
> >   ```
> >   packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
> >   <label
> >       key={choice.id}
> >       tabIndex={idx + 1} 
> >   />
> >   ```
> > * since we can simply use `tabIndex={0}` in case of choice/rating questions, simply pass 1/2 as the tabIndex for buttons
> >   ```
> >   packages/surveys/src/components/MultipleChoiceMultiQuestion.tsx
> >   <BackButton
> >       tabIndex={questionChoices.length + 3}
> >       backButtonLabel={question.backButtonLabel}
> >       onClick={onBack}
> >   />
> >   ```
> 
> I have tried setting `tabIndex={0}` but when it set so, browser show some abnormal behaviour to press Tab twice to move to next option. I don't know whether this issue only exist in my browser only.

I have tired same in firefox. Set all the options with `tabIndex=0` and with buttons 1 & 2 .
It's not working as expected. The control doesn't reach to button as expected.

https://www.loom.com/share/d3220f4b5eaa4a1e919aa0ef7faa4cf8?sid=d2a0c225-5c64-4e9d-a5c3-afac9a7ee66a

**Comment by xnsei** [comment]
hmm, that's weird. can you maybe commit your changes so that I can have a better look. we can always revert 🙂

**Comment by ShubhamPalriwala** [comment]
Heyyy @joyal007 and @xnsei, super awesome to see both of you collaborate on this 🚀 

Let me know when the PR is ready for my review once its final from both of your ends. Really looking forward to this one 🤞🏼

**Comment by jobenjada** [comment]
Hey @joyal007 and @xnsei - thanks for your good work on this :)

Testing it, I noticed one UX issue: In long text fields, you cannot add a new line anymore, because ENTER always submits the question.

**Ideally, we are able to make the keyboard UX dependent on the type of input we are seeing.** Some context:

In the Survey Editor, we can decide if we want to have a long answer or a short answer:

image

- If we're dealing with a short answer, hitting ENTER submits the question
- If we're dealing with a long answer (so a textarea), hitting ENTER adds a new line and TAB + ENTER submits the question

This will be particularly important because we will use the same input field for Email, URL, Number and Phone Number very soon (PR is 90% done). For these, we definitely want to have the ENTER = Submit UX :)

From a technical point of view, you ideally make the keyboard UX dependent on the long answer variable in the survey object. This would allow your solution to be automatically compatible with the work were doing in the other PR 🙏 

----

You cannot unselect multi select fields with ENTER:

image

-----

On single select (radio) type questions, I feel it's not necessary to have to hit ENTER to select and TAB + ENTER to move to the new question. Since only one answer is possible anyways due to the question type, I would like to submit the question with the same ENTER used to select an option. 

So ideally: TAB to jump to first option, TABs to jump to next options, ENTER to select and submit question

image


------

CTA questions get skipped

https://tella.video/johanness-video-963g

----

The rest looks good, love the new keyboard UX!!  🔥🔥🔥 Good work :)

**Comment by joyal007** [comment]
> Hey @joyal007 and @xnsei - thanks for your good work on this :)
> 
> Testing it, I noticed one UX issue: In long text fields, you cannot add a new line anymore, because ENTER always submits the question.
> 
> **Ideally, we are able to make the keyboard UX dependent on the type of input we are seeing.** Some context:
> 
> In the Survey Editor, we can decide if we want to have a long answer or a short answer:
> 
> image
> * If we're dealing with a short answer, hitting ENTER submits the question
> * If we're dealing with a long answer (so a textarea), hitting ENTER adds a new line and TAB + ENTER submits the question
> 
> This will be particularly important because we will use the same input field for Email, URL, Number and Phone Number very soon (PR is 90% done). For these, we definitely want to have the ENTER = Submit UX :)
> 
> From a technical point of view, you ideally make the keyboard UX dependent on the long answer variable in the survey object. This would allow your solution to be automatically compatible with the work were doing in the other PR 🙏
> 
> You cannot unselect multi select fields with ENTER:
> 
> image
> On single select (radio) type questions, I feel it's not necessary to have to hit ENTER to select and TAB + ENTER to move to the new question. Since only one answer is possible anyways due to the question type, I would like to submit the question with the same ENTER used to select an option.
> 
> So ideally: TAB to jump to first option, TABs to jump to next options, ENTER to select and submit question
> 
> image
> CTA questions get skipped
> 
> https://tella.video/johanness-video-963g
> 
> The rest looks good, love the new keyboard UX!! 🔥🔥🔥 Good work :)
> 
> **Please mark this as complete when it's ready for review from your side!**

I have completed the above assignments

**Comment by jobenjada** [comment]
@joyal007 Thanks a lot!

I found another Edge case: The "Other" options:

image

If you hit Enter after typing something in, it does not submit the question but unselects "Other".

Secondly, and this is optional: If a user submits a SingleSelectQuestion via keyboard, can you add a 500ms (or so) time out so that the user can see which option got selected?

Other than that, it works super smooth! Good job 🚀

**Comment by jobenjada** [comment]
@joyal007 Whoop whoop! It's merged 🤸 

Thanks a lot, this makes using Formbricks a lot easier :) We'll tweak the UX a bit with hotkey indicators and subtile animations to signal to users which options they selected, but this will be done in the process of our UI revamp.

Great work! Thanks :))

**Pull request merged**
