### PR TITLE
feat: created icon bar component in survey overview

### LINKED ISSUE #4219: [FEATURE] Create icon bar component and use in survey overview
### Is your feature request related to a problem? Please describe.

In the Survey Overvie we have this button bar:
image

We want to change it for more clarity and to take up less space.

### Describe the solution you'd like

Our friends at Cal.com built this cool icon bar:
image

### Tasks
1. Have a look at their repo and create the corresponding component in ours
2. Create the icon bar for the following actions:

- Preview
- Copy Link
- Embed
- Alerts
- Send to Panel
- Edit

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aryamantodkar**
## What does this PR do?

Fixes #4219 

Reviewed Cal.com icon bar and created a similar reusable icon bar component with the following actions -

- Preview
- Copy Link
- Embed
- Alerts
- Send to Panel
- Edit

https://www.loom.com/share/4c9d9d3c6a674756957077c07f461ed8?sid=ca514951-8866-4ea2-bbc9-14b27f94a647

Screenshot from 2024-11-13 22-10-18

Screenshot from 2024-11-13 22-10-47

## How should this be tested?

- Go to the Surveys Tab
- Open an Individual Survey
- Check the new icon bar in the top right corner for actions like Preview, Copy Link, Embed, Alerts, Send to Panel, Edit

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced an `IconBar` component for streamlined access to survey actions, replacing dropdown menus with icon-based buttons.
	- Enhanced `Button` component with a new `Wrapper` for improved tooltip handling and rendering logic.

- **Bug Fixes**
	- Improved accessibility and usability by consolidating actions and removing dropdown complexities.

### CODE REVIEW

**Comment by jobenjada** [comment]
hey @aryamantodkar thanks so far!

did you have a look a the cal.com repo and see how they handle the icon bar? I suppose they have a component for that.

in any case, it's not necessary to add any CSS to global CSS, we work with Tailwind.

**Comment by aryamantodkar** [comment]
Thanks, @jobenjada My apologies for the oversight, I'll make the necessary changes. I couldn't override the existing background property with Tailwind, so I opted for Global CSS instead.

**Review by jobenjada — APPROVED** [review]
image

looks great from UI / UX :)

**Review by gupta-piyush19 — APPROVED** [review]
LGTM! 🚀 
Thanks @aryamantodkar for the feature 🙌

**Review by gupta-piyush19 — APPROVED** [review]

**Review by gupta-piyush19 — APPROVED** [review]

**Pull request merged**
