### PR TITLE
feat: Enhance Github Issue Templates for better usability

### LINKED ISSUE #587: [FEATURE] Enhance Github Issue Templates for better usability
**Is your feature request related to a problem? Please describe.**
The current Github Issue templates for creating bugfixes and feature request are one editor window with comments indicating where to fill information.
Screenshot 2023-07-19 at 17 55 09

This isn't very easy to handle for first time users or less technical users.

**Describe the solution you'd like**
While filling out a bug report in the [gitpod-repo](https://github.com/gitpod-io/gitpod) I noticed they were able to show a better editor to the user with multiple input field. This is much easier to understand and fill out by the users.
Screenshot 2023-07-19 at 17 58 22
The template can be found here: https://github.com/gitpod-io/gitpod/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml

Please update the Formbricks Templates in `.github/ISSUE_TEMPLATE/` to also have multiple input fields for the different questions that are asked.

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

### PR DESCRIPTION
**Pull request by yashhhguptaaa**
## What does this PR do?

- Adds Enhanced version of Feature Request and Bug Report Github Page.

Fixes #587

https://github.com/formbricks/formbricks/assets/82795074/1c74ab78-2093-4661-9371-8922735f35a5

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
looks great! One little mistake a I saw in the video:

The field to fill in the **Desktop** info isn't an input field yet. Can you update this? 

Apart from this, ready to merge! 🚀

**Comment by yashhhguptaaa** [comment]
> looks great! One little mistake a I saw in the video:
> 
> The field to fill in the **Desktop** info isn't an input field yet. Can you update this?
> 
> Apart from this, ready to merge! 🚀

Sorry, I actually missed that 😅. Let me just do

**Comment by mattinannt** [comment]
> > @yashhhguptaaa looks awesome 🎉 Can we maybe also move the checkboxes over to real checkboxes? https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema
> 
> We can do, but what about the 2nd option `- [ ] self-hosted Formbricks, version/commit: [please provide]`, in this we need `version/commit` input from the user ?? @mattinannt

I think we can omit the version/commit for now 😊

**Comment by yashhhguptaaa** [comment]
> > > @yashhhguptaaa looks awesome 🎉 Can we maybe also move the checkboxes over to real checkboxes? https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema
> > 
> > 
> > We can do, but what about the 2nd option `- [ ] self-hosted Formbricks, version/commit: [please provide]`, in this we need `version/commit` input from the user ?? @mattinannt
> 
> I think we can omit the version/commit for now 😊

Sure

**Comment by yashhhguptaaa** [comment]
> > > @yashhhguptaaa looks awesome 🎉 Can we maybe also move the checkboxes over to real checkboxes? https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema
> > 
> > 
> > We can do, but what about the 2nd option `- [ ] self-hosted Formbricks, version/commit: [please provide]`, in this we need `version/commit` input from the user ?? @mattinannt
> 
> I think we can omit the version/commit for now 😊

@jobenjada @mattinannt Done. Updated the PR and also the PR's description

**Comment by mattinannt** [comment]
@yashhhguptaaa Awesome 💪 Thanks a lot for making the changes 😊 Will merge the PR now 🎉

**Pull request merged**
