### PR TITLE
fix: add delete confirmation modal before deleting tags

### PR DESCRIPTION
**Pull request by vaishak10**
## What does this PR do?
Delete Confirmation modal before deleting a tag. This is a replacement to the alert message before deleting the tag.

https://github.com/user-attachments/assets/2674ff91-b37c-41e1-8bad-30104131a590

Fixes # (issue)
[BUG] Delete tags not working once merge operation is completed. #2886

## How should this be tested?

- Select the survey
- Click on Responses Tab
- Click on the settings icon
- Delete any tag
- The Delete Confirmation Modal appears with the tag name which you want to delete
- Once you click on delete the tag will be deleted

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [X] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [X] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by Dhruwang — APPROVED** [review]
Thanks for the fix, works well 🚀🙌🏻😊

**Comment by Dhruwang** [comment]
Hey @vaishak10 , can you please sign the CLA 😊 ?

**Comment by vaishak10** [comment]
> Hey @vaishak10 , can you please sign the CLA 😊 ?

Hey @Dhruwang, Have agreed to the CLA!

**Comment by mattinannt** [comment]
@vaishak10 We have issues with merging the PR due to the CLA license checks ( https://github.com/formbricks/formbricks/pull/2912#issuecomment-2241079104 ).
Do you have an idea why the username `Vaishak` is also listed a contributor in the PR? Did you change the username or updated your git config?

If we can't figure this out in this PR, you would need to create a new PR with these code changes so we can get the git history right and merge this PR.

**Pull request merged**
