### PR TITLE
feature/add consent question

### PR DESCRIPTION
**Pull request by moritzrengert**
## What does this PR do?

Adds the consent question type that can be used for terms&conditions etc.

image
image
image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Add consent question type to link survey and in-product survey and check UI
- Submit both checked and skipped and check summary

## Checklist

- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — CHANGES_REQUESTED** [review]
Thanks for building this feature 💪🙏

There seems to be an issue with logic jumps: I had a link survey with an optional consent question and a "when skipped" logic that wasn't triggered.

Also in not-required consent questions I think we need an additional logic jump option `checked` to jump based on the decision if the checkbox was checked or not.

Please always make sure there are no build errors before requesting a review 😊 🐛

**Comment by mattinannt** [comment]
> How should the buttons be implemented ? Currently the buttons „Next“ and „Skip“ do exactly the same on non-required questions. Is this the expected behavior @mattinannt ? 🙂

just checked back with the other question types we have: please remove the skip button (to make it consistent with an optional multi-select question type)

**Comment by mattinannt** [comment]
> Just to clearify: If the consent question is required, there is only the **checked** option right? Because **submitted** would be the same and **skipped** is not possible. If it is not required, there is only **checked** and **skipped** because **skipped** and **submitted** would be the same?
> 
> I am a bit confused here, as this seems a bit complicated... 😅

I would say I should be like this (renamed `checked` to `accepted` to make it clearer)

**required**:
- submitted (to override where to go next)

**not required**:
- submitted (to override where to go next)
- accepted (to override where to go only when consent accepted)
- skipped (to override where to go only when consent not accepted)

Some conditions have overlaps but as with the other question types I think it's good to give the users more options to choose from when building the logic jumps.

**Comment by moritzrengert** [comment]
I added the requested logic and tested on the in-app widget and link survey 🙂

**Review by mattinannt — APPROVED** [review]
@moritzrengert thanks for the recent changes 😊 Works great! 💪
I tested the different conditions a bit and realised that some parts can be confusing. I renamed the `submitted` state in the CTA question to `clicked` and also in consent question reduced the possible states to `accepted` and `skipped`. 😊

I will merge the changes now 😊

**Pull request merged**
