### PR TITLE
fix: gitpod setup issue

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Error:-

Screenshot_2024-04-09_123445

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@anikdhabal thanks for the PR. The `pnpm clean && pnpm i && pnpm go` routine is more a last resort for debugging than something that should happen every time a gitpod container is started. The command purges all existing build and package information and starts from scratch.
Did the error you were facing happen consistently when starting the gitpod setup?
I was not able to reproduce the issue with the current commands in main and for me the container and dev server is starting correctly.

Screenshot 2024-04-15 at 11 00 08

**Comment by anikdhabal** [comment]
> @anikdhabal thanks for the PR. The `pnpm clean && pnpm i && pnpm go` routine is more a last resort for debugging than something that should happen every time a gitpod container is started. The command purges all existing build and package information and starts from scratch. Did the error you were facing happen consistently when starting the gitpod setup? I was not able to reproduce the issue with the current commands in main and for me the container and dev server is starting correctly.
> 
> Screenshot 2024-04-15 at 11 00 08

Hey @mattinannt I consistently facing this error when starting the gitpod setup. And the error just visible after creating an account or login. There is no issue with the starting of container and dev server.

**Comment by mattinannt** [comment]
@anikdhabal Unfortunately I was not able to reproduce the issue. Are you also facing the issue if you create a Gitpod instance directly from the `formbricks/formbricks` repo or only from your fork?

@ShubhamPalriwala Can you please also check if you run into this issue when setting up a new Gitpod instance and creating an account/logging into Formbricks?

**Comment by anikdhabal** [comment]
> @anikdhabal Unfortunately I was not able to reproduce the issue. Are you also facing the issue if you create a Gitpod instance directly from the `formbricks/formbricks` repo or only from your fork?
> 
> @ShubhamPalriwala Can you please also check if you run into this issue when setting up a new Gitpod instance and creating an account/logging into Formbricks?

Only from my fork.

**Comment by ShubhamPalriwala** [comment]
Hey @anikdhabal, thanks for opening the PR. I tried to reproduce it for both:
1. this formbricks repo
2. my forked formbricks repo
and both of them worked for me with the existing setup! I also noticed that your fork's main branch is a little behind than this repo. Can you try syncing the branch and then trying again?

**Comment by mattinannt** [comment]
I'm closing this PR for now since the bug it's solving is not reproducable. Let's keep the discussion up to make sure we are able to solve all issues for @anikdhabal

**Pull request closed without merging**
