### PR TITLE
fix: Increase card size for link surveys

### LINKED ISSUE #3293: [🕹️] Increase card size for link surveys
### Is your feature request related to a problem? Please describe.

There isn't really a need to squeeze **link surveys** in such a small card for link surveys:

image

### Describe the solution you'd like

Increase the card size a bit for link surveys:

image

check if increasing `max-w-md` to `max-w-lg` based on survey type works. If it's too wide, choose custom value `32rem`

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RajuGangitla**
## What does this PR do?
changing the width of the card conditionally based on survey type 

Fixes #3293 

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling logic for the `PreviewSurvey` component with conditional class application.

- **Bug Fixes**
	- Adjusted the `z-index` of the `PreviewSurvey` component for improved stacking context.

### CODE REVIEW

**Comment by anubhavkushagra** [comment]
please assign tis

**Comment by anubhavkushagra** [comment]
please assign this to me

**Comment by silentboy-07** [comment]
Dear Sir/Madam

I'm Vikas Singh, a developer passionate about Android, web technologies, and API integration. I'd love to contribute to your project and grow alongside the open-source community. Excited for the opportunity to collaborate!

**Pull request closed without merging**
