### PR TITLE
fix: add toast and error handler for multiple team/product creation with existing team/product name

### LINKED ISSUE #994: [FEATURE][FormTribe 🔥][150 Points] Prohibit two identical product names
### Issue Summary

Multiple Product and Team can be added with same name!
This issue can lead to confusion to user working with several teams on different products !
And it get disappear after few minutes .

### Steps to Reproduce

Click on the profile Avatar :

**For Product**
1.click on [My Product] product button .
2.At drop down click on [+ Add Product] button
3.Fill name[newproduct] in Name (fill up)

Follow step 1 <to> 3 few times !

**For team**
Currently its not showing up the newly created team but u can see it few minutes after creating multiple team with same name

1.click on [<user> team] Team button .
2.At drop down click on [+ create team] button
3.Fill name[newTEAM] in Name (fill up)

Follow step 1 <to> 3 few times !

after doing this you will see multiple Product/Team with same name in the dropdown menu !

Again logout & login or after few minutes it will get disappeared ! ( don't know the exact timing )
**Note : after logout & login multiple entries of products get disappear but team name still there !**  

### Expected behavior

Since it get disappeared ! ( logout and login )
it should check list of previously added [product/team names] and throw errors team already exist !

or 

different solutions can be implemented ! 

### Other information

_No response_

### Screenshots

Product : 
https://www.loom.com/share/1bc4c0b6bb9b4136bc8c407bbabd51d4?sid=ce312efe-c3c6-40c9-a596-ff94ecd3c807

Team Name ;
https://www.loom.com/share/0dbbaa2d700c45c88add80b844f0c9f9?sid=09de555a-d897-4b53-a709-8729a87bb485

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by anjy7**
## What does this PR do?

1. Added error and success toast to create new product model 
2. Added error  toast to create new team model 
3. Added error check for same team name already exists while team creation
4. Added error check for same product name already exists while product creation

Fixes #994 

Screenshot from 2023-10-07 17-17-07
Screenshot from 2023-10-07 17-28-35

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Create a new team with the existing same named team
- Create a new product with the existing same named product

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [X] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [X] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@anjy7 Thanks a lot for the PR :-)
Multiple products with the same name in a team can be confusing and we shouldn't allow this.
But I'm not sure with team names in general, as normally it doesn't lead to problems easily because most likely a user is not of both teams. I will discuss this with the team :-) 
Also if we enforce things like this we should also enforce them on the database level.

**Comment by mattinannt** [comment]
@anjy7 We decided internally that we would only like to make product names within a team unique and still allow team names to be the same within Formbricks.
Can you please remove the check for the team?
Also I would like to enforce this within the database (prisma schema) and skip the additional check in the product services :-)

**Comment by anjy7** [comment]
Sure @mattinannt, I’ll make the changes

**Comment by anjy7** [comment]
hey @mattinannt, I have removed the additional checks in the team and product services. Do you want me to add `@@unique([teamId, name])` in the product prisma schema?

**Comment by mattinannt** [comment]
@anjy7 Yes, please :-)
Also make sure the the error message is still understandable for the users and that it's working for both creating a new product as well as update the product name in the settings :-)

**Comment by anjy7** [comment]
> @anjy7 Yes, please :-) Also make sure the the error message is still understandable for the users and that it's working for both creating a new product as well as update the product name in the settings :-)

Hey @mattinannt, just had one doubt in showing a better error message while creating a new product and updating the name of a product - where would it be better to handle the error - in the frontend component or in the create/update product service?

for context - currently I get "Database operation failed" while updating a product name and "Invalid `prisma.product.create()` invocation:Unique constraint failed on the fields: (`teamId`,`name`)" in case of creating a new product

**Comment by mattinannt** [comment]
> > @anjy7 Yes, please :-) Also make sure the the error message is still understandable for the users and that it's working for both creating a new product as well as update the product name in the settings :-)
> 
> Hey @mattinannt, just had one doubt in showing a better error message while creating a new product and updating the name of a product - where would it be better to handle the error - in the frontend component or in the create/update product service?
> 
> for context - currently I get "Database operation failed" while updating a product name and "Invalid `prisma.product.create()` invocation:Unique constraint failed on the fields: (`teamId`,`name`)" in case of creating a new product

@anjy7 Ok, makes sense. Let's just say in the toast `Unable to save product information` and we will do proper checks later with form input validation.

**Comment by anjy7** [comment]
> > > @anjy7 Yes, please :-) Also make sure the the error message is still understandable for the users and that it's working for both creating a new product as well as update the product name in the settings :-)
> > 
> > 
> > Hey @mattinannt, just had one doubt in showing a better error message while creating a new product and updating the name of a product - where would it be better to handle the error - in the frontend component or in the create/update product service?
> > for context - currently I get "Database operation failed" while updating a product name and "Invalid `prisma.product.create()` invocation:Unique constraint failed on the fields: (`teamId`,`name`)" in case of creating a new product
> 
> @anjy7 Ok, makes sense. Let's just say in the toast `Unable to save product information` and we will do proper checks later with form input validation.

Hi @mattinannt , I have made the changes, please have a look
Screenshot from 2023-10-10 20-31-02
Screenshot from 2023-10-10 20-33-16

**Review by mattinannt — APPROVED** [review]
@anjy7 Thanks for making the changes :-) Looks great!
I hope the migration will work in production ;-)

**Pull request merged**
