### PR TITLE
Validate Survey Editor Form

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## What does this PR do?
Multiple minor UX fixes in the Survey Editor:

1. Submitting a Survey with 0 questions was possible before, now they cannot:
Screenshot_2023-09-01-16-29-27_5760x1080

2. Consent question could be created without any text next to the checkbox, now they cannot:
Screenshot_2023-09-01-16-31-45_5760x1080

4. Multi Choice questions (both single and multi-select) could have multiple "exactly same" options, now they cannot:
Screenshot_2023-09-01-16-33-02_5760x1080

5. Long single word text description was breaking the Formbricks Thank you card. now it just wraps:
Screenshot_2023-09-01-16-34-10_5760x1080

6. Multiple Logic Jumps were created without setting the previous one, now they are not allowed to:
Screenshot_2023-09-01-16-36-45_5760x1080

7. Exactly same Logic Jumps could be created multiple times, now it is not possible to:
Screenshot_2023-09-01-16-44-57_5760x1080

8. And to add on the above point, now even 2 "conditons" are also not allowed to point to a different destinatio
Screenshot_2023-09-01-16-46-49_5760x1080

9. If the user made a question not-required, then added "is skipped" condition, then made it required,  we would show it as blank in the frontend but in the backend, still store it as an "is skipped". Now we show the "is skipped" option beforehand itself but when the user tries to save it, give them an error:
Screenshot_2023-09-01-16-48-54_5760x1080

10. Setting duplicate questions IDs previously used to send 2 prompts, 1 being the error toast and then automatically set a QuestionId and save the survey! Now we throw an error and dont save the survey until the user manually changes the questionId!

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey Shubham, thanks for working on this!

Here is my feedback:

1. Its uncommon to use " ! " in toast messages. I removed it from all of them and update the wording.

2. I really like that the card color changes to red at the cards where no question is filled in. Please also apply this to issues with the Logic Editor. 

3. Logic Jumps a required question not working properly.

These are my logic jumps:
image

And Im getting this error message, despite the following question not being Required:
image

Also, the toast loads kind of spikey so there is something else in the bush. I think your logic tries to display two different toasts. At this point, it should display the "You have two identical logic jumps", right?

4. Validation after blur?
When you add a new option, the card turns red, because it is empty at first. This is bad UX because it tells the user "You're doing something wrong" while they are not. Can we maybe move the validation to onBlur (or find a different fix)
image


Thank you!

**Comment by jobenjada** [comment]
Heya!

Here more context on the wrong error message: https://tella.video/johanness-video-9d07

In this video we have two bugs: https://tella.video/johanness-video-gzis

- And here for the validation on blur / inconsistent validation between multi and single select
- Wrong error message when the options are identical (warns that field is empty but it should warn that value are identical)

Please thoroughly test all cases :)

**Comment by ShubhamPalriwala** [comment]
Thanks a ton for the detailed video. I've made a fix and attaching a screen recording herewith to save your time:
https://www.loom.com/share/773591c99ef3425698690134d2706af5?sid=e6b1d143-7323-49c0-b1f7-f6bb9d84be62


And the same has been applied for Single Select as well! And have added appropriate error messages now instead of the generic Input all required fields!

And I have also handled to not show the "is skipped" in required question:
https://www.loom.com/share/40a83f79a5e54b6eac37673e7fef2e97?sid=f8c0c330-6f9d-45da-8d2a-d279431f7c27

Let me know if there are any other changes to be made as well 🤞🏼

**Comment by ShubhamPalriwala** [comment]
Hey @jobenjada, I have resolved the merge conflicts in the PR, please view the above screen recordings and do let me know if there are changes to be made, thanks! 🙏🏼

**Comment by jobenjada** [comment]
Hey @ShubhamPalriwala - Sorry I didnt get to merge this sooner, my bad.

Testing it through once more, I noticed a few more things:

1. Publish button loading states
When you hit save and one of the validation fires off, the UX is good. But when you hit Publish, the buttons load forever. So similar to the Save button, show the Error message and dont set the buttons to loading state:

image

Then we're good to merge! :)

**Pull request merged**
