### PR TITLE
fix/logic on question update

### PR DESCRIPTION
**Pull request by moritzrengert**
## What does this PR do?

Fixes [FOR-980](https://linear.app/formbricks/issue/FOR-980/[bug]-logic-jumps-break-when-the-text-the-answer-option-changes)
Updates related logic values on multi select option change.

https://github.com/formbricks/formbricks/assets/42251569/ae69f06b-771c-4f22-85b5-9f69093ab313

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Update MultiSelectSingleChoice choice label and see if the logic value updates as well and still performs the logic
- Update MultiSelectMultiChoice choice label and see if the logic value updates as well and still performs the logic

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — CHANGES_REQUESTED** [review]
@moritzrengert thanks a lot for the fix 😊💪
While testing I have noticed another issue that arises with this fix.
If we have the same option label (even for a short time while writing) the logic jump label gets messed up. That could happen if you have a label `Käse` and are writing `Käsekuchen` next.

https://github.com/formbricks/formbricks/assets/675065/c52f1356-df37-41e6-b893-7ab9ab45c919

**Comment by moritzrengert** [comment]
What would be your preferred way of solving this @mattinannt ? I just updated the logic, based on the label text but that comes with the issue you mentioned above. I could possibly change the whole system to using id's but the reason that I didn't in the first place, is that the js widget currently isn't dealing with choice id's so it would be a quite big of a change...

**Comment by jobenjada** [comment]
@moritzrengert pls resolve merge conflicts :)
@mattinannt can we get this merged after?

**Review by mattinannt — APPROVED** [review]
Sorry that reviewing took so long. Works great, thanks a lot for making the changes 🤗💪

**Pull request merged**
