### PR TITLE
fix: Create dark mode version of Code Block on landing page

### PR DESCRIPTION
**Pull request by itzabhinavarya**
## What does this PR do?

This PR Fixes the issue no. #1311 

Note : As there is no confirmed PR opened for this issue within 24hrs, So i have raised a new PR for this issue. I request @jobenjada @ShubhamPalriwala Sir to review this PR and if there is any changes required then let me know. If everything looks good then kindly merge this PR. Thanks :)

I have changed the text from white to text-amber-400, because that looks more clear and good in both mode. And the UI is also looking better with this text color.

Fixes # (issue)

Dark Mode : 

image

Light Mode : 

image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change adds a new database migration
- [x] This change requires a documentation update

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### CODE REVIEW

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala @jobenjada Sir, Gentle reminder for this PR.

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala @jobenjada Sir, Please look at the PR.

**Comment by jobenjada** [comment]
@itzabhinavarya please dont spam

The styling looks off: The text shadow is still there and some of the symbols are highlight weirdly:

image

Please fix that

**Comment by itzabhinavarya** [comment]
@jobenjada @ShubhamPalriwala  Sir, I apologize for mentioning you again and again but that was my curiosity for solving this issue. 
I have made changes, Kindly look at them.  As prism css is applying dynamically, So the only solution i came up with a global css property to remove the background color from the operators. 

here is preview:

image

**Comment by jobenjada** [comment]
@itzabhinavarya I've updated it to not use global styling, added it to merge queue - thanks! :)

**Comment by itzabhinavarya** [comment]
@jobenjada Sir, Waaohh Great approach. i wasn't aware with this. But that's a really great way to do that.
Thanks :)

POV : Still understanding the code. 😂

**Pull request merged**
