### PR TITLE
feat/improve survey progress bar

### PR DESCRIPTION
**Pull request by moritzrengert**
## What does this PR do?

Fixes [FOR-725](https://linear.app/formbricks/issue/FOR-725/progressbar-tweaks)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [ ] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by jobenjada — COMMENTED** [review]
https://tella.video/johanness-video-c6pp

The most recent change leads to the progress bar being frozen at 50% until the survey is completed.

What I tried to say is: On the first question, it should never be more than 50%. Dependening on the logic so how many questions follow, it either jumps to the end (2 questions) jumps to 2/3ish (3 questions) etc. 

**The goal is for the progress bar to never move backwards and still move a bit forward after every question answered.**

Cheers :)

**Comment by moritzrengert** [comment]
> https://tella.video/johanness-video-c6pp
> 
> The most recent change leads to the progress bar being frozen at 50% until the survey is completed.
> 
> What I tried to say is: On the first question, it should never be more than 50%. Dependening on the logic so how many questions follow, it either jumps to the end (2 questions) jumps to 2/3ish (3 questions) etc.
> 
> **The goal is for the progress bar to never move backwards and still move a bit forward after every question answered.**
> 
> Cheers :)

The issue here is not that the progress is miscalculated but the logic of the survey you used, is structured so that every question could jump to the last question. As I implemented that it can never be more than 50%, it always stays there. I understand that this behaviour is not ideal but I am not sure about the best solution to this... @jobenjada

**Comment by jobenjada** [comment]
@moritzrengert I had to play around with it myself :D Now I'm happy with it, only added that it always adds 5% to the progress bar no matter what - until the survey catches up with the bar itself.

@mattinannt

1. I did not add it to the widget yet as I'm not sure if this is too much "math" to run in the widget.
2. There are lots of errors logging in the console FYI

**Comment by mattinannt** [comment]
Sorry for the delay 😉
@moritzrengert Can you please also integrate the new progress into formbricks-js? 😊 And a few weeks back we added a `back` button but currently the progres isn't working with this feature. Can you please fix this? 🤗

**Comment by Dhruwang** [comment]
On it 🚀

**Comment by mattinannt** [comment]
@Dhruwang thanks a lot for making the changes, works great! 😊 We are currently working on the unified survey components package which will be merged tomorrow. I moved all your code for the progressbar to the new package into the new PR and will close this PR.

**Pull request closed without merging**
