### PR TITLE
fix: solve responsiveness issues in docs

### PR DESCRIPTION
**Pull request by thanmaisai**
## What does this PR do?

Fixes # (#1029) - Website alignment not scaling properly on large screens Fixed - Fixed
Fixes # (#1044) -  [BUG][FormTribe 🔥][50 Points] Image and page responsiveness in Docs section #1044 - Fixed

### Before: 
before_gitpod
Screenshot 2023-10-10 at 1 49 41 AM

### After:
after_gitpod
Screenshot 2023-10-10 at 1 52 08 AM

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
Hey @thanmaisai, as #1044 was already picked up by someone and we just merged it, we cannot assign it to you! And for the other issue, could you resolve the merge conflict and then I'll review it

**Comment by thanmaisai** [comment]
I have resolved the merge conflict. You can review it @ShubhamPalriwala !!!

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @thanmaisai, I see the following dimensions for images across the docs now:

image


This has happened since you removed the `max-w-3xl` limiting that we had for bigger screens so that image does not exceed like it is currently doing.

Please fix it, test it locally and then request a review again from me 🤞🏼

**Comment by ShubhamPalriwala** [comment]
@thanmaisai, converting this PR to draft, please convert it back to ready once you've made the changes and the PR is ready for review

**Comment by thanmaisai** [comment]
Sure, I will fix the changes by today.

**Comment by ShubhamPalriwala** [comment]
Hey @thanmaisai is this ready for review?

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey @thanmaisai, with your changes, it still looks messy in normal screens:
image


And with the margin bug fix already merged in main, the images should now be fine in bigger screens as itself! For your effort and findung the bug we'll award you +50 points but close this PR! Thanks

**Pull request closed without merging**
