### PR TITLE
feat: custom S3 endpoint to use third party storage services

### PR DESCRIPTION
**Pull request by sebiweise**
## What does this PR do?

I´ve added the available S3 environment vars to .env.example.
Also added the ability to define a custom S3 endpoint to use Third Party S3 compatible storage services like StorJ.

## How should this be tested?

Register for [StorJ](https://docs.storj.io/dcs/api/s3/s3-compatible-gateway) or another S3 storage provider
Define all environment vars:

- S3_ENDPOINT e.g. https://gateway.storjshare.io
- S3_REGION e.g. eu1
- S3_ACCESS_KEY
- S3_SECRET_KEY
- S3_BUCKET_NAME

## Checklist

- [x] Upload profile picture
- [x] Upload picture question image
- [x] Upload files in file upload question

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@sebiweise I would like to make changes to the PR but unfortunately I'm not able to push them. Did you allow maintainers to make changes?

**Comment by sebiweise** [comment]
> @sebiweise I would like to make changes to the PR but unfortunately I'm not able to push them. Did you allow maintainers to make changes?

I don´t really know how to do this, can you tell what I have to change so that you can push changes?

**Comment by mattinannt** [comment]
Screenshot 2024-02-27 at 09 53 00
When creating the pull request you can select this option. I'm not sure if you can also change this setting afterwards.
If it's enabled we should be able to see this in the info-bar on the right: https://github.blog/changelog/2023-02-10-see-when-a-pull-request-is-editable-by-maintainers/

**Comment by sebiweise** [comment]
> Screenshot 2024-02-27 at 09 53 00 When creating the pull request you can select this option. I'm not sure if you can also change this setting afterwards. If it's enabled we should be able to see this in the info-bar on the right:
> image
> 
> Update: you might be able to just check it: Screenshot 2024-02-27 at 09 54 48

Unfortunately I don´t have this options.
I tried to recreate the PR but even then I don´t have the option to enable maintainer edit.

**Comment by sebiweise** [comment]
I think thats  the problem: https://github.com/orgs/community/discussions/5634#discussion-3570791

**Comment by sebiweise** [comment]
Fixed it, you should be able to edit now.

**Pull request merged**
