### PR TITLE
feat: added dropoff visibility

### LINKED ISSUE #891: [FormTribe 🔥][500 Points] Display Drop-Offs better
### Welcome to the FormTribe

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

### Is your feature request related to a problem? Please describe.

Users want to know when respondents drop out of surveys. Currently, we are not displaying this info in an intuitive way.

### Describe the solution you'd like

Build a more intuitive way to understand drop offs

image

### How drop off is calculated

When a question remains unanswered we assume that the user dropped off during that question. For example when the page is loaded and a display is created but the first question did not get answered, the user dropped out on the first question. Similarly, when we have answers for Q1 and Q2 but not Q3, we assume the user dropped out on Q3.

Generally drop off is calculated like so: All who answered Q1/all who answered Q2. So if 100 people start the survey and 80 people answer Q2 we have 100/80. In the screenshot you can see this in practice: Even though on the 1st and 3rd question 20 people dropped out, in Q1 it's 20% drop-off while in Q3 it increased to 25% drop-off.

For the calculation of the drop off per question we only take into account the number of people who reached this specific questions. Since we don't track if a question was displayed, we 'reverse engineer' this KPI based on the assumption described above.

### Notes

We store the submission in the local storage. If a user comes back to continue filling out a survey on the same device and browser, the drop off is recalculated. With every new answer, the drop-off consequently moves to the back. If the survey gets completed, there is no more drop off 😃

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
Added dropoff visibility

Fixes #891 

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
Apologies for converting this to a draft PR, we currently have the https://github.com/formbricks/formbricks/pull/856 PR to be merged, and once that is tackled, we can jump right into this! Will ping you, once that's done! 😁

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Heyv @gupta-piyush19, thanks a lot for the implementation! While testing the functionality, I faced a bug if you add a logic jump to jump to end a survey when a response is submitted. This is being counted as a drop-off for that question but it shouldn't since the question was answered and the person moved forward.

To reproduce:
1. Create a survey with any question type
2. Now add a question again with any type and add a logic jump here that if the survey is submitted, we jump to the end of the survey
3. Now add another random question after this
4. Now publish the survey and fill it up.
5. Now go to the analysing drop offs and you'll see that for the question you had the logic jump, it is showing as a drop-off there (which is not as expected as the user submitted and moved forward).

https://www.loom.com/share/33c89539c87d405b89473a92ad5f7dac?sid=bc58de3d-28c6-48b2-8813-a209499efc3d

Attaching a Loom video for the same, Let me know if you have any further doubts

**Comment by jobenjada** [comment]
@gupta-piyush19 what is the status hree? :)

**Comment by gupta-piyush19** [comment]
Hey @jobenjada, working on the fix. will update it soon. Apologies for the delay.

**Comment by jobenjada** [comment]
converting to draft for us to know that you're still working on it :)

**Comment by gupta-piyush19** [comment]
Hey @ShubhamPalriwala! I've added the dropoff count logic in `apps/web/app/(app)/environments/[environmentId]/surveys/[surveyId]/(analysis)/summary/components/SummaryDropOffs.tsx`. 
Only the dropoff percentage remains in this issue. Could you please review the logic once?

**Comment by ShubhamPalriwala** [comment]
Hey, just tested it now:
Could you also build a logic for the case where the survey ends after a question is being submitted so then it's not a drop off since the survey ended?
Screenshot_2023-10-17-18-17-13_5760x1080

Also when I skipped a question and closed the survey after it, it showed the drop off for the skipped question even if I didn't view it
image

PS: All these tests are conducted on the template "Churn Survey" so should be reproducible

**Comment by gupta-piyush19** [comment]
Hey! Thanks for pointing this out. I've updated the code.

**Comment by ShubhamPalriwala** [comment]
Hey @gupta-piyush19, I've reworked the logic in the `SummaryDropoff.tsx` file, please take a look! Also review the other file changes once and see if they are necessary, I havn't touched the other files (the `pnpm format` has made some formatting changes though).

Test it thoroughly and see if any logic is going off somewhere

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey, can you make the following changes:

With 0 responses & displays I see NaN in the first question percentage:
image

For a question being optional, I do not see the drop-off:
image

The views also does not get updated if I skip through an optional question:
image

On submission of a response as well, the drop off table does not get updated:
image

PS: It works well for the required questions:
image

Please make the above changes and test it once

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey, thanks a lot for the changes! Made a minor fix and tested against the following cases and it worked well! 🚀 GG

image

**Comment by jobenjada** [comment]
hey boys! Love the collaboration on this one, looking pretty good :)

Made a minor UI tweak and had this issue at first:

image

It's not really an issue of your code though, because if we have a start we should also have a Display so this case should not exist.

We're looking into the Display issue right now, I will get this merged in the meanwhile :)

### Good work! 🤸

**Review by ShubhamPalriwala — APPROVED** [review]
LESSGOOOO🚀

**Pull request merged**
