### PR TITLE
docs: in-app & link multi language surveys

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## What does this PR do?

Fixes # (issue)

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
hey! fixed a few types and please do the following:

1. add a few more screenshots here. Many people first look at the docs to see if the product does what they hope it ill do. Your screenshots are a bit scarce and often show the full screen instead of the part of the UI which is important:

image

2. please style the example surveys in a cool way to showcase more what you can do with Formbricks:
image

Thanks! :))

**Review by mattinannt — COMMENTED** [review]
@ShubhamPalriwala thanks for the docs 😊💪 We get an issue with duplicated content and SEO if we publish the post twice in both link-surveys and in-app-surveys. Please add a new category `Additional Features` above Best Practices and include the Multi-Language here.

**Comment by ShubhamPalriwala** [comment]
Added screenshots + moved over both the pages, combined into 1, and moved to Additional Features. Please take a look now 🤞🏼

**Review by mattinannt — APPROVED** [review]
@ShubhamPalriwala thanks for making the changes :-) 💪

**Pull request merged**
