### PR TITLE
docs: Add Lost Pixel to open source friends

### PR DESCRIPTION
**Pull request by d-ivashchuk**
## What does this PR do?

Adds Lost Pixel OSS to the OSS friends list! Thanks a lot for this awesome initiative 🙌🏼

### CODE REVIEW

**Comment by jobenjada** [comment]
hey @d-ivashchuk - where is the OSS Friends page on your website? 🤓

**Comment by d-ivashchuk** [comment]
it was merged not so long ago so was waiting for the release 🙈 

https://lost-pixel.com/oss-friends - here it is!

**Comment by jobenjada** [comment]
@d-ivashchuk merging, welcome to the team! ;)

**Comment by d-ivashchuk** [comment]
@jobenjada let's goooo!

**Pull request merged**
