### PR TITLE
feat: Add colors to rating

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
Add colors to rating

Fixes 
https://github.com/formbricks/internal/issues/243

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by gupta-piyush19** [comment]
https://github.com/formbricks/formbricks/assets/56182734/c634954f-8ca2-47bc-b214-fe1924a45afe

**Review by Dhruwang — DISMISSED** [review]
Hey @gupta-piyush19 , looks so appealing with the new colors and works well too 🚀😊

Here are some of my UI suggestions
1. Lighten smiley colors

Screenshot 2024-06-21 at 5 17 36 PM

to 

Screenshot 2024-06-21 at 5 18 02 PM

2. For number as scale, right now selected option look like this with grey background

Screenshot 2024-06-21 at 5 54 06 PM

What if we change it to something like this ?

Screenshot 2024-06-21 at 5 40 13 PM

3. Right now if we hover on colored smiley (or in active state), its color changes to yellow, but with the new color theme with colors ranging from red to green, looks a bit odd. Can we add a ring around selected/hovered smiley 

Screenshot 2024-06-21 at 5 48 09 PM


Screenshot 2024-06-21 at 6 01 33 PM

As you can see here, last smiley is selected in this case and it has yellow color (similar to middle one)

4. Build error with templates 🤔

POINT 2 and 3 are just suggestions, i am too not sure about them. What do you think @jobenjada ?

**Comment by jobenjada** [comment]
Hey Piyush and Dhru

thanks a lot for your work so far.

1. Please add the space for the top color to the height. The idea is that the container does not feel like getting smaller by adding the color.

image

2. The orange isn't correct. Both for 7 and 10 points we should have two orange boxes.

image

3. These colors are way to bright, please use the same colors like for the numbers:

image

The hover color should could then be a bit more saturated to the Tailwind color 300 instead of 100.

4. Adding a ring on focus / active. Similar to how we do it with the numbers, we should indicate the focus / active states. I like Dhrus idea to add a ring with a small gap (on dhrus draft, it's to wide). But this requires to much hacking then let's go with the same look we have for numbers (changing the border color to something darker)

5. Add the smiley colors here to summary and response views:
image

image

**Review by jobenjada — APPROVED** [review]
The UI / UX looks good (last tweaks coming in as we speak).

Let's hand it over to @mattinannt for final code review

**Review by mattinannt — APPROVED** [review]

**Comment by ykburda** [comment]
Nice functions :)

**Pull request merged**
