### PR TITLE
feat: skeleton loading #3051

### LINKED ISSUE #3051: [FEATURE] Replace loading spinner with loading skeleton
### Is your feature request related to a problem? Please describe.

image

### Describe the solution you'd like

This doesn't use a skeleton loader but a loading spinner. 

Replace this with a loading skeleton. Research how we do it on other places and follow the same patterns like the Survey Editor or the Summary and Response pages.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SaiSawant1**
## What does this PR do?
This PR implements a new Feature as described in issue #3051.
This PR will replace the spinner loading with skeleton loading.
There are two Loading states on this page.
1)For the page that is rendered by loading.tsx.
2)Loading state while surveys are being fetched from the server.

Fixes #3051 

For the first loading state, I edited the loading.tsx to render the skeleton loader which is inspired by the loading state of people, and actions page.

For the second loading state I have created a new component in packages/ui/SurveysList/components called SurveyLoading.tsx which renders the skeleton loading while surveys are being fetched.

page loading before implementing the skeleton loading.
swappy-20240827_160934

page loading after implementing the skeleton loading.
swappy-20240827_161338

before implementing the skeleton for survey fetching.
swappy-20240827_161115

after implementing the skeleton for survey fetching.
swappy-20240827_162630

skeleton loading if the orientation is selected for grid.
swappy-20240827_162642

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by jobenjada — CHANGES_REQUESTED** [review]
see comment above

**Comment by SaiSawant1** [comment]
> see comment above

that error was caused because while the orientation was being fetched from the local storage, react already rendered the default loading state "grid". I changed that and instead of using a gird skeleton as a default render, the skeleton will only load after orientation is fetched from local storage. However, now there is a split second when no skeleton is rendered so to fix that instead of using useEffect I used useLayoutEffect.
so this is when I use useEffect 
https://github.com/user-attachments/assets/0d0cdcb7-0816-45a8-bede-69c36eb9bfc2

and this is when i use useLayoutEffect

https://github.com/user-attachments/assets/5b762a78-99dc-48d3-99b5-95a4aaeefdb3

**Comment by jobenjada** [comment]
Hey!

It kinda defies the purpose of the loading skeleton because for most of the loading time we see an empty screen.

We have the Card view as the default view so lets just show the card loader. 

Please remove the code for the skeleton for the list view and make sure to show the skeleton as soon as the page reloads, thats purpose right :) 

Thanks a lot! Happy to merge this asap 🚀

**Review by jobenjada — APPROVED** [review]
thanks!

**Pull request merged**
