### PR TITLE
fix: fixes duplicate named file uploads

### PR DESCRIPTION
**Pull request by pandeymangg**
## What does this PR do?

Fixes # (issue)

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — COMMENTED** [review]
@pandeymangg thanks a lot for the fix 😊🔥 Looks great.
But it seems like we have a few duplications of the complex logic for transforming the filenames back and forth. Can we also put this logic in separate functions, e.g. in `packages/lib/storage/util.ts`

**Review by mattinannt — APPROVED** [review]
@pandeymangg thanks a lot for making the changes; looks great! :-)

**Comment by mattinannt** [comment]
@pandeymangg I just thought about one edge case, tested it and unfortunately is not working as expected. The file names are not working correctly for files uploaded before the fix. They have two file extensions:
Screenshot 2024-01-11 at 19 44 48

Can you please fix this issue?

**Comment by pandeymangg** [comment]
> @pandeymangg I just thought about one edge case, tested it and unfortunately is not working as expected. The file names are not working correctly for files uploaded before the fix. They have two file extensions: Screenshot 2024-01-11 at 19 44 48
> 
> Can you please fix this issue?

done 👍

**Review by mattinannt — APPROVED** [review]
@pandeymangg thank you for fixing the backwards compatibility issues. ready for merge 💪

**Pull request merged**
