### PR TITLE
fix: #1255 Update SettingsNavbar.tsx

### LINKED ISSUE #1255: [BUG] side panel in the app.formbricks -> setting is not scrollable.
### Issue Summary

app.formbricks setting side panel is not scrollable 

### Steps to Reproduce

1. Go to: https://app.formbricks.com/
2. Clicked on: settings
3. minimize the window 50% vertically 

### Expected behavior

.

### Other information

.

### Screenshots

https://github.com/formbricks/formbricks/assets/84387676/8bd85778-a65b-4d1a-93fd-6c0124b5c555

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: chrome, edge, firefox
```

### PR DESCRIPTION
**Pull request by priyanshu2k3**
fix #1255 Update SettingsNavbar.tsx

## What does this PR do?

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by priyanshu2k3** [comment]
fix #1255 Update SettingsNavbar.tsx

**Comment by jobenjada** [comment]
Reopened PR to get it merged

**Comment by jobenjada** [comment]
image

@priyanshu2k3 this doesnt solve it, the compliance links are still not scrollable :(

**Comment by jobenjada** [comment]
No response from contributor, not really important enough to keep open.

**Pull request closed without merging**
