### PR TITLE
docs: Added Single Use Links Section in Docs.

### LINKED ISSUE #971: [DOCS][FormTribe 🔥][200 Points] Docs for Single Use Links
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Is your feature request related to a problem? Please describe.

We have shipped single use links for link surveys to make sure that each person can only submit a survey once.

As of now, we're lacking documentation for this feature.

### Describe the solution you'd like

1. Write concise but complete documentation of the Single Use Links feature incl. Screenshots.
2. Add it to the Link Survey chapter in our Docs

image

Notes:
- The UI explains the feature quite well
- Make sure to explain how URL encryption works via the corresponding env variable:
image

- Currentl, the suID sits next to the completed tag:
image

We are currently reworking our response cards and it will move into the metadata section which opens on hovering over the Avatar:
image

Additionally, we're updating the embedding modal for Single Use Links: https://github.com/formbricks/formbricks/pull/952

This is why you'll need to update 2 screenshots, once the corresponding PRs are merged :)

But 95% of the work you can do already, so we decided to open the issue today.

### Thanks!

### PR DESCRIPTION
**Pull request by aman44444**
## What does this PR do?

Added a section About Single Use Links in Docs This section provide all information about Single Use Links.

Fixes #971 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [X] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by aman44444** [comment]
@jobenjada  check this out i know this pr needs lots of changes please markdown all changes and also tell me where to use screenshots.

**Comment by jobenjada** [comment]
hey @aman44444 thanks a lot for your draft PR.

Your docs page did not contain images but a lot of information which was incorrect or irrelevant. I didn't really get the impression that you really tried writing a good docs page so I decided to write it myself instead of helping you get it shipped.

You'll be awarded 50% of the points for your work so far ✨

**Comment by aman44444** [comment]
@jobenjada  To be honest, I did a poor job, and I apologize for that. I am working on improving myself.

**Comment by jobenjada** [comment]
Love the insight! :D

**Pull request merged**
