### PR TITLE
feat: Automatic team assignment + skip onboarding

### PR DESCRIPTION
**Pull request by jonas-hoebenreich**
## What does this PR do?

This PR introduces the new environment variables DEFAULT_TEAM & SKIP_ONBOARDING. When these are set, new users are automatically added to the default team and skip onboarding. This prevents creating countless useless teams, environments and products when self hosting.

[scrnli_20_10_2023_13-38-26.webm](https://github.com/formbricks/formbricks/assets/64426524/f4cb81c5-2f58-444e-8db7-afbb2856dec5)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- DEFAULT_TEAM & SKIP_ONBOARDING and create a new user using email & social auth 

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@jonas-hoebenreich Thank you for the PR :-) I'm getting the main idea behind the functionality but I think we can solve this better. The current flow would be to create a Formbricks instance with `DEFAULT_TEAM` not set, creating an account with a team, then trying to find the team id and setting the default team in the environment variables + skip onboarding and restarting the Formbricks server.

This seems too complicated and I would prefer an approach where we set the environment variables once; before starting Formbricks for the first time and then maybe the first user will become owner of this team and the others join. What do you think about this approach?
Also you chose the new members to be of role `viewer` which means they cannot perform any action (create survey, etc.) on their own. Was this intentional? Maybe to have a more generic approach we should also have an optional env setting for the `DEFAULT_TEAM_ROLE` (default admin).
In general, we try to have as few env variables as possible. But I think the features you proposed make sense also when viewed independently. So maybe we can have these environment variables (to stay in the current env naming schema):
```
ONBOARDING_DISABLED=1

DEFAULT_TEAM_ENABLED=1
DEFAULT_TEAM_ROLE=viewer
```

I'm not really sure what the best approach for the automatic team creation would be, but we can figure this out in the next step if we agree on a general functionality :-)

**Comment by jonas-hoebenreich** [comment]
Hi @mattinannt,
I do get your point. What do you think about this solution: you can set it up with any team id you want (including for teams that do not exist yet and will be automatically created). This solution has the advantage that it allows to change the default team later. Imagine this scenario: a company sets up Formbricks and onboards all relevant users to the team "Production". After all relevant users signed up, the default team id is changed to "Playground" so all users coming from different departments can still explore the tool but not access any production data.
This would be the new variables:

```
ONBOARDING_DISABLED=1

#enter any team id (if team does not exist yet it will be created)
DEFAULT_TEAM=aaa
DEFAULT_TEAM_ROLE=viewer
```

**Comment by mattinannt** [comment]
@jonas-hoebenreich yes, the case is valid. Let me think about it a bit.
You mixed up teamId and team name sometimes. We need to go with the team Id (cuid, e.g. `cjld2cjxh0000qzrmn831i7rn`) instead of the team name as only the id is unique.

```
ONBOARDING_DISABLED=1

# insert an existing team id or generate a new one at https://www.getuniqueid.com/cuid
DEFAULT_TEAM_ID=cjld2cjxh0000qzrmn831i7rn
DEFAULT_TEAM_ROLE=viewer
```
Unfortunately there isn't a good an easy way to generate a cuid in the terminal so people need to go with an online tool.
Also currently there is no easy way in Formbricks to see the teamId, but I think that's not too hard to add in a visual appealing way.

**Comment by jonas-hoebenreich** [comment]
Hi @mattinannt,

I've addressed your point by renaming the variable for clarity. I've also introduced automatic team creation and default user roles (first users will always be owners).
In my view, it's not a problem that the default team ID can't be generated in the terminal because a) any string is considered a valid ID in the current Formbricks implementation, and b) we provide an example ID in .example.env for users to use.

I've added the team ID to the team's settings page footer and to product and profile settings for consistency. This can be also useful for tasks like customer support or debugging.

image

Your feedback is always appreciated, and I hope these enhancements align with your ideas.

**Review by mattinannt — APPROVED** [review]

**Pull request merged**
