### PR TITLE
Fixed : Password validation

### LINKED ISSUE #410: No minimum password length on signup page
### Issue Summary

On signup page, currently there is no minimum password length enforced

### Steps to Reproduce

1. Go to signup page
2. Enter username and email
3. Enter a password 

Password of any length will be considered valid and user will be created in database

### Expected behavior

Password below a certain length (say 8) should not be accepted

#### Screenshots

https://github.com/formbricks/formbricks/assets/67850763/d3777c16-4354-499b-a18b-4b26a8c5fe9b

#### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [x] self-hosted Formbricks, version/commit: [please provide]

### LINKED ISSUE #411: User already exist error shows even if no such email exist in DB
### Issue Summary

User already exist error pops up while creating a new account even with an email not existing in database

### Steps to Reproduce

1. Fill credentials on signup page
2. Press submit button (continue with email)
3. User get redirected to email verification page but in between there pops an error of "User already exist"

#### Screenshots

https://github.com/formbricks/formbricks/assets/67850763/6cdb3ef9-2da2-4500-a286-b5aa788409e2

**Pause on sec 4**

#### Environment

- [x] Formbricks Cloud (app.formbricks.com)
- [x] self-hosted Formbricks, version/commit: [please provide]

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?
# Made 2 changes
## Change 1
Added minimum length password validation error in signup page

https://github.com/formbricks/formbricks/assets/67850763/e6f0a9d9-c2c0-49d5-b457-990ed2edfd9c
## Change 2
Solved user already exist error even while using a new email:
Screenshot from 2023-06-19 23-59-13
Screenshot from 2023-06-20 00-01-52

When a user clicks on submit button after filling credentials, `onClick` event is triggered and as this button is inside of form element, its default behavior will be to run `onSubmit` function of that form and hence it will run `handleSubmit` function and then it will again execute` formRef.current.requestSubmit() ` which will again call the function `handleSubmit` and hence 2 request will be sent to server
First request will result into creation of user into the database and second one will throw user already exist error.

So just added a `e.preventDefault()` to avoid the default behavior of button onClick 

Fixes #410 
Fixes #411 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## Checklist

- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @Dhruwang 

Thanks a lot for spotting these issues and fixing them 👏 

We didn't tackle password validation yet, but it definitely needs to be done. However, the UX you've built isn't really working. Have a look at how Cal.com does it:

grafik

You can find the code in their repository, they're building with the same tech stack: 
https://github.com/calcom/cal.com

Please rebuild the UX they have for password validation 🙏 

Thanks a lot!
Johannes

**Comment by Dhruwang** [comment]
Yes sure !

**Comment by Dhruwang** [comment]
https://github.com/formbricks/formbricks/assets/67850763/0e90215e-5d93-466d-bde0-5ee4b5adfe01

@jobenjada what do you think about this ?

**Comment by jobenjada** [comment]
Hey! Here is what GPT suggest in terms of refactoring:

`import { CheckIcon, XMarkIcon } from '@heroicons/react/24/solid';
import React, { useState, useEffect } from 'react';

interface Validation {
  label: string;
  state: boolean | null;
}

const PASSWORD_REGEX = {
  UPPER_AND_LOWER: /[A-Z]/ && /[a-z]/,
  NUMBER: /\d/
};

export default function IsPasswordValid({ password, submitted, setIsValid }:
  { password: string | null, submitted: boolean, setIsValid: (isValid: boolean) => void }) {

  const [validations, setValidations] = useState<Validation[]>([
    { label: 'Mix of uppercase and lowercase', state: null },
    { label: 'Minimum 8 characters long', state: null },
    { label: 'Contain at least 1 number', state: null },
  ]);

  useEffect(() => {
    resetValidations(submitted ? false : null);
    if (password) {
      checkValidation(0, PASSWORD_REGEX.UPPER_AND_LOWER.test(password));
      checkValidation(1, password.length >= 8);
      checkValidation(2, PASSWORD_REGEX.NUMBER.test(password));
    }
    setIsValid(validations.every((validation) => validation.state === true));
  }, [password, validations]);

  const resetValidations = (state: boolean | null) => {
    setValidations((prevValidations) =>
      prevValidations.map((validation) => ({ ...validation, state }))
    );
  };

  const checkValidation = (index: number, state: boolean) => {
    setValidations((prevValidations) => {
      const updatedValidations = [...prevValidations];
      updatedValidations[index].state = state;
      return updatedValidations;
    });
  };

  const ValidationIcon: React.FC<{ state: boolean | null }> = ({ state }) => {
    if (state === null) {
      return <span className="w-5 h-5 flex items-center justify-center"><i className="w-2 h-2 rounded-full bg-slate-700 inline-block"></i></span>;
    } else if (state) {
      return <CheckIcon className="h-5 w-5" />;
    } else {
      return <XMarkIcon className="h-5 w-5" />;
    }
  };

 
`

**Comment by jobenjada** [comment]
Looks very good, thanks!

@mattinannt please do a final code review :)

**Review by mattinannt — APPROVED** [review]
@Dhruwang Thanks for this feature PR 💪🚀
During my tests I noticed that the useEffect() hook inside IsPasswordValid was updating `validations` as well as got triggered by `validations` what led to infinite update loops and also prevented the signup redirect.
I solved this issue and now we are ready to merge. 😊

**Pull request merged**
