### PR TITLE
fix: adding loader for Delete and Save buttons

### LINKED ISSUE #1338: [BUG][FormTribe 🔥][100 Points] Delete and Save Buttons Remain Clickable After Click on Delete or Save button
### Issue Summary

Upon clicking the "Delete" button in the DeleteDialog component, the button does not become disabled as expected. Consequently, users can click the "Delete" button multiple times, leading to potential issues. The same behavior is observed with the "Save" button. 

Multiple time click create error also 

image

### Steps to Reproduce

1. Open the DeleteDialog component.
2. Click the "Delete" button.
3. Observe that the button does not become disabled.
4. Attempt to click the "Delete" button again. Note that it remains clickable.
5. Repeat the above steps for the "Save" button.
image

https://www.loom.com/share/9b9980e2125b443589acd6c0a11f55e4?sid=71ec4b52-033b-4674-bfff-8a20330f7437

### Expected behavior

After clicking the "Delete" button, it should be disabled to prevent multiple consecutive clicks until the action is completed.
The "Save" button should exhibit the same behavior, becoming disabled temporarily after being clicked to avoid multiple rapid clicks.

https://www.loom.com/share/c4973ca8c83a4f289e8b63b0a8c9dad2?sid=aa956af4-9871-4e10-bd16-370ef253f6d9

### Other information

_No response_

### Screenshots

image

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: v18.18.0
- npm: 9.8.1
```

### PR DESCRIPTION
**Pull request by shyamraghu**
## What does this PR do?

This PR introduces a loader for the "Delete" and "Save" buttons in the DeleteDialog component. The loader provides visual feedback to users while the delete or save action is in progress.

Fixes #1338

Loom Video: https://www.loom.com/share/527e9519dc144b0d9ee425fa03b06d17?sid=c8fe270d-e1fd-40a6-ad71-0b51d62da012

## Type of change

- [x] Enhancement (small improvements)

## How should this be tested?

- Open the DeleteDialog component.
- Click the "Delete" button.
- Verify that the "Deleting..." loader is displayed.
- Ensure that the "Delete" button remains clickable during the loading state.
- Repeat the above steps for the "Save" button.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [] Ran `pnpm build`
- [x] Checked for warnings; there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by shyamraghu** [comment]
@jobenjada check if something required i removed the disabled because the value of disabled was null. And I ran build there is no issue

**Comment by Dhruwang** [comment]
Hey @shyamraghu ,thank you for the PR 😊, but we need `disabled` to disable the delete button when we try to delete user account or team 😊

**Comment by shyamraghu** [comment]
> Hey @shyamraghu ,thank you for the PR 😊, but we need `disabled` to disable the delete button when we try to delete user account or team 😊

I think you should read this conversation #1344

**Comment by jobenjada** [comment]
@shyamraghu thanks for following up. Dhru is right, we need the disable functionality generally in the modal, I asked you to use a Loading State when it is loading, not to remove the disabled state completely.

A Disabled button and a button in Loading state serve two different purposes. In some cases, we want to disable the button (like Dhru refered to) and in other cases we want to set the button to Loading state. The Modal needs to support both states but in your tweak, we only need to apply loading states to the buttons.

Please update this PR accordingly 🙏

**Comment by shyamraghu** [comment]
> @shyamraghu thanks for following up. Dhru is right, we need the disable functionality generally in the modal, I asked you to use a Loading State when it is loading, not to remove the disabled state completely.
> 
> A Disabled button and a button in Loading state serve two different purposes. In some cases, we want to disable the button (like Dhru refered to) and in other cases we want to set the button to Loading state. The Modal needs to support both states but in your tweak, we only need to apply loading states to the buttons.
> 
> Please update this PR accordingly 🙏

Ok 🙏

**Comment by shyamraghu** [comment]
@jobenjada Done 👍

**Comment by jobenjada** [comment]
Thanks, added to merge queue :)

**Pull request merged**
