### PR TITLE
feat: Video upload

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Fixes [1924](https://linear.app/formbricks/issue/FOR-1924/add-video-to-each-question)

https://github.com/formbricks/formbricks/assets/67850763/6a845780-1181-47de-8389-96d6196d85ad

Screenshot 2024-03-28 at 1 28 15 PM

The iframe here serves to showcase the specified video, but unfortunately iframes does not throw an error when there is no video present at given url, it shows the default fallback screen provided by respective providers (youtube, vimeo or loom), and hence wasnt able to find a good solution for this

## How should this be tested?

Click on photo icon next to headline
Click on Video
Paste a youtube, vimeo or loom link

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by pandeymangg** [comment]
Hey @Dhruwang Thanks for the feature! Looks and works really nicely 😊 
I just found two bugs in the Thank you card and the Welcome card, please have a look at these 🙏 

https://github.com/formbricks/formbricks/assets/54475686/e295adad-58f5-4c25-86ce-80f49d4ec792

**Comment by jobenjada** [comment]
@pandeymangg do you think this is an issue?

image

Also, please always merge main before testing, the Matrix question was still using the old image (updated it):

image

------

@Dhruwang here is my feedback for the feature:

image

image


- For videos it has to be 16 by 9 aspect ratio
- Pls round the corners, ideally using the custom value from styling  (you need to put it in a div and style the div)

------

The scale up button doesnt work:
image

Instead, it should link out to the actual video on the hosting platform. Make sure to also replace the icon with a matching icon from the lucide set

-------

Reduce controls:

I know that YouTube has various setting to control the UX of the embedded video. We want to keep it as clean and easy as possible with as little distractions as possible. Here is a starting point for your research

```
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/jfKfPfyJRdk?si=gAA3YRGN8k-R8tTW&amp;controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
```

Ideally, it just has a start and stop button, allows skipping ahead and maybe switching ob subtitles. As little outbound links as possible, no video suggestions at the end, etc

Please research if Vimeo and Loom have something similar and implemented. Especially the Loom embed feels overwhelming.

--------

pls have a look at the border and why it's not covering the rounded corners:

image

---------

The rest looks good, thanks! :))

**Comment by Dhruwang** [comment]
About Reducing controls, it can be achieved by passing params to video urls
For youtube it pretty straight forward, just add ?controls=0 , and we are good to go. We also have same params mechanism in vimeo but in case of vimeo it hides all the controls, so viewer cant even play/pause the video. So I have added params to disable individual components and loom too provide similar params. Have added all the possible ones
Here are the links for vimeo and loom params docs
Vimeo: https://developer.vimeo.com/player/sdk/embed
Loom : https://support.loom.com/hc/en-us/articles/360002208317-How-to-embed-your-video-into-a-webpage


About refactoring using GPT,
Extract Utility Functions : Utility functions are already extracted in lib/utils, and it does not make sense to extract functions like toggleYoutubePrivacyMode , as they deal with states or we have to pass all the setter functions as params too
Custom Hook for State Logic : We dont use that pattern where we create hooks for state logic
Use useCallback for Event Handlers: Event handling functions here are simple event handlers attached to buttons within this component. They aren’t passed down to other components, there wont be any benefit in memoizing them with useCallback
Didn’t find anything useful there, i already refactored it before review :blush:

Also fixed all the mentioned tweaks !

**Review by jobenjada — APPROVED** [review]
looks great! last tweaks from Dhru incoming and then @pandeymangg will merge it 🤓

**Review by pandeymangg — APPROVED** [review]
LGTM!

**Pull request merged**
