### PR TITLE
feat: Back_to_Top_button_added

### LINKED ISSUE #3142: [FEATURE] 'Back to Top' button on Summary screen
### Is your feature request related to a problem? Please describe.

Scrolling through data can be sped up a bit by adding a floating "Back to Top" button on the summary page. This way, if I am viewing one of the questions near the end of my survey and decide I need to add a filter, I can very quickly get back to the top of the page without affecting any other filters I might have applied.

### Describe the solution you'd like

Floating 'Back to Top' button on Summary page

### Describe alternatives you've considered

A more complicated alternative could be to add a few floating buttons that not only allow you to scroll back to the top quickly, but also apply filters directly from the location you are on the page.

Although that would be nice, I think at least a scroll to top button is something that could be useful for everyone.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alok14598**
What does this PR do?

This Issue resolved the issue stated as "[FEATURE] 'Back to Top' button on Summary screen", the solution added contains a floating Two buttons, One is open Filter in case user want to add filter and another button slides to the top.

Fixes #3142

 How should this be tested?
Please Fill the Summary Page so that it become scrollable i.e the Page should have Enough Content to make it Scroll and view the Top Button

### Required

- Filled out the "How to test" section in this PR
-Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- Self-reviewed my own code
-Checked for warnings, there are none
-  Removed all `console.logs
-My changes don't cause any responsiveness issues

## Summary by CodeRabbit

- **New Features**
	- Enhanced user interface on the Summary Page with improved navigation and filtering options.
	- Added buttons for toggling filter visibility and scrolling back to the top of the page.
	- Introduced new state management for better user interaction based on scroll position.

- **Chores**
	- Updated Tailwind CSS configuration to include new height and spacing properties for improved design flexibility.

### CODE REVIEW

**Comment by jobenjada** [comment]
hey Alok! This seems like an overkill to add a simple scroll to top button. Please cut down on the lines of code. And why are you working on filters?

**Comment by alok14598** [comment]
HI @jobenjada In the Issue description, Under "Describe alternatives you've considered" found the line as "also apply filters directly from the location you are on the page." , that's the reason behind working on filters.

The Top button will only display when the page is Scrollable, I realised there are plenty of lines, 

Please Suggest should I have Single Top Button or the changes I have Done before ???

**Comment by jobenjada** [comment]
hey! Please:

- create a reusable "Scroll to top button" component in the `packages/ui`
- import it in the summary
- remove everything filter related

Run your code by GPT to refactor it following common code best practices.

Thanks!

**Comment by jobenjada** [comment]
@alok14598 are you still working on this?

**Comment by alok14598** [comment]
HI @jobenjada got little busy during weekend, I am working on the issue

**Comment by jobenjada** [comment]
@alok14598 sweet, i've added some points to it for our current hackathon :)

**Comment by alok14598** [comment]
Created a new PR as 3292

**Pull request closed without merging**
