### PR TITLE
fix: Card overlapping issue #1001

### PR DESCRIPTION
**Pull request by itzabhinavarya**
## What does this PR do?

This PR fixes the overlapping of the "categories" tages on the website, When we switched for smaller screen.

Fixes # (issue : #1001)
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

What i did ?

1. Created a repo "customStyles"
2. Created a css module BestPracticeNavigation.module.css
3. Imported into BestPracticeNavigation.tsx
4. Write some responsive code into my css style which resolve the issue (#1001)
5. Done with the changes.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @itzabhinavarya thanks! 

This is quite an unconventional solution for a Tailwind based repo. Please find a Tailwind-only solution to fix this :)

Thanks!!

**Comment by itzabhinavarya** [comment]
Ok thanks for guidence, Please assign this task to me. I am fixing this with tailwind based approach only.

**Comment by jobenjada** [comment]
@itzabhinavarya you pushed your env file ;) 

I dont think its needed to introduce a new break point, please work with the ones we have as they are commonly accepted and sufficient

**Comment by itzabhinavarya** [comment]
@jobenjada  Ok Sir, Now check please.

**Comment by itzabhinavarya** [comment]
Hello Sir,

Greetings of the day.

I have created a new commit without adding a new breakpoint as you said,
Please review the code.

Issue no : #1005

Thanks & Regards
Abhinav Arya
Github : github.com/itzabhinavarya

**Comment by jobenjada** [comment]
@itzabhinavarya you did not really fix it, you just decreased the text of the tag but for all view ports (so it was tiny even on large desktops)

Please have a look at how I solved it 🤓 

I'll award you +50 points instead of +100 points for trying 🙏

**Comment by itzabhinavarya** [comment]
Oo i see, I have checked your changes, Sir you are really amazing. I am learning so forgive my mistakes.
The approach you followed is awesome. I didn't think about to change the box width small to medium.
BTW learned a lot from you. 
Thank you so much Sir @jobenjada . Respect for you.

**Pull request merged**
