### PR TITLE
feat: Improve Preview Full Screen Modal Animation

### PR DESCRIPTION
**Pull request by yatharth1706**
## What does this PR do?
Made the animation look more natural when expanding the preview modal or shrinking it

Fixes # (issue)

https://github.com/formbricks/formbricks/assets/32243289/ad02406f-55e1-4e96-a57d-695d91bab682

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
hey mate! Love to see you come back and get the job done 💪 :D 

we'll look into it when the 2.0 is out! :)

**Comment by yatharth1706** [comment]
> hey mate! Love to see you come back and get the job done 💪 :D
> 
> we'll look into it when the 2.0 is out! :)

Sure @jobenjada no worries. I was just learning more about animations and was tinkering with framer motion a lot in past few days. And i thought lets just give it a try again to improve the preview full screen animation. And hence i submitted a PR again.

**Comment by pandeymangg** [comment]
Hey! @yatharth1706 Thanks for opening the PR, could you please look into this? The preview survey is not visible in the full screen preview.

https://github.com/formbricks/formbricks/assets/54475686/c313acbb-1c40-4d69-9a08-b3ed02397a4b

**Comment by yatharth1706** [comment]
Yeah Sure, I will take a look at that in some time. Thanks

**Comment by yatharth1706** [comment]
Keeping this in draft version for now. Some strange behaviour happening with the modals inside preview screen when its maximized. Those are getting invisible. I will check that in some time.

**Comment by yatharth1706** [comment]
@pandeymangg i was checking the code. Inside preview modal, survey modal is getting dynamically added in the runtime. I believe that is causing some strange behaviour. Because for adding the animation i am using shared layouts of framer motion and in that i have to create the preview modal twice. One is the existing and second is the one which covers the whole screen when maximized.

So because of having two components and as our survey modal is dynamically added at the runtime, i believe that is causing some strange issues. Do you have any idea on how we can fix that and show the survey modal in the maximized component as well ?

**Pull request closed without merging**
