### PR TITLE
feat: Expanded the options of time periods in filters

### LINKED ISSUE #4218: [FEATURE] Expand the options for time periods in filters
### Is your feature request related to a problem? Please describe.

Currently, we only offer these
image

### Describe the solution you'd like

Augment them to add the following:

This month (note: not 30 days, actual month)
Last month (note: not 30 days, actual month)
This quarter
Last quarter
Last 6 months 
This year
Last year

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by khAja13**
## What does this PR do?

Fixes #4218 

## How should this be tested?

- Checkout the responses of a particular survey, you will have all the time periods to filter the responses. Based on the selected time period, the responses get filtered.
 
image

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced date filtering options, including "This Month," "Last Month," "Last 6 Months," "This Quarter," "Last Quarter," "This Year," and "Last Year."
	- Updated dropdown menu for selecting filters with new predefined date ranges.

- **Improvements**
	- Added new localization entries for better user engagement and clarity regarding survey data timeframes in English, German, and Portuguese.
	- Improved focus management in the EmbedView component for better user experience.

### CODE REVIEW

**Review by jobenjada — APPROVED** [review]
works well, good job! :)

we're looking into how to automate the translation of the labels for the other languages and then merge it

**Comment by khAja13** [comment]
Thank you @jobenjada

**Comment by jobenjada** [comment]
@gupta-piyush19 UI looks good to me (code as well) - pls review 🚀

**Review by gupta-piyush19 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
