### PR TITLE
Adds back button label adjust

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Now user can set a custom label for **Backbutton**

Screenshot from 2023-08-31 13-42-18

Fixes [1188](https://linear.app/formbricks/issue/FOR-1188/adjust-back-button-label)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Open any question card
Click on advance settings
Edit Back button label

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @Dhruwang thanks a ton for the quick turnaround!

You considered some UX things that weren't defined in the ticket - really like that!! You are thinking along form a user perspective more and more 💪💪💪 

Here is my feedback:

**NPS Question Type & CTA Question Type**
The UI is inconsistent: Label is Back instead of "Back" Button Label and the input fields are not next to each other:
image

**Rating Question Type**
Its not in the Advanced Settings, pls add it there
image

Other than that, works great! :)

**Comment by Dhruwang** [comment]
@jobenjada Made requested changes 😊

**Comment by jobenjada** [comment]
Thanks @Dhruwang - looks good :)

@mattinannt - ready 2 merge

**Review by jobenjada — APPROVED** [review]
👍

**Review by mattinannt — APPROVED** [review]
@Dhruwang thanks a lot for this feature PR 😊💪🙏
I will merge this into main now :-)

**Comment by ykburda** [comment]
Hi, Is there any reason that if we change back button title it is affecting  all questions? Kind of trying to make all same title.

**Comment by mattinannt** [comment]
@ykburda Good point. I will discuss this with the team. We previously made the choice because it was easy to implement and gave the back-button-label-setting the same the place in the app as the next-button-label-setting

**Comment by ykburda** [comment]
Matti, It is now changing all back buttons if we change at any question.  It is not same as next button. I think it should be.

**Pull request merged**
