### PR TITLE
feat: rework-the-loading.tsx-on-people-page

### PR DESCRIPTION
**Pull request by lovishduggal**
## What does this PR do?
The PR implemented loading.tsx to match the UI of the /people page.

Fixes: #2619

Demo: 

https://github.com/formbricks/formbricks/assets/104680808/a79a7210-7c09-419e-aa23-d11d3f2a3bec

### CODE REVIEW

**Comment by lovishduggal** [comment]
Hey @jobenjada, could you please review the PR? Thanks!

**Review by jobenjada — APPROVED** [review]
great work! Added a mock nav and fixed the segment empty state

**Pull request merged**
