### PR TITLE
fix: Refactor theme switcher from dropdown to toggle

### LINKED ISSUE #1267: [BUG][FormTribe 🔥][50 Points] Request for Improved User Experience: Simplify Theme Selection with Toggle Button
### Issue Summary

Please bring attention to an issue in application's user experience that I believe could greatly benefit from an improvement. Currently, users are presented with a dropdown menu to select their preferred theme, which includes options for "Light," "Dark," and "System (Default)" themes. While providing theme customization is essential, we believe there is room for enhancement in how we offer this choice.

Reasons for the Change:

1. Streamlined User Experience: A toggle button is an intuitive way for users to switch between light and dark themes quickly without navigating through a dropdown menu. It simplifies the process, making it more user-friendly.

2. Aesthetic Consistency: Toggle buttons have become a standard design element in many modern applications and websites. Transitioning to a toggle button will provide a more consistent and visually appealing user interface.

3. Improved Accessibility: A toggle button is more accessible for all users, including those with disabilities. It offers a clear and straightforward method of theme selection.

4. Alignment with User Preferences: Users often prefer having only the option to choose between light and dark themes, as "System (Default)" may not always align with their preferences. Providing a toggle for light and dark themes respects user choice.

I would like to fix this. Please assign me. #Hacktoberfest

Screenshot 2023-10-17 194721

### Steps to Reproduce

1. Go to formbricks.com

### Expected behavior

I propose simplifying the theme selection process by replacing the existing dropdown menu with a toggle button for "Light" and "Dark" themes. This adjustment will not only make the user experience more intuitive but also align with contemporary design trends and user expectations.

Benefits:

1. Enhanced User Experience: Users will find it easier to customize their experience with our application.
2. Improved User Satisfaction: By accommodating user preferences and expectations, we can enhance overall user satisfaction.
3. Consistency and Accessibility: The updated design will adhere to best practices and make our application more accessible to a wider audience.

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Chrome
```

### PR DESCRIPTION
**Pull request by moheyt**
## What does this PR do?

Introduce a user interface enhancement that changes the theme switcher from a dropdown to a toggle switch.The previous implementation used a dropdown for selecting the theme, and this update improves the user experience.

Changes:
1. Replaced the theme selector dropdown with a toggle switch.
2. Modified the functionality to control the theme using the toggle switch.
3. The theme is now set as the system default by default, providing a seamless transition for users who prefer system-defined themes.
4. Ensured that the toggle switch correctly reflects the current theme state.

Fixes #1267

https://github.com/formbricks/formbricks/assets/85775976/ee5a14a3-50e0-46e9-b8dc-31bce8e6f514

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @moheyt, thanks for the changes! I tested it locally and here are my 2 suggestions:
 - The theme selector now does not have a selector cursor when hovered over it so can you please add that!
 - I would prefer the default isDarkMode to be true because: the small amount of time before which the useEffect runs, a person with dark theme would not the like the flash of a light mode webpage. And for the other case ie a light mode person would not really be flashed if its dark mode for the inital few milliseconds since it won't cause a flash!

Rest all looks good to me, post the above changes, we can proceed with the merge 🚀

**Comment by moheyt** [comment]
sure @ShubhamPalriwala 🫡

**Comment by ShubhamPalriwala** [comment]
Hey @moheyt, any updates on this? Would like to merge and get this going!

**Comment by moheyt** [comment]
@ShubhamPalriwala hey bro just wait 5min.

**Review by ShubhamPalriwala — APPROVED** [review]
Thanks for the changes @moheyt LGTM 🚀

**Pull request merged**
