### PR TITLE
feat: custom S3 endpoint to use third party storage services

### PR DESCRIPTION
**Pull request by sebiweise**
## What does this PR do?

I´ve added the available S3 environment vars to .env.example.
Also added the ability to define a custom S3 endpoint to use Third Party S3 compatible storage services like StorJ.

## How should this be tested?

Register for [StorJ](https://docs.storj.io/dcs/api/s3/s3-compatible-gateway) or another S3 storage provider
Define all environment vars:

- S3_ENDPOINT e.g. https://gateway.storjshare.io
- S3_REGION e.g. eu1
- S3_ACCESS_KEY
- S3_SECRET_KEY
- S3_BUCKET_NAME

## Checklist

- [x] Upload profile picture
- [x] Upload picture question image
- [x] Upload files in file upload question

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — APPROVED** [review]
@sebiweise thanks a lot for the PR 😊💪🚀
Please sign the CLA and we are ready to go forward with the merge 😊

**Comment by sebiweise** [comment]
@mattinannt Is there anything required so that my pr gets merged?

**Comment by sebiweise** [comment]
@mattinannt The Vercel build/deploy isn´t running and after some time thee Run Tests gets invalidated.

**Comment by sebiweise** [comment]
#2133

**Pull request closed without merging**
