### PR TITLE
fix: Multiple Choice Question's Other Field submits each value onChange rather than the final Value

### PR DESCRIPTION
**Pull request by prasoonmhwr**
## What does this PR do?

- fixes Multiple Choice Question's Other Field submits each value onChange rather than the final Value issue

Fixes https://github.com/formbricks/formbricks/issues/1028

https://github.com/formbricks/formbricks/assets/52622674/7f6575d0-4be3-4fa8-aabe-9deb105c6170

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Create a Survey with Multiple Choice question and add an "Other" option type and Publish the survey
Now open the survey, click on the other option and fill anything and click submit
Now go to the survey response page and view how the response is shown.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey @prasoonmhwr, this looks like a hacky way and I'd prefer a cleaner solution though. Like instead of submitting the value on change, you can rather do it on submit and that should be a much cleaner one

**Review by ShubhamPalriwala — APPROVED** [review]
I'm not 100% convinved w the code but should keep us going for now.

Tested it and works pretty nicely! 🚀

**Comment by ShubhamPalriwala** [comment]
Closing this since the bug is fixed in #1004

**Comment by prasoonmhwr** [comment]
@ShubhamPalriwala @jobenjada can this be merged then

**Comment by ShubhamPalriwala** [comment]
Hey, since we already had a fix, we merged that. I'll award you half the points for this since your solution worked as well 🚀 but we couldn't merge it.

**Pull request closed without merging**
