### PR TITLE
feat: New Question Type Meet Scheduling with Cal.com

### PR DESCRIPTION
**Pull request by KapadiaNaitik**
## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [X] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@pandeymangg Thanks a lot for updating the PR 😊🚀
I got stuck in my testing. I have two consecutive cal-com questions. After finishing a booking in the first question; I get redirected to the second question, but I see the confirmation screen and the question doesn't seem to reset, which leads to a lot of confusion as to what happened ;-) 

Screenshot 2023-12-11 at 16 34 31

**Comment by jobenjada** [comment]
hey @KapadiaNaitik 

Thanks for the PR :) Here is my feedback:

1. Description is not displayed:

image

--------

2. Change default button label to "Skip"

Its a bit confusing with the Cal UI inside of the question card. To make sure that the people actually complete the booking, we  change the default button label to "Skip" so it becomes clearer what the button does. 

image

--------

3. If question is required, remove the Skip button completely:

image

-------

4. The "Optional" hint is missing when the question is optional:
image

image

-------

5. The window in a window look on link surveys isn't great, but for now its ok imo @mattinannt 

image

**Comment by mattinannt** [comment]
@jobenjada Anshuman updated the PR; can you please check again 😊

**Comment by jobenjada** [comment]
Hey! Looks great 😍 

Last thing: Pls change default from `rick` to `rick/get-rick-rolled` so that we show the user that they can save a step in the booking by adding /event to their user name.

After this, LGTM!

Good job @KapadiaNaitik and @pandeymangg

**Pull request merged**
