### PR TITLE
feat(github): add social logins (github, google)

### PR DESCRIPTION
**Pull request by kymppi**
Issues: #18 #36 

TODO:
- [x] Github Login Button (styling)
- [x] Add Github provider
- [x] Add required environment variables
- [x] Google Login Button
- [x] Add Google Provider
- [x] Add required environment variables

### CODE REVIEW

**Comment by kymppi** [comment]
Current preview: 
image
image


Fully functional :tada:

**Comment by kymppi** [comment]
There seems to be problems when creating a form after user has signed up with google

**Comment by kymppi** [comment]
Problem: when signing up with social, the user is not saved to the database by next-auth

**Comment by matthiasnannt** [comment]
@kymppi thanks a lot for this PR 🤗 Looks great! Sorry that it took so long for me to get to it. I will check with next-auth and prisma how to make the database integration and how to migrate snoopForms to make this work 😊

**Comment by kymppi** [comment]
@mattinannt Any progress?

**Comment by mattinannt** [comment]
@kymppi With our transition to Formbricks HQ I went through your code and built the remaining parts on the next-auth side into Formbricks HQ and added the Github provider. Thanks for tackling this challenge 💪
We now have Github Auth built within Formbricks HQ (releasing next week) and I'm closing this PR now.

**Comment by kymppi** [comment]
Awesome! :tada: If there's something i could help with, contact me :)

**Pull request closed without merging**
