### PR TITLE
feat: Cal.com embed widget

### PR DESCRIPTION
**Pull request by itsalam**
## What does this PR do?

Adds an embed Cal.com Widget as a survey question, Lets the web application add it in, and view accepted vs. unaccepted resposnes. 

Fixes # (issue)

https://github.com/calcom/cal.com/issues/10811

Survey Question Example (Rick Astley is only cal.com I could find to demo):
https://www.loom.com/share/Demo-App-13-September-2023-891bba7f6d8f43f393e24bbbf52ba6c9?sid=7a95423b-e3d3-492b-b516-8ff9d61fad04

Adding the survey question: 
https://www.loom.com/share/Formbricks-13-September-2023-4e84ea85acbd4635b62a011aafdf0772?sid=7943e18a-7340-4c5d-9326-fb07a768aa18

-->

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

pnpm go, run through manual use cases. 

###Caveats: 

1. @calcom/embed-core doesnt export types, makes it difficult to parse information, so I just have it as a JSON.stringify dump in the component callback on a sucessful attempt. 
2. @calcom/embed-react embed crashes, seems to be an issue with some ref.current, but its hard to debug the minified package, and with preact the interaction is not diagnosable.
3. It seems like the `packages/surveys` doesn't have any styling to match light/dark themes, the cal.com widget will default to its light theme.
4. While the embed widget currently adheres to width and height constraints, it would be convenient if we could config its own overflow. This would require implementation by cal.com's team. Currently, the embed widget exhibits jittery scrolling behavior, especially during booking confirmation when additional elements are added. I've considered rendering the embed as a pop-up ([docs](https://cal.com/docs/core-features/embed/set-up-your-embed#demos), [example](https://codesandbox.io/s/floating-button-popup-react-8pwvk4?from-embed)), but this is a design choice not specified in the issue, so I'll defer to the project owners for a decision.

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

/claim https://github.com/calcom/cal.com/issues/10811

### CODE REVIEW

**Comment by algora-pbc** [comment]
> how should the bounty here work? I think the Algora bot has to be installed in the formbricks repos since Im sure I can't claim it in this PR.

@itsalam no fear algora is here 🫡 your claim is in

**Comment by jobenjada** [comment]
Closing this bc we'll get this merged once we have side loading enabled https://github.com/formbricks/formbricks/pull/708

**Pull request closed without merging**
