### PR TITLE
Feature : Redirect on survey completion

### LINKED ISSUE #397: [FEATURE] Redirect on link survey completion
**Is your feature request related to a problem? Please describe.**
As a user I want to redirect users from a link survey after completion.

**Tasks**
1. Build UI to allow users to toggle "Redirect on completion" and added a URL in an input field into ResponseOptions.tsx - only display if Survey Type === "link"
2. Build logic into "LinkSurvey.tsx"
3. Test

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Now user can toggle "Redirect on completion" and set a link to which form submitter will be redirected after completing form submission

Fixes #397 

Screenshot from 2023-06-19 16-15-43

https://github.com/formbricks/formbricks/assets/67850763/f22074d0-bb08-4512-9032-1469d168cbe9

https://github.com/formbricks/formbricks/assets/67850763/00408c2f-1b70-46d8-990c-8a75d51abce8

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Add a redirect link in "Response options" box in survey settings
Then take a survey and if redirect link is provided than you will be redirected to that link on form submission

## Checklist

- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @Dhruwang 

Thanks for your contribution! 🙏 

I'm getting an error on `pnpm prisma migrate dev`

grafik

Looks like you added the redirectLink to the User model first and changed it. Please make sure to keep the migration history clean by only adding changes which are meant to be permanent.

Thanks! :)

**Comment by Dhruwang** [comment]
@jobenjada 
Oh got it, let me fix it

**Comment by Dhruwang** [comment]
@jobenjada can you check now ?

**Comment by jobenjada** [comment]
Hey @Dhruwang 

Thanks a lot, the new migration works great 😊 Some more feedback:

1. Making it fail-safe: When the user types in e.g. "formbricks.com" or "www.formbricks.com" it doesnt work: 
grafik
Please add a check for "https://" or "http://" and if its missing, add it before the string.

2. Improving UX: Currently, the respondent might think the submission didnt work, because the redirect happens immediately after the survey was submitted. Please add a 3 second timer before the Redirect happens:
grafik
Note: I assume it adds unnecessary complication to keep the timeout before the redirect and the timer in the frontend in sync. It's fine if you just add a timeout in the linkSurvey.ts and display a separate timer in the ThankYou card, when a link survey has a redirectLink set.

Hope this makes sense. Apart from that: Great work, appreciate your contribution 🙌 :)

**Comment by Dhruwang** [comment]
Got it !

**Comment by jobenjada** [comment]
@Dhruwang That works, thanks a lot :)

@mattinannt Pls do the final review

**Review by mattinannt — APPROVED** [review]
@Dhruwang Great job 🎉 Thanks for this PR 😊
I just renamed `redirectLink` to `redirectUrl`, everything else worked great!
I will merge the feature into main now 😊

**Comment by Dhruwang** [comment]
@mattinannt So glad I was able to help ☺️

**Pull request merged**
