### PR TITLE
current url to meta data for link-survey and in-app survey

### LINKED ISSUE #533: [FEATURE] Add current url to meta data for link-survey and in-app survey
**Is your feature request related to a problem? Please describe.**
This feature was requested by a Formbricks user.
A formbricks user running an in-app survey may want to filter the responses based on the page the survey was shown on. Also a formbricks user sending a link survey might want to filter responses based on where users came from by using a self-placed `?utm_source=blog` into the link-url.

**Describe the solution you'd like**
Add the current `url` to the meta data of the response that currently already house the userAgent information:
```
interface Meta = {
  url: string;
  userAgent: {
    browser: string;
    device: string;
    os: string;
  }
};
```

Please make sure to add this to the link-survey as well as the formbricks-js (`packages/js`) in-app client.

The filtering is not part of this issue. This will be done in a later issue as the response filtering is currently being built in a separate PR.

### How we code at Formbricks 🤓

- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

### PR DESCRIPTION
**Pull request by Meetcpatel**
## What does this PR do?

Fixes #533 

https://drive.google.com/file/d/1QD4dSGZBwTKiXn6-Z_jEgAA8wP9GXDE-/view?usp=sharing

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Create an in-app survey
- Create link-survey

## Checklist

- [X] Added a screen recording or screenshots to this PR
- [X] Filled out the "How to test" section in this PR
- [X] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [X] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@Meetcpatel thanks for this PR 💪 Is the PR already ready for review or is it still work in progress? 😊

**Comment by Meetcpatel** [comment]
@mattinannt 
Yes, I will make it ready today

**Comment by Meetcpatel** [comment]
Hi @mattinannt, 
The PR is ready for review

**Review by mattinannt — APPROVED** [review]
@Meetcpatel Works great, thank you! 😊💪 I will merge the changes into main now. Next step for us is to make the information visible but we need to go into a UI planning for this first 😊

**Pull request merged**
