### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by shubhamkhunt04**
## What does this PR do?
This PR will Fix the below bugs
- [x] #499 
- [x] #503 
- [x] #504 
- [x] #607  

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Make Product name, team name, and full name empty or the same, It will show the disable button and red input border based on user actions
- Check any DeleteDialog or AlertDialog padding

## Checklist

- [ ] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @shubhamkhunt04 

since it's WIP I have converted it to a draft. Please also always link the issue you're working on and fill out the PR template so we can keep tabs on who is working on what. Thanks a lot! :)

**Comment by jobenjada** [comment]
hey @shubhamkhunt04 

how is it going? 🤓

**Comment by shubhamkhunt04** [comment]
@jobenjada It is work in progress, I will try to fix it by tomorrow EOD

**Review by jobenjada — CHANGES_REQUESTED** [review]
@shubhamkhunt04 

Sorry for such a delay, didn't got around to review this earlier. 

Thanks a lot! 

Please remove the toasts bc the condition for sending them is the same which disables the button which would issue the Toast.

Afterwards, I'm happy to merge this :)

Thanks a lot for your contribution! 🙏

**Comment by shubhamkhunt04** [comment]
@jobenjada @mattinannt Changes done, Please re-review!

**Review by jobenjada — APPROVED** [review]
looks great, thanks a lot! 🚀

**Pull request merged**
