### PR TITLE
feat: created dark mode version of code block

### LINKED ISSUE #1311: [FEATURE][FormTribe 🔥][150 Points] Create dark mode version of Code Block on landing page
### Is your feature request related to a problem? Please describe.

Currently, our code embed on the landing page doesnt look good on dark mode:

image

Pls also add rounded corners :)

### Describe the solution you'd like

Make it look nice with dark mode. Please use only colors from Tailwind `slate` color palette.

You'll work in this file: `apps > formbricks-com > components > shared > CodeBlock.tsx`

image

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aman44444**
## What does this PR do?
added dark mode version of code block

Fixes #1311 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by aman44444** [comment]
@jobenjada i can make new css file if want because the operators in code of code block still showing text shadow beacuse of prism css and also i can change bg of codeblock if you don't like it.

**Comment by ShubhamPalriwala** [comment]
@aman44444 please make the PR ready for review whenever its ready 🚀 I'll take a look 😁

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala @jobenjada  Sir, Is this issue fixed or still open?

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @aman44444, we'd prefer if you stick to the tailwind classes and use a conditional for all the needed items such as `dark:<>` instead of defining a separate codestyle. This will help us in uniformity across the app

**Comment by aman44444** [comment]
@ShubhamPalriwala we cannot apply the 'important' property directly to Tailwind CSS classes, and it is necessary to override the Prism CSS to achieve the desired output. Sorry it is not possible for me you can assign this issue to someone else. Thank you

**Pull request closed without merging**
