### PR TITLE
docs: question types description and overview

### LINKED ISSUE #3207: [🕹️] Docs: Create one page for each question type we support
### What side quest or challenge are you solving?

Docs: Create one page for each question type we support

### Points

750

### Description

Create a docs page for each question type we currently support.

1. Create a new dropdown in the Navigation under Core Features called "Question Types". Add all of the new pages there (so in `/global/` )
2. Make sure all pages follow the same structure
3. Explain all features specific to each question type
4. Add both a screenshot of the question form (left side) as well as the question itself in the survey (right side). Make sure the content in the questions is somehow related to Customer Experience surveys.
⚠️ All images need to be in .webp - compress and convert using tinypng.com

That should be it :)

### Provide proof that you've completed the task

open a PR for it

### PR DESCRIPTION
**Pull request by marwinburesch**
## What does this PR do?

This adds documentation for all the different types of questions that can be used when crafting a survey

Fixes #3207 

## How should this be tested?

Check if the page is reachable as described in the ticket

## Checklist

- [x] Single-Select
- [x] Multi-Select
- [x] Picture Selection
- [x] Rating
- [x] Net Promoter Score
- [ ] Ranking
- [ ] Matrix
- [ ] Statement (Call to Action)
- [ ] Consent
- [ ] FIle Upload
- [ ] Date
- [ ] Schedule a meeting
- [ ] Address
- [ ] Add images of rendered questions
- [ ] Improve image quality??

### Required

- [x] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
just as a quick pre-review: pls create 1 page per question type :) but it looks like you just wanted to stay within the 48h and looking to complete this over the weekend 💪

**Comment by marwinburesch** [comment]
I'm not entirely happy with the image quality so far. Also, I think it would be super helpful to have images of the output in the default styling, even though you get a preview when crafting a survey. Any opinions?

**Comment by jobenjada** [comment]
hey @marwinburesch sorry for the delayed response. I dont really understand your request, what would you like to do?

Yeah the images are a bit pixelate, what kind of screen do you have?

**Comment by jobenjada** [comment]
/award 150 thanks for your work so far :)

**Pull request closed without merging**
