### PR TITLE
feat: Hidden fields card

### PR DESCRIPTION
**Pull request by United1l**
## What does this PR do?
This is the hidden fields component that allows users(clients) to add meta data to links without setting attributes.

Fixes # (issue)
#887 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?
By verifying the UI and checking if the data prefilling through links work.

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by United1l** [comment]
This is just the structure of the hidden fields component.
There's no design for how the Preview of a hidden fields survey should appear in the Survey editor,

**Comment by jobenjada** [comment]
@United1l  I have rewritten the ticket to be complete, hope this helps :) Let us know if you need support on this one!

**Comment by United1l** [comment]
> @United1l I have rewritten the ticket to be complete, hope this helps :) Let us know if you need support on this one!

Sure thing @jobenjada, Happy to contribute and will do my best. I'll seek support if I get in a bind.

**Comment by jobenjada** [comment]
@United1l Any update on this one?

**Comment by United1l** [comment]
Yes @jobenjada. Let me close the draft and open a PR.

**Pull request closed without merging**
