### PR TITLE
feat: Replace 'Show survey to % of users' slider

### LINKED ISSUE #2716: [FEATURE] Replace 'Show survey to % of users' slider
### Is your feature request related to a problem? Please describe.

Users with millions of views need more granular setting (0.1% or even 0.01%)

### Describe the solution you'd like

Replace this slider with an input field (number) which allows 2 decimals:

image

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manish-singh-bisht**
## What does this PR do?

Replace 'Show survey to % of users' slider

Fixes #2716

[Screencast from 03-06-24 12:20:57 AM IST.webm](https://github.com/formbricks/formbricks/assets/114493480/fa97e6e9-1b27-440b-8387-4cb51a3c4364)

## How should this be tested?

go to survey settings-> survey type should be web or app ->survey trigger->Survey Display Settings->Show survey to % of users

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [ ] [] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by manish-singh-bisht** [comment]
we may need to change the prisma file as well @mattinannt @gupta-piyush19 
Screenshot from 2024-06-03 13-36-23

**Comment by gupta-piyush19** [comment]
@manish-singh-bisht Thanks for the feature, changes looks good. 😊 
But, in order to store decimal values, can you please modify the schema accordingly, and use `Decimal` type instead of `Int`?

**Comment by manish-singh-bisht** [comment]
yes i will change it to decimal. was cautious regarding the schema changes thus thought of asking before changing it.

**Review by gupta-piyush19 — APPROVED** [review]
Thanks, @manish-singh-bisht, for the changes; it works well 🚀 
I made a few minor fixes for consistency; apart from that, the code looks good and is ready to merge. 😊

**Pull request merged**
