### PR TITLE
feat: Add full screen preview feature

### LINKED ISSUE #886: [FormTribe 🔥][500 Points] Full Screen Link Survey Preview
### Welcome to the FormTribe

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

On small screens, its difficult to get a grasp of what you're designing, especially when layouting comes into play soon.

### Describe the solution you'd like

We let people scale up the preview to a almost a full-screen pop-over, like Arc browser does:

image

### Tasks

1. Add a button to the top right of the preview window, use Hero Icon ArrowsPointingOut
image

2. Scale up the window to 90vw and 90vh with a smooth animation. Add dark backdrop, blur and slight shadow to give it a plastic look and feel. Ideally, you can perform the animation without any library. If you have to choose one, use Framer Motion:
image

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yatharth1706**
## What does this PR do?

Added the feature of Viewing Full Screen Preview

Fixes #886 

https://github.com/formbricks/formbricks/assets/32243289/157c704a-d3fb-40a4-ba8d-55453cca8025

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?
Manual testing did on localhost

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @yatharth1706 - thanks a lot for picking this up and welcome to the FormTribe 🔥

Technically, it works. However, it doesn't feel slick, it actually feels a bit broken 🫠  I think it would help already if:

- The blur and dark overlay is not 'loading' from left to right but fading in
- The window is not 50% width at first an then jumps to full-width but opens in full-width right away.

What we're actually looking for is the window to smoothly scale up and down with the button 🤓

**Comment by yatharth1706** [comment]
Sure, I will try to work on points you suggested and improve the animation as well

**Comment by yatharth1706** [comment]
> Hey @yatharth1706 - thanks a lot for picking this up and welcome to the FormTribe 🔥
> 
> Technically, it works. However, it doesn't feel slick, it actually feels a bit broken 🫠
> 
> image
> It would help already if:
> 
> * The blur and dark overlay is not 'loading' from left to right but fading in
> * The window is not 50% width at first an then jumps to full-width but opens in full-width right away.
> 
> What we're **actually** looking for is the window to smoothly scale up and down with the button 🤓
> 
> Wanna rework your submission?

I improved animation and background blur. Is it looking fine now ?

https://github.com/formbricks/formbricks/assets/32243289/0cc8b171-cfd6-4f36-ab28-9d41e89b2d40

**Comment by jobenjada** [comment]
Hey! This is better, thanks! 

Please fix the following:

1. There is an error in the console:
image

2. The margin right got lost for the Refresh button and the container is a bit shorter than before so we're losing precious screen space:

Screenshot 2023-10-03 at 10 07 25

image

-----

I also tried to play around with it and get GPT to suggest a solution where it actually looks like the preview window is growing to full screen instead of a new window being opened. I think the issue is that we're toggling between absolute and relative positioning. Can we find a way where we stick with absolute positoning?

Or why do you think is it not looking like the same window grows to fill the screen?

Thanks!!

**Comment by yatharth1706** [comment]
Hi @jobenjada , I have fixed all the points you suggested.
1. Fixed first render animation issue
2. Fixed margin right and border radius issue (this one was existing issue can be visible in actual production website though, but fixed it in this pr). Container height also fixed.
3. Note in the console fixed
4. Improved animation so that it looks natural. Tried my best. Do let me know if it needs more improvement. Will analyse it more.

Attaching a small demo of how it looks now

https://github.com/formbricks/formbricks/assets/32243289/fa668e06-d475-48d0-be46-2aca96a4dd3b

**Comment by jobenjada** [comment]
Thanks a lot for your presistence, really appreciated :)) 

This is pretty good! I know someone who could help actually, let me reach out and follow up with you!

**Comment by yatharth1706** [comment]
> Thanks a lot for your presistence, really appreciated :))
> 
> This is pretty good! I know someone who could help actually, let me reach out and follow up with you!
> 
> https://twitter.com/formbricks/status/1709432803606077691

Sure @jobenjada , Although I will try again in the evening to improve this more. Will analyse it again how to make animation look more slick and natural.

**Comment by yatharth1706** [comment]
Hi @jobenjada , I was trying to improve the animation. I am attaching two demo videos. Do let me know which one do you prefer. Although they might not be perfect, but want to know what you think and which one is good from user perspective, so that i will improve that one.

In this, i added a little delay while changing position from relative to fixed, so that it looks like the screen is becoming full screen from its original position, as you can see in demo. And it does not appear like a new window opening. Only one problem in this is that while changing from relative to fixed, its not smooth. I am trying to figure out any way to make that smooth, but stuck in that.

https://github.com/formbricks/formbricks/assets/32243289/3d924b6f-eaeb-4c12-9e2e-d221402ed35e

In this i am not adding any delay between fixed and relative position, so it might look like a new window is opening although this one is smoother. Only drawback i guess its not looking natural and looking like a new window is opening
https://github.com/formbricks/formbricks/assets/32243289/b222bb16-2079-4107-b19a-8fc4607c4f61

Do let me know what you think. I will try to still improve it.

**Comment by jobenjada** [comment]
The first one is verrrry close already! Any idea, why its not animating the scale up? I think you're 95% there 🫶

Great work! You're a strong candidate for the +500 points award as Pixel Picasso :D

**Comment by yatharth1706** [comment]
> The first one is verrrry close already! Any idea, why its not animating the scale up? I think you're 95% there 🫶
> 
> Great work! You're a strong candidate for the +500 points award as Pixel Picasso :D

Yes, in the first one, i have added a little delay of around 300ms. After that i am making it position fixed, so that it covers the whole screen. From position relative to fixed when its going, its not animating. Will check framer motion docs for this, if i can find anything for this scenario

**Comment by yatharth1706** [comment]
Hi @jobenjada , I tried making it look more natural. But still its not 100% smooth. But i would request you to once use this locally so that you can get a feel of how maximize is working currently and what is your user experience.

I tried finding some solution in framer motion. It said to use layout keyword for change in position layouts, but its not giving me super smooth animation. Let me know if you have any ideas.

**Comment by jobenjada** [comment]
@yatharth1706 I think its fine, from the last 2 options you presented, please commit the first one and resolve the merge conflicts. Happy to get it merged then! :) 

Thanks for your good work! Really appreciated 🙏

**Comment by yatharth1706** [comment]
Hi @jobenjada, i have resolved the merge conflicts. Can you review this. Also if you could check the animation manually, that would be great. I have made a slight change as there was width and height inconsistency with the actual production app. Also decreased the bottom margin a little when maximizing as it was getting cut with top nav bar when its in relative state.

Do let me know if this works fine.


https://github.com/formbricks/formbricks/assets/32243289/050bcd10-2ea1-4c3f-a94f-b494e15a46c9

**Comment by jobenjada** [comment]
@yatharth1706 thanks a lot!! :)

**Comment by yatharth1706** [comment]
Welcome @jobenjada

And thanks for merging this. Also, it might not be 100% according to what you would have wanted. But i will rework on it in future and improve the animation for sure.

**Pull request merged**
