### PR TITLE
feature/extend link context menu

### PR DESCRIPTION
**Pull request by moritzrengert**
## What does this PR do?

Adds a preview survey and copy link option to the link survey context menu.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Click preview survey and check if it opens in preview mode in new tab
- Copy link to clipboard
- Check if it doesnt appear on in-product surveys

## Checklist

- [x] I have read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have added comments to my code, particularly in hard-to-understand bits
- [x] I ran `pnpm build` and `pnpm lint` to prevent build and linting errors
- [x] My contribitiom does not cause any warnings
- [x] I have removed all `console.logs`
- [x] I have merged the latest changes from main onto my branch with `git pull origin main`
- [x] My contribution causes changes to the Formbricks Docs

### CODE REVIEW

**Review by mattinannt — CHANGES_REQUESTED** [review]
@moritzrengert Thanks for the PR 😊 Please provide a screenshot when visual changes are made.
The link options also show when Survey is still a draft where the survey can't be previewed and isn't publicly available. Please hide the new options when survey status is `draft`.
Screenshot 2023-05-26 at 10 00 26

**Comment by moritzrengert** [comment]
Removed the link options from draft surveys context menu. 🙂

**Comment by jobenjada** [comment]
merged main, looks good :)

**Review by mattinannt — APPROVED** [review]
😊🎉🙏

**Pull request merged**
