### PR TITLE
docs: add prerequisities to readme.md

### PR DESCRIPTION
**Pull request by rotimi-best**
## What does this PR do?

From my investigation of other Open source projects, one thing we didn't have was a Prerequisites section in our README.md. This PR fixes this.

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Open README.md
- Look for Prerequisites section
- You should see this
image

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@rotimi-best We currently have in the README a mix of Getting started with development and getting started with usage.
For usage we recommend the Formbricks Cloud or the docker setup or a deployment on third party services like railway.
For development / contributing we have the requirements you pointed out and the gitpod setup.
Can you think of a good way to restructure the README so it's clear which path to go?

**Comment by rotimi-best** [comment]
@mattinannt Sure, will give it more thoughts

**Comment by rotimi-best** [comment]
@mattinannt I made a couple of improvements

1. I added a short note stating that we have different options to get started with formbricks
2. Moved prerequisites to the development section to make it clear for anyone choosing to run formbricks locally


image

**Comment by rotimi-best** [comment]
Does this address your concern with the structure or is there something specific you think isn't clear enough?

**Comment by rotimi-best** [comment]
@mattinannt Something like this?

image

**Comment by mattinannt** [comment]
> @mattinannt Something like this?
> 
> image

I like that :-) Maybe an intro sentence to self-hosting and then first section (same size as `Community managed One Click Hosting` but with `Docker`)

**Review by mattinannt — APPROVED** [review]
😊💪

**Pull request merged**
