### PR TITLE
fix: delay stacked card container height calculation

### LINKED ISSUE #2784: [BUG] Background Tiles not resizing properly
### Issue Summary

When going back and forth between tiles, the background tiles sometimes do not resize properly.
(I changed the background to green in this video to increase the contrast)
[scrnli_6_19_2024_4-43-35 PM.webm](https://github.com/formbricks/formbricks/assets/64426524/a57dbae9-4147-4362-a013-8c516cd37972)

### Steps to Reproduce

I was able to reproduce the issue with this setup, I guess it also affects other flows:
1. Create a survey with logic jump and star rating question just like in the video
2. Select 5 stars -> tiles resize properly
3. Go back and select 3 stars (jump to different question) -> tile resizes properly
4. Go back and select 5 stars again -> tiles do not resize properly

### Expected behavior

Background tiles resize properly.

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
latest
```

### PR DESCRIPTION
**Pull request by itsjustaplant**
## What does this PR do?

[legact-react-docs](https://legacy.reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node)
[similar-stackoverflow-issue](https://stackoverflow.com/questions/60476155/is-it-safe-to-use-ref-current-as-useeffects-dependency-when-ref-points-to-a-dom)

Accessing ref inside useEffect hook is not a good idea because of the nature of useEffect. 
Trying to access `const currentElement = cardRefs.current[questionIdxTemp];` returns null, thus height is set incorrect. 
As a solution, delaying this part a pit allows us the access rendered content.

Fixes #2784 

## How should this be tested?

- Go create survey with 3 questions
- First question is __Rating__ with long description
- Second question is __Free Text__ 
- Third question is __Free Text__
- Add logical so that when rating is 2 we show 2nd question and when rating is 3 we show 3rd question
- First give it a 3 rating and then click back
- Now give it a 2 rating and observe
- If doesn't work go back and give it a 3 rating again and observe

### Required

- [ ] Filled out the "How to test" section in this PR
- [X] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [X] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by gupta-piyush19** [comment]
Hey @itsjustaplant, Thanks for the PR. 😊 
I was not able to reproduce the issue before these changes. Can you please maybe provide a recording of what exactly this PR solves?

**Comment by itsjustaplant** [comment]
Hey @gupta-piyush19 , i am adding the video recording from the original issue. [video](https://github.com/formbricks/formbricks/assets/64426524/a57dbae9-4147-4362-a013-8c516cd37972) , [issue](https://github.com/formbricks/formbricks/issues/2784)

**Comment by gupta-piyush19** [comment]
@itsjustaplant I Saw this video on the original ticket, but I am still unable to reproduce this issue. Can you please share a video reproducing this and fixing it with your code changes? 🙏

**Comment by gupta-piyush19** [comment]
Yeah, no worries. @itsjustaplant 
I followed the same steps you did in the video. Somehow, I'm not getting this issue, but does this get fixed with your changes?

**Comment by itsjustaplant** [comment]
@gupta-piyush19 , yes the changes that i made fixes this issue, [video from local build with fix](https://www.loom.com/share/00301ce56f9e46e6b8311b147408c065). When useEffect runs ref object can be null, I simply defer the calculation process by adding a timeout.

**Comment by gupta-piyush19** [comment]
Ahh, nice! Thanks, @itsjustaplant, for the video and explanation. 🙏 
Just a few more questions,
1. what's your local environment config? (OS, browser)
2. Were you facing the same issue with your gitpod hosting as you did with the formbricks prod cloud app?

Though code changes look good to me, we can merge them right after this. 
Sorry for being paranoid, but I am a bit sceptical before accepting any change in the stackedCardContainer as this component can affect a lot of things(in the survey rendering 😅)

**Comment by gupta-piyush19** [comment]
Thanks, @itsjustaplant, for the explanation. 
LGTM 🚀 
Can you please comment `/assign` on the original issue, so that you can get assigned to the issue and avail the oss.gg points for the fix?

**Comment by gupta-piyush19** [comment]
@mattinannt, can you please take a quick look at the code changes? 
LGTM 🚀

**Pull request merged**
