### PR TITLE
- Group Events of same Type in Activity Timeline

### LINKED ISSUE #453: [FOR-900] Group Events of same Type in Activity Timeline
**Problem / Need**

As a user, I want to have an overview of the events tracked in the Acivity Timeline on the Person Detail page. The Exit Intent event spams the timeline.

**Describe the solution you'd like**

If the same event is fired repeatedly, group it and display a count indicator instead.

(see screenshot below)

**Tasks**

* If 3 or more events are of the same type, group them
* Show a count indicator
* Show the timeSince of the most recent event recorded

### How we code at Formbricks 🤓

* Everything is type-safe
* All UI components are in the package `formbricks/ui`
* Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
* We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-900](https://linear.app/formbricks/issue/FOR-900/group-events-of-same-type-in-activity-timeline)</sub>

### PR DESCRIPTION
**Pull request by kuluruvineeth**
## What does this PR do?

Fixes #453 

https://github.com/formbricks/formbricks/assets/47528651/4bf9c7d4-c5b9-4b0e-94ad-e97e6e7fba73

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @kuluruvineeth - Thanks a lot for picking this up!

I was wondering if we can also group them serverside? This could allow us to speed up the loading of the Person Detail Page because we dont have to transfer the full event data for each event but only once per instance + count?

What do you think?

**Comment by kuluruvineeth** [comment]
@jobenjada i think its better to keep it the way it is now in server side, so that we will have data for better tracking incase of any mishaps.

**Comment by jobenjada** [comment]
Hey! Makes sense, we can keep it how it is - thanks! 🙏 

I tested it a bit more and it seems to be not working 100% correctly. If I check the Demo Data in the Demo Project, the numbers are off:

Here we have 5 "Survey seen" events followed by a few single events:

image

Locally, it spits out this: High sums of actions and quite different actions as well
image

Any idea how that could be?

Additionally, it only shows one of the surveys in the list:
image

The tooltip should contain the name of all surveys which were displayed.

---

Testing it locally, its also off:

image

---

Here is how it has to work:

1. Maintain the correct chronological order (its a timeline)
2. ONLY if there are several identical actions behind each other, they should be grouped together, like here:

image

Group the 4 occurrences of "50% scroll triggered" together. If the same action pops up at a different point in the timeline, it should not be added to the group - always keep them in chronological order.

Hope this makes it clearer. 

Thanks for working on this, really appreciated 😊

**Comment by kuluruvineeth** [comment]
> Hey! Makes sense, we can keep it how it is - thanks! 🙏
> 
> I tested it a bit more and it seems to be not working 100% correctly. If I check the Demo Data in the Demo Project, the numbers are off:
> 
> Here we have 5 "Survey seen" events followed by a few single events:
> 
> image
> Locally, it spits out this: High sums of actions and quite different actions as well image
> 
> Any idea how that could be?
> 
> Additionally, it only shows one of the surveys in the list: image
> 
> The tooltip should contain the name of all surveys which were displayed.
> 
> Testing it locally, its also off:
> 
> image
> Here is how it has to work:
> 
> 1. Maintain the correct chronological order (its a timeline)
> 2. ONLY if there are several identical actions behind each other, they should be grouped together, like here:
> 
> image
> Group the 4 occurrences of "50% scroll triggered" together. If the same action pops up at a different point in the timeline, it should not be added to the group - always keep them in chronological order.
> 
> Hope this makes it clearer.
> 
> Thanks for working on this, really appreciated 😊

got it, will work on the changes

**Comment by jobenjada** [comment]
@kuluruvineeth any updates from your end? :)

**Comment by kuluruvineeth** [comment]
> @kuluruvineeth any updates from your end? :)

@jobenjada will complete this weekend.

**Comment by kuluruvineeth** [comment]
Hi @jobenjada 

- As per your inputs i have fixed all the issues.
- Please review and let me know if still needed any changes.

- Functionality wise all looks fine for me, but there is type error when trying to get on to particular peoples page.
- The type error is with respect to **activityFeedItem** in  model **TActivityPopOverItem** - Please look into it and let me know your inputs and accordingly i would make the changes.

Screenshot 2023-09-16 at 3 39 18 PM
Screenshot 2023-09-16 at 3 39 35 PM

**Comment by jobenjada** [comment]
Hey @kuluruvineeth 

Thanks for following up with this 🙏 

It is still not working as supposed to, let me break it down for you with the People in the Demo product:

This is the status quo:

image

This is your solution:

image

Here is what's off:

1. UserId was set 1x not 10x. So when an attribute is added, you have to distinguish them, instead of bundling it. While it is the same event (Attribute added) the metadata is really important here. I suggest that you dont bundle Attributes at all, only Actions.

2. User Actions are not displayed correctly. In the original one you see this:
image

and in your bundling, you see this:

image

So instead of having 1x Exit Intent and 5x 50% scroll, you display 3x Exit Intent and 3x 50% Scroll.

3. Updated availability happened 4 times but you display it only once:

image

image

etc. etc. etc.

If you closely compare the Demo Data ( you can do so by creating an account at app.formbricks.com and look at the same person you're looking at in your PR) you see a loooot of inaccuracies. 

--------

**TypeError:** You attached 2x the same screenshot so I suppose the other one was meant to display the type error. Was it this one?
 
image

I don't think its related to a type issue rather the page tries to process the activity feed before it was loaded from the server. You have to make sure that activityPopOverItem is fully loaded and set before accessing its activityFeedItem.

---------

For your next update please make sure to compare at least **5 person detail pages and check if everything is displayed correctly!**

Thanks a lot!
Johannes

**Comment by jobenjada** [comment]
@kuluruvineeth are you willing to complete your work on this PR?

Happy to award you 250 Points for our [FormTribe hackathon!](https://formtribe.com) It would give you a ticket to win a Mac at the end of the month :)

**Pull request closed without merging**
