### PR TITLE
feat: Data table for persons

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Fixes https://github.com/formbricks/internal/issues/355

Screenshot 2024-09-18 at 11 45 56 AM

## How should this be tested?

Test people page

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

## Release Notes

- **New Features**
	- Introduced the `PersonTable` component for displaying and managing person data with customizable column order through drag-and-drop functionality.
	- Enhanced the `ResponseTable` with improved column management and user preferences saved in local storage.

- **Improvements**
	- Adjusted the table container's CSS for better layout responsiveness, allowing it to fit content rather than expanding to full width.
	- Refined styling in the `ResponseTableCell` for improved visual consistency.

- **Bug Fixes**
	- Streamlined import paths for utility functions to improve code organization.

### CODE REVIEW

**Comment by jobenjada** [comment]
hey @Dhruwang 

UI looks good except for if I remove columns the last one isn't rounded anymore (pls also check on Response t able):
image

And please retain survey settings (incl. collapse / dont collapse) in local state for Person Table and Response table.

Thanks!

**Review by jobenjada — CHANGES_REQUESTED** [review]
pls see prev comment

**Comment by Dhruwang** [comment]
https://github.com/user-attachments/assets/2ed1bb25-fb5d-487e-9154-eef297041599

Fixed above mentioned issues 😊

**Review by jobenjada — APPROVED** [review]
pls fix the corner of the scroll bar and then LGTM 🪨

**Pull request merged**
