### PR TITLE
feat: recall information functionality

### LINKED ISSUE #884: [FormTribe 🔥][1250 Points] Recall information
### Welcome to the FormTribe Hackathon!

This issue will get you **1000 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------
### Issue

Users want to create more personalized, sticky surveys by including responses of previous answers in subsequent questions and descriptions.

### Describe the solution you'd like

Allow recalling information using @ plus selecting one of the preceding questions from a dropdown:

image

### **How it should work in the UI:**

- Write @ in the question or description field opens the dropdown
- The first option is already focussed indicating that a selection can be made using the keyboard
- ENTER selects the question, which then is linked (UI below)
- Clicking on the linked question opens a different context pop up where users can set a default or fallback in case there is not response to be displayed in the placeholder:

image

### **What happens technically:**

We need a special syntax inside the strings to indicate, that a recall should be done together with the questionId to link to, e.g. "So recall:cjld2cjxh0000qzrmn831i7rn, how do you like Formbricks?"

Also the fallback should be able to be added:
"So recall:cjld2cjxh0000qzrmn831i7rn/fallback:my%20fallback, how do you like Formbricks?"
In this example the fallback is url-encoded and instructions are devided by a /. If you can think of a better approach for solving this, you are welcome to implement it.

When the question gets rendered in the @formbricks/surveys package we also need to pass the current responseData to the question component and replace the recall information in the strings. Please write a reusable logic for this.

Please consider the edge cases:

- When there is not data in the recalled response and no fallback is specified, please render an empty string
- When the questionId gets changed inside the surveyEditor, please make sure to also change the questionId in all recall strings.
- When a question gets deleted remove the recall for this questionId from all strings.

### Thanks!

### PR DESCRIPTION
**Pull request by yashnirmal**
## What does this PR do?

Added recall feature
Fixes #884 

https://www.loom.com/share/4b5016a273514cf4b30d539d73c56b81?sid=f29172ff-e8fb-46ab-991d-3470feb545b1

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Try creating recall questions and fallback to them

## Checklist

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Thanks @yashnirmal - this looks quite good so far :) 

Looks like you've deleted our new and precious input types for the test question though ;) @Dhruwang  will look a bit closer at your code to get a better understanding of what you've built.

I'm happy to reserve this issue to you and also increase the points to 1500 since I am aware that this is quite a comprehensive contribution! We would take several feedback loops to get it working stable incl edge cases and looking nice.

Would you be up for this?

**Comment by yashnirmal** [comment]
> Thanks @yashnirmal - this looks quite good so far :)
> 
> Looks like you've deleted our new and precious input types for the test question though ;) @Dhruwang will look a bit closer at your code to get a better understanding of what you've built.
> 
> I'm happy to reserve this issue to you and also increase the points to 1500 since I am aware that this is quite a comprehensive contribution! We would take several feedback loops to get it working stable incl edge cases and looking nice.
> 
> Would you be up for this?

Thanks @jobenjada and yes I would love to work on this feature going ahead

**Comment by jobenjada** [comment]
Hey @yashnirmal how is it going? Sorry for the delay, our team offsite threw us off a bit :)

Here is my test log:

----

1. You've built the recalling for Open Questions, but we need it for all question types + descriptions. However, since we'll have to build a new custom input component to facilitate the UI, we can then reuse it in all question types and descriptions:

image


------

2. The @ popover is quite buggy: if you hit @ in one question card, its open everywhere. It doesnt close on outside click (or at all). 

https://tella.video/johanness-video-2xd9

-----

3. The @ popover contains questions which are positioned after the question where we type @. This obviously wont work since we cannot recall answers to a question which didnt show up yet:

image

-----

4. Edge case: We change the Id of a question which is recalled:

Screenshot 2023-10-14 at 19 36 13

I'm not entirely sure what the best solution here is. @ShubhamPalriwala built validation for the Survey Editor, Im sure he has an idea :) At least, the question where it broke, should be flagged red.

-----

That's it for now :) I think this will give us enough for work on ;)

@yashnirmal when do you plan to work on this more? 🚀

**Comment by yashnirmal** [comment]
Thanks @jobenjada for pointing these bugs out, I will solve them asap.
As for building component for input, @yatharth1706 as has come up me a solution, you can see that here https://github.com/formbricks/formbricks/issues/884#issuecomment-1763070580

**Comment by ShubhamPalriwala** [comment]
Hey @yashnirmal, just took a higher level look on what you're building and its super cool 🚀

For the validation, 
1. For a leniant checking, what you can do is, whenever a questionID is updated, update the same in recall information as well ie run a loop to find out where all the existing questionId is used and update it accordingly in the fields provided.
2. For a more strict checking, what you can do is, throw off an error on the the question where the recall information for this changes questionID is used.

If you need help at a lower level in the code for this, do ping me!

**Pull request closed without merging**
