### PR TITLE
fix(bug): #969 bug new team not listed in teams list

### LINKED ISSUE #969: [BUG][FormTribe 🔥][150 Points] New teams are not listed in teams list
### Welcome to the FormTribe

This issue will get you the points mentioned in issue title for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

--------

### Issue Summary

When creating a new team, it is not listed in the teams overview in the top menu:

https://tella.video/johanness-video-57q7

### Steps to Reproduce

1. Create a new team
2. Look for it in the team switch

### Expected behavior

Each new team should appear in the team switch

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by adityadeshlahre**
Change in service.ts [unstable_cache to prefecthing]

## What does this PR do?

Fixes #969
**[loom video]**
(https://www.loom.com/share/e93663a0c9164ae685f5952147622173?sid=bab604ef-1a49-4b07-b832-56770dfb20d4)

## Type of change
changed unstable_cache to prefecthing on [service.ts]
file location [workspcae/formbricks/packages/lib/team/service.ts]

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- pnpm build
- pnpm test
- pnpm lint

## Checklist

**Database fetching related errors are still there !**
EDIT (by running) :  [ pnpm clean && pnpm install && pnpm build ] fixed this issue :fire: 

image

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
@pandeymangg pls review, you've worked with the caching a lot 🤓

**Comment by anjy7** [comment]
> @pandeymangg pls review, you've worked with the caching a lot 🤓

Hey @jobenjada, I tried to use React cache function with this function and it worked as desired - I was able to get the newly team created in the dropdown.

Here's the docs for it and its mentioned right above unstable_cache, could be a possible alternative.

Screenshot from 2023-10-07 17-40-45

**Comment by anjy7** [comment]
> > @pandeymangg pls review, you've worked with the caching a lot 🤓
> 
> Hey @jobenjada, I tried to use React cache function with this function and it worked as desired - I was able to get the newly team created in the dropdown.
> 
> Here's the docs for it and its mentioned right above unstable_cache, could be a possible alternative.
> 
> Screenshot from 2023-10-07 17-40-45

Also we are using the same unstable cache function in the add products dropdown as well, but over there it gets updated quickly unlike this. Looks like it really is "unstable" currently :)

**Comment by pandeymangg** [comment]
@adityadeshlahre I think you don't need to replace the unstable_cache with the cache function, instead the whole caching-revalidating strategy can work absolutely fine here. So just like the `unstable_cache` function, there's also the `revalidateTag` function that you can import like this:

`import { revalidateTag } from "next/cache";`

and then in the team service in `packages/lib/team/service.ts`, you can revalidate the cache for the `getTeamsByUserId` service. So in the `createMembership`service, add the following code and it should work fine:

`revalidateTag(getTeamsByUserIdCacheTag(userId));`

**Comment by adityadeshlahre** [comment]
please look at the PR #1010 this moved to new PR because this have some unnecessary commits !
thankyou !

**Pull request closed without merging**
