### PR TITLE
docs: added contact form article

### LINKED ISSUE #3200: [🕹️] Article: How to add a contact form to any website and get notified for free
### What side quest or challenge are you solving?

Article: How to add a contact form to any website and get notified for free

### Points

1500

## This gives A LOT of points because writing a high quality technical article with good instructions, screenshots, etc. can take a full day or more 🤓

Here is the [Formbricks Writing Guide](https://formbricks.notion.site/FormTribe-Content-Writing-Guide-f6464ee837364785afdc6c88ef8bfd51?pvs=74)

### PR DESCRIPTION
**Pull request by Aditya-PS-05**
## What does this PR do?

Fixes #3200 

## How should this be tested?

- Simple UI test needed

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [X] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [X] If a UI change was made: Added a screen recording or screenshots to this PR
- [X] Updated the Formbricks Docs if changes were necessary

### Images
Screenshot from 2024-10-12 17-55-24

Screenshot from 2024-10-12 17-55-30
Screenshot from 2024-10-12 17-55-36

Screenshot from 2024-10-12 17-55-42

Screenshot from 2024-10-12 17-55-51
Screenshot from 2024-10-12 17-55-59

## Summary by CodeRabbit

- **New Features**
	- Introduced a comprehensive guide for creating a contact form using Formbricks, including step-by-step instructions and visual aids.
	- Added a new "Contact Form" link under the "Features" section for easier navigation to the guide.

- **Documentation**
	- Enhanced documentation with a detailed contact form creation guide, covering setup, customization, and integration.

### CODE REVIEW

**Comment by jobenjada** [comment]
hey! pls move this to the Best Practices section

**Review by jobenjada — CHANGES_REQUESTED** [review]
pls move to Best Practices and run through GPT to avoid typos - thanks! :)

**Comment by Aditya-PS-05** [comment]
@jobenjada , 
Thanks for review, I will do it as soon as possible. Any other suggestion related to the content or something else?

**Comment by Aditya-PS-05** [comment]
@jobenjada ,
Should I remove the `What we'll build section`.

> pls move to Best Practices and run through GPT to avoid typos - thanks! :)

The changes done and the format of the article is also made like it's described.

**Review by jobenjada — APPROVED** [review]
looks good :)

**Pull request merged**
