### PR TITLE
ossgg: update -brand with -brand-dark

### LINKED ISSUE #3215: [🕹️] Replace `-brand` with `-brand-dark`
### Is your feature request related to a problem? Please describe.

We have a few places throughout the app where we still use the old `-brand` color

### Describe the solution you'd like

Find them and replace them with `-brand-dark`

**Include before:after screenshots for each change that you make in the PR description!**

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vanshii**
## What does this PR do?
This pull request updates instances of the -brand color throughout the application to utilize the new -brand-dark color scheme. The previous -brand color was still present in several areas of the app, and this update ensures consistency by replacing all occurrences with the updated -brand-dark color.

Fixes # (issue)
This pr fixes #3215 

## How should this be tested?

- Test A
- Test B

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

## Release Notes

- **New Features**
	- Added a new environment configuration file for the web application to inherit settings, improving its configuration and runtime behavior.

- **Style Updates**
	- Updated various components to reflect a darker theme for input fields, buttons, and other UI elements, improving visual consistency across the application.
	- Adjusted class names for active states in multiple components, including `SideNavigation`, `DisableTwoFactorModal`, and `PasswordResetForm`, among others.

- **Bug Fixes**
	- No specific bug fixes were noted in this release.

- **Chores**
	- Removed unnecessary environment configuration file, streamlining the application setup.

### CODE REVIEW

**Review by jobenjada — CHANGES_REQUESTED** [review]
hey @Vanshii 

thanks a lot for your contribution.

I haven't been 100% in the ticket because in the surveys package, we're not referring to the formbricks brand color when we use `brand` but instead to the brand color that the user set. So in this instance, there is no `brand-dark`

Please revert the changes for all the files in `/packages/surveys` 

Thanks!

**Comment by Vanshii** [comment]
> hey @Vanshii
> 
> thanks a lot for your contribution.
> 
> I haven't been 100% in the ticket because in the surveys package, we're not referring to the formbricks brand color when we use `brand` but instead to the brand color that the user set. So in this instance, there is no `brand-dark`
> 
> Please revert the changes for all the files in `/packages/surveys`
> 
> Thanks!

**Comment by Vanshii** [comment]
Hey @jobenjada requested changes have been made can you please review

**Review by jobenjada — APPROVED** [review]
thanks a lot LGTM!

**Comment by jobenjada** [comment]
hm it doesn't build, do you use out Gitpod setup?

**Comment by Vanshii** [comment]
No i used github only

**Comment by jobenjada** [comment]
weird, we'll figure it out then. I've closed the issue so you can pick up another one. You'll get the points once this is merged :) Thanks for your contribution 🙏

**Pull request merged**
