### PR TITLE
feat: add GTM integration in survey page

### PR DESCRIPTION
**Pull request by RaflyLesmana3003**
## What does this PR do?

Feat: include query parameter from current page to redirected page for marketing needs like tracking url

Feat: add GTM integration on survey page

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Create Survey and access the survey url with utm you can build utm url here https://utmbuilder.net/
- in survey setting you should set the Redirect on completion on your desired website
- when you already submit the survey the utm (query parameter) should be included on the redirected url

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by RaflyLesmana3003** [comment]
Thank you so much for your attention 🙌🏻

**Comment by jobenjada** [comment]
hey @RaflyLesmana3003  - thanks for your contribution! Here is my feedback:

1. Im having a look into the PR, have you tested if it works? Looks like you've added it to the Countdown, not sure if thats correct.
2. Have you considered adding some UI to add the GTM ID instead of an env variable? We try to keep the number of env ids a small as possible and UI would allow marketers to set this up themselves (without having to involve engineering)
3. Please add a Docs page with a short tutorial on how to add a GTM ID and how to verify if that worked.

Thanks a lot - really appreciate your time and effort! 🙏

**Comment by RaflyLesmana3003** [comment]
Hi @jobenjada thanks for the feedback, yeah i already test it and that code already used in my product.

and my approach was i only added the query parameter in countdown after the user submit the form, is the any feedback about this?

> Have you considered adding some UI to add the GTM ID instead of an env variable? We try to keep the number of env ids a small as possible and UI would allow marketers to set this up themselves (without having to involve engineering)

that's a good idea, i will added GTM ID to database and add setting for input field

**Comment by mattinannt** [comment]
@RaflyLesmana3003 💪 When adding the GTM ID to the database I think the best approach would be to use the existing infrastructure we already have with `Integrations` and add a new integration of type `googleTagManager`.

**Comment by jobenjada** [comment]
@RaflyLesmana3003 wanna make the needed changes for us to get this merged? 🤓

**Comment by RaflyLesmana3003** [comment]
> @RaflyLesmana3003 wanna make the needed changes for us to get this merged? 🤓

yes, i will create the changes

**Comment by RaflyLesmana3003** [comment]
Hey @jobenjada,

It's been 5 months 😀. I've been so busy lately, but I've now resumed work on this integration. I hope I can still contribute to this repo.

Here's my new PR for this feature.
#2651

**Pull request closed without merging**
