### PR TITLE
chore: (docs) review navigation & information hierarchy

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## What does this PR do?
- merge self hosting and contributing under dev resources
- merge actions and attributes under concepts
- moved Best Practices section at the end (just before API)
- moved top 4 best practices component from homepage to "How does it work" page
- added the "Why Formbricks" page to the 1st tile of the Getting Started component

ToDo:
- [ ] Redo home page content
- [x] Update links for everywhere in the redone pages
- [x] Add redirects for old links for users to not get a 404
- [ ] Get feedback and iterate more
- [x] Create Formbricks Survey for the docs

## Type of change
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] This change requires a documentation update

## Checklist
- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — COMMENTED** [review]
@ShubhamPalriwala thanks for this first draft :-) As this is still a phase of exploration I think our process here should be as lean as possible. I think it's better if we first only change the content and the navigation and relocate / rename urls later as every relocation also needs to be added as a redirect to not affect our SEO. Is it possible here to only refactor the navigation?

**Comment by ShubhamPalriwala** [comment]
that makes sense, let me revert back the URL changes and ping you

**Comment by jobenjada** [comment]
putting in the back burner for now

**Comment by mattinannt** [comment]
We will pick up some of these changes and redo them on the current codebase, sorry for not being able to merge this in time.

**Pull request closed without merging**
