### PR TITLE
feat: React Native SDK

### PR DESCRIPTION
**Pull request by neo773**
## What does this PR do?

This PR adds SDK for React Native to embed surveys

https://github.com/formbricks/formbricks/assets/62795688/6644cf7a-5cbf-4cce-8a0b-aee6796f2620

https://github.com/formbricks/formbricks/assets/62795688/23e164ea-d0f2-4050-bc50-1e82c8122fc3

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?
```bash
cd packages/react-native && pnpm run build
cd apps/react-native && pnpm start
```
Replace "YOUR_SURVEY_ID" with yours in `apps/react-native/src/App.tsx:8`

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [] Self-reviewed my own code
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR

### CODE REVIEW

**Comment by mattinannt** [comment]
@neo773 thank you very much for opening a PR for this 😊💪 @ShubhamPalriwala will take a first look at it :-)

**Comment by ShubhamPalriwala** [comment]
Hey @neo773, thanks for opening the PR! I tried to follow your commands to test it ie:
1. `cd packages/react-native && pnpm run build` ran successfully
2. Added the surveyId as well for of a localhost URL
3. `cd apps/react-native && pnpm start` gave me the following error:

```sh
› Metro waiting on exp://192.168.29.190:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
metro-file-map: Haste module naming collision: formbricks
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/../../package.json
    * <rootDir>/../web/.next/standalone/package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/home/shubham/Desktop/formbricks/node_modules/metro-file-map/src/index.js:450:17)
    at workerReply (/home/shubham/Desktop/formbricks/node_modules/metro-file-map/src/index.js:507:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 98773)
    at async HasteMap._applyFileDelta (/home/shubham/Desktop/formbricks/node_modules/metro-file-map/src/index.js:672:7)
    at async /home/shubham/Desktop/formbricks/node_modules/metro-file-map/src/index.js:327:9
    at async DependencyGraph.ready (/home/shubham/Desktop/formbricks/node_modules/metro/src/node-haste/DependencyGraph.js:95:5)
    at async Bundler.ready (/home/shubham/Desktop/formbricks/node_modules/metro/src/Bundler.js:69:5)
    at async IncrementalBundler.ready (/home/shubham/Desktop/formbricks/node_modules/metro/src/IncrementalBundler.js:289:5)
    at async Server.ready (/home/shubham/Desktop/formbricks/node_modules/metro/src/Server.js:1085:5) {
  mockPath1: '../../package.json',
  mockPath2: '../web/.next/standalone/package.json'
}
```

Please let me know if I'm doing something wrong here. :)

**Comment by neo773** [comment]
@ShubhamPalriwala 
Hi, pushed a new commit that fixes this could you try again?
Also could you run `pnpm clean` first? that should help if it's some cache issue.

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey, just tested it again and this time it did not throw any errors on startup!
```sh
> expo start

Starting project at /home/shubham/Desktop/formbricks/apps/react-native
Starting Metro Bundler
Some dependencies are incompatible with the installed expo version:
  react-native-get-random-values@1.10.0 - expected version: ~1.9.0
  react-native-webview@13.6.3 - expected version: 13.2.2
  @expo/webpack-config@18.1.3 - expected version: ^19.0.0
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▀▄█▀ ██  █ ▄▄▄▄▄ █
█ █   █ █▄   ▄█▄▄██ █   █ █
█ █▄▄▄█ █ ▀█▀█▀▀ ▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ ▀▄█ █ ▀ █▄▄▄▄▄▄▄█
█▄ █▄█▀▄▄██ ▀█ ▀▄█▀  ▄▀▄▄▀█
█▄██▄ ▄▄▄▀▄▄██  ██▄▀ ▀▀█▄▄█
█▄▄▄▀▀ ▄ ▄█▀▀   █▀█ ▄█ ██▀█
█▄▀▀█▄ ▄█▄█▀█  ██ ▄▄ ▀▀██▄█
█▄▄██▄▄▄▄▀██▄▄█▄  ▄▄▄ █ ▄ █
█ ▄▄▄▄▄ █▄ ▀▀██▄  █▄█  ▀▄▄█
█ █   █ █▀██▄█ ▀▀▄ ▄▄ █▀▄██
█ █▄▄▄█ █▀█▀█▄  █  █▄  ▄█▄█
█▄▄▄▄▄▄▄█▄▄▄▄█▄▄█▄███▄▄█▄▄█

› Metro waiting on exp://192.168.29.190:8081
› Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

› Using Expo Go
› Press s │ switch to development build

› Press a │ open Android
› Press w │ open web

› Press j │ open debugger
› Press r │ reload app
› Press m │ toggle menu
› Press o │ open project code in your editor

› Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on Android...
Failed to resolve the Android SDK path. Default install location not found: /home/shubham/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Failed to resolve the Android SDK path. Default install location not found: /home/shubham/Android/sdk. Use ANDROID_HOME to set the Android SDK location.
Error: spawn adb ENOENT

```

However, on clicking `a` to get android, I get the error above!

**Comment by neo773** [comment]
@ShubhamPalriwala 
You'll need to set up the dev environment for Android.
https://reactnative.dev/docs/environment-setup

**Comment by ShubhamPalriwala** [comment]
Hey, apologies for the delay. Happy new year 🎆 I just setup Expo on my mobile device and was able to interact with the app! I updated the `surveyId` as well as you mentioned. However, on clicking the "Show Survey", I get the below logs:
```sh
 WARN  Encountered an error loading page {"canGoBack": false, "canGoForward": false, "code": -1004, "description": "Could not connect to the server.", "didFailProvisionalNavigation": true, "domain": "NSURLErrorDomain", "loading": false, "target": 37, "title": "", "url": ""}
```
I can see the same on my mobile device as well!

**Comment by ShubhamPalriwala** [comment]
Apart from this, I would recommend you to take a look at the [JS package](https://github.com/formbricks/formbricks/tree/main/packages/js) and see how that works! For example, one fundamental difference in your package and the other packages that we have is that you use a `surveyId` to fetch the survey however we use the `environmentId` to fetch all the surveys using the sync endpoint and then find out which survey to show to the user based on their state!

Another drawback with how you render the surveys currently is using the URL ${BASE_URL}/s/${surveyId}?mobileapp=true  but that will not work for the in-app surveys which one might want to show. 

So please take a look once at the [surveys](https://github.com/formbricks/formbricks/tree/main/packages/surveys) & js package, understand it, and then see how we can modify the react native package to be as close as to that one for easier maintainability. Please do reach out here / or on our Discord if you get stuck anywhere!

**Comment by mattinannt** [comment]
@neo773 Thanks a lot for working on this and opening the PR for the React Native integration 💪. Since there are a lot of changes needed to make the functionality work as we need it for Formbricks, I will close the PR for now.

@neo773 @ShubhamPalriwala Since this seems to be more complex than we initially thought, also our Formbricks experienced core contributor @ty-kerr has offered to help with the React Native integration to make sure it works similar to the `@formbricks/js` integration.
Let's keep the discussion open and see what's the best way to move forward to get a fully functional Formbricks React Native integration.

**Pull request closed without merging**
