### PR TITLE
fix: Update docs link to point to the quickstart (3539)

### LINKED ISSUE #3539: [🕹️] Fix js integration docs link
### Issue Summary

Screenshot 2024-10-12 at 11 59 22

docs link is pointing to the nextjs docs instead the general docs.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

"docs" link should be pointing to the quickstart at https://formbricks.com/docs/app-surveys/quickstart

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by Asymtode712**
## What does this PR do?

This PR updates the "docs" link, which was previously pointing to the Next.js documentation, to now correctly point to the Quickstart guide at https://formbricks.com/docs/app-surveys/quickstart.

Fixes #3539 

## How should this be tested?

- Test A: Navigate to the section with the "docs" link and verify that it now directs to the correct Quickstart guide.

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [X] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [X] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [X] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Updated the documentation link for the "Javascript SDK" integration card to a new resource.
	- Moved the "Javascript SDK" integration card to the top of the list for improved visibility.

- **Bug Fixes**
	- Ensured the integration cards continue to function correctly with existing logic and user session checks.

### CODE REVIEW

**Comment by Asymtode712** [comment]
@mattinannt please review and merge this PR if it is good to go

**Review by mattinannt — APPROVED** [review]
@Asymtode712 thank you very much for fixing this 🚀

**Comment by Asymtode712** [comment]
@mattinannt please push it to the merge queue again

**Comment by Asymtode712** [comment]
@mattinannt please push it to the merge queue again

**Pull request merged**
