### PR TITLE
fix: buttons responsiveness fixed

### PR DESCRIPTION
**Pull request by ratishjain12**
## What does this PR do?
@jobenjada  I have fixed the issue #977 

I have made it properly now kindly merge :)

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @ratishjain12 thanks for the quick turnaround! 

You have worked a lot with absolute values, can you find a less rigid solution? :)

**Comment by ratishjain12** [comment]
> Hey @ratishjain12 thanks for the quick turnaround!
> 
> You have worked a lot with absolute values, can you find a less rigid solution? :)

can you elaborate on this?

**Comment by jobenjada** [comment]
This PR fixed it: https://github.com/formbricks/formbricks/pull/998

For it to be fair, I will add points to you for flagging it and to him for solving it :) 🚀

**Comment by ratishjain12** [comment]
> This PR fixed it: https://github.com/formbricks/formbricks/pull/998
> 
> For it to be fair, I will add points to you for flagging it and to him for solving it :) 🚀 

Hey I saw the fix he removed/ made the github logo hidden to make it responsive just to make sure

**Pull request closed without merging**
