### PR TITLE
feat: add 4 new survey templates

### PR DESCRIPTION
**Pull request by jonas-hoebenreich**
## What does this PR do?

This PR template adds 4 new survey templates targeting 4 main areas in HR. The questions in this template have been inspired by [Peakon Employee Voice](https://www.workday.com/en-us/products/employee-voice/overview.html)

One question: these templates are currently set to role: productManager. What do you think about adding the role People Manager?
And just my personal opinion: I would completely remove industries. I think they don't solve any real issue, are not easy to understand for the typical user and reducing the onboarding by one step probably increases CVR.

Fixes # (issue)

## How should this be tested?

- check out new survey templates
image

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Added five new survey templates: Long Term Retention Check-In, Professional Development Growth, Recognition and Reward, Alignment and Engagement, and Supportive Work Culture.
	- Expanded the Employee Well-Being template to include additional industries: SaaS, eCommerce, and Other.
	- Introduced support for the "People Manager" role in various components and styling options.
- **Improvements**
	- Enhanced existing templates to better assess various aspects of employee engagement, satisfaction, and alignment with company values.

### CODE REVIEW

**Comment by jobenjada** [comment]
I like the idea of adding "People Manager" :) wanna implement that and add the other two HR templates?

we'll keep the industries for now 🤓 but i do see your point!

**Comment by jonas-hoebenreich** [comment]
@jobenjada, sure I can add "People Manager". Do you want me to add this to the on boarding as well?

**Comment by jonas-hoebenreich** [comment]
@jobenjada 
I've added the role :)

image

**Review by jobenjada — APPROVED** [review]
very cool, thanks :)

**Pull request merged**
