### PR TITLE
feat: Add user agent to response meta

### LINKED ISSUE #386: [FEATURE] Add user agent data to in-app responses
**Is your feature request related to a problem? Please describe.**
I have no idea on which device my respondents reply to **in-app surveys**.

**Describe the solution you'd like**
Store and display the user agent along with the response.

**Tasks**
- Request userAgent when a survey is triggered via the Formbricks Widget. Write the userAgent data into the `meta` object in the response model (the meta object already exists in the Prisma schema)
- Type the meta object correctly with ZOD in packages/types/v1/responses
- Display the meta data in the response overview when hovering over the Avatar using the [Tooltip](https://ui.shadcn.com/docs/components/tooltip) in packages/ui. Make use of [UAParser.js](https://www.npmjs.com/package/ua-parser-js)

grafik

## How to code for Formbricks
1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #386

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey G3root!

Thanks a lot for your contribution 🙌  Here is my feedback:

1. Your PR has a merge conflict, please run `git pull origin main`
2. Only display the tooltip if there is User Data to be displayed in it:
grafik
3. I am missing Device type in the tooltip:
grafik

Please update the PR accordingly.

Thanks! 🙏

**Comment by G3root** [comment]
@jobenjada pushed some changes

- [x] fixed the merge conflict
- [x] fixed displaying of tooltip when there isn't data
- [x] looks like Desktop/Laptops doesn't have indications telling what device they are on https://github.com/faisalman/ua-parser-js/issues/182#issuecomment-263115448, so added the text `PC / Generic device` as a fallback

**Comment by jobenjada** [comment]
hey!

Thanks for the fallback solution, makes sense :)

Im getting "device" twice on mobile (I emulated an iPhone with Chrome Dev Tools):
grafik

Other than that, it works well - thanks 🙌

**Comment by G3root** [comment]
> hey!
> 
> Thanks for the fallback solution, makes sense :)
> 
> Im getting "device" twice on mobile (I emulated an iPhone with Chrome Dev Tools): grafik
> 
> Other than that, it works well - thanks raised_hands

sorry for the mistake, as it resulted from an additional line of code that I inadvertently overlooked. pushed some code for the fix

**Pull request merged**
