### PR TITLE
fix: toast Message while creating the survey

### LINKED ISSUE #3204: [🕹️] Duplicate Toasts on Publish Survey
### Issue Summary

Almost all the times when publishing a survey we see the success toast twice.

Investigate why, don't just treat the symptom with a hack 😉

### Steps to Reproduce

1. Create a new survey, publish it
2. Check the toast messages bottom left

### Expected behavior

Only show once.

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by smritidoneria**
## What does this PR do?

This pr fixes the duplication of the toast message after creating the survey.

Fixes  #3204

https://github.com/user-attachments/assets/35a3078a-22ff-432b-a7bd-342640b9c23e

## How should this be tested?

- Test A.
1. Create a new Survey
2.Publish it.
- Test B

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced the success message display to prevent multiple notifications for successful survey submissions.
	- Added a new toast notification identifier for better management of success notifications.

- **Bug Fixes**
	- Improved logic to ensure toast notifications and confetti are triggered only once per submission.

### CODE REVIEW

**Comment by jobenjada** [comment]
hey @smritidoneria your solution doesn't solve the problem but the symptom. Please find out why the Toast is issued twice (probably related to the component being rendered twice).

Consult with GPT to find out why and learn more on how React works 🤓

**Comment by smritidoneria** [comment]
Hey @jobenjada ,this issue is likely to occur due to the due to use effect hook being triggered various times due to its dependency array change, causing it to re-run. Specifically searchPrams is causing this effect to re-run.


So the solution of this problem is to use useRef hook. The  useRef hook allows you to persist a mutable value across renders without causing a re-render when the value changes. This will be  useful for keeping track of whether the toast message has already been shown.( this pr uses this solution only)

**Comment by gupta-piyush19** [comment]
@smritidoneria, you can try adding a unique ID to this toast. This should fix the issue without using ref https://arc.net/l/quote/pyoztdxy

**Comment by smritidoneria** [comment]
Hey @gupta-piyush19 , Updated the code by adding a toastId. kindly have a look

**Review by gupta-piyush19 — APPROVED** [review]
Thanks @smritidoneria, fix works great 🙌 
LGTM 🚀

**Comment by smritidoneria** [comment]
hey @gupta-piyush19 , can you please tell why this pr has been removed from merged Queue, are there any changes required?

**Pull request merged**
