### PR TITLE
fix: overflowing CodeBlock in "Share or embed your survey" modal 

### PR DESCRIPTION
**Pull request by mandharet**
## What does this PR do?

This PR fixes issue related to  overflowing CodeBlock in "Share or embed your survey" modal mentioned in https://github.com/formbricks/formbricks/issues/1403

Fixes [# (issue)](https://github.com/formbricks/formbricks/issues/1403)

image
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

1. Make an in-app survey with multiple questions
    try to upload images as image URL's are huge to fit in CodeBlock's normal width
2. Save Form and click on Share or Publish
3. Will open "Share or embed your survey" modal
4. Click on Embed in an Email tab
5. then click on View Embed Code tab
6. try to pay around with displayed codeblock and try to scroll

Entire Code should be visible and readable from CodeBlock with simple scroll operation if needed

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mandharet** [comment]
Yes, The changes in this PR focused on improving the scrolling behavior for Share or embed your survey modal 😅

**Comment by mandharet** [comment]
Tested with Chrome DevTools for different screen sizes and LGTM 😎

Hi Reviewers, I am new to this tech stack React, next, tailwind and more.
Looking forward to learn more.

**Comment by gupta-piyush19** [comment]
Hey! While making any changes in the embed survey modal, do verify its functionality on smaller screens as well.

**Comment by mandharet** [comment]
Hi @gupta-piyush19 ,
As I have already mentioned, I have tested with chrome devtools for smaller screens as well.
Have you found any styling issue on smaller screens ?
Let me know, I'll try to fix it.

**Comment by gupta-piyush19** [comment]
Naah, just commented as a disclaimer, If you've tested then it's fine.

**Comment by mandharet** [comment]
I have tried with 1080P monitor with 1080P resolution and 100% scaled on windows 11 (edge).
image


I was able to replicate same issue.
image

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey, thanks a lot for the quick fix! I tested and it looks good to me! One enhancement that I'd like is if we can also make the horizontal scrollbar not visible everytime and only when needed (if there's a case for this).

image


Once this is fixed, we should hopefully be gtg 🚀

**Comment by mandharet** [comment]
Hi @ShubhamPalriwala, I can continue to work on this early tomorrow. Apologies for the delay.
Thank you for the review.

**Comment by mandharet** [comment]
Hi @ShubhamPalriwala,
I have already got rid of mandatory scrollbars, as it will only show the scrollbar when necessary.
Please, refer first screenshot from here https://github.com/formbricks/formbricks/pull/1404#issue-1955893856

**Comment by ShubhamPalriwala** [comment]
It's weird that its visible for me! Can you see if you can reproduce it and if then fix it?

**Comment by mattinannt** [comment]
@mandharet I have the same issue as shubham, at least when the screen gets bigger.
I'm also not able to reproduce the issue in the current main branch. That's how my sharing code looks like on Formbricks Cloud: 
Screenshot 2023-10-23 at 16 29 02
(everything fine as far as I can see)

**Comment by mandharet** [comment]
Hi @mattinannt, Please try to add image in welcome card

**Comment by jobenjada** [comment]
Closing this for two reasons:

1. I'm getting an error with the email preview on prod: 

https://tella.video/johanness-video-65ku

This has priority.

2. Secondly, the solution should not be embedding the Welcome Card in an email, which doesn't make a lot of sense imo. Instead, we should embed the first question in the Preview, to optimize the response rate.

Thanks for your effort!

You will get the 50 points anyways because you went through the effort of solving it 🙏

**Pull request closed without merging**
