### PR TITLE
feat: add airtable integration

### LINKED ISSUE #888: [FormTribe 🔥][500 Points] Integration: Airtable
### Welcome to the FormTribe

This issue will get you **500 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

### Is your feature request related to a problem? Please describe.

Users want to send submission data directly to Airtable instead of going via Zapier etc. Privacy-focussed users want to keep the number of companies touching their data to a minimum.

### Describe the solution you'd like

Build native Airtable integration using OAuth.

### Notes

- We have a Google Sheets integration which can be copied and adapted.
- Here are [Sheets integration docs](https://formbricks.com/docs/integrations/google-sheets)

#### Tasks

- Develop a direct Airtable Integration which has all the capabilities the Google Sheets integration has
- Make sure to add the needed env variables etc. for self-hosters to be able to use it

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #888

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [ ] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
@G3root thanks for opening the draft PR!

What are the steps for you to complete to get this ready for review?

**Comment by G3root** [comment]
@jobenjada now it's ready for review

**Comment by Dhruwang** [comment]
Looks great 💪😊
Can you check your discord?

**Comment by jobenjada** [comment]
Hey @G3root 

Thanks for the integration, it looks pretty good! 🙏

I pushed some UI changes (replacing logo, update wording , etc)

In AddIntegrationModal.tsx I'm getting the following error twice:

image
image


Secondly, the Modal isn't working properly:

https://tella.video/johanness-video-79b2

There are two issues related:

- The modal closes if dropdown is empty
- I have an Airbase table in my account but it is not being loaded when the modal is opened. Similar to the Google Sheets integration, it should fetch all available tables when the AddAirtableIntegrationModal is opening.

Once you've fixed this, I'll be able to test the integration end-to-end.

Thanks a lot! 🚀

**Comment by Dhruwang** [comment]
@G3root Works great 😊💪

**Comment by G3root** [comment]
> @G3root Works great 😊💪

looks like it needs some more work. The OAuth "access token" provided by Airtable remains valid for only 60 minutes, while the "refresh token" from Airtable has a validity of only 60 days. If the "access token" expires, obtaining a new token is possible. However, if the "refresh token" expires, we must take action to revoke the integration. To achieve this, we may require an additional table dedicated solely to storing tokens, such as a "Credential" table, which we can revoke easily.

@Dhruwang @jobenjada  any suggestions would be helpful 🙏🏼

**Comment by jobenjada** [comment]
@mattinannt please perform a final review an merge :)

**Comment by mattinannt** [comment]
@G3root Thanks a lot for the PR 😊🙏 It's nearly ready to merge from my side. 
Why do we need the `AIR_TABLE_REDIRECT_URL` environment variable? Isn't this something that is always the same (of course depending on the WEBAPP_URL of the instance) but is fix due to the airtable api design in Formbricks?
What's the expected value for the `AIR_TABLE_REDIRECT_URL`?

**Comment by G3root** [comment]
> @G3root Thanks a lot for the PR 😊🙏 It's nearly ready to merge from my side. Why do we need the `AIR_TABLE_REDIRECT_URL` environment variable? Isn't this something that is always the same (of course depending on the WEBAPP_URL of the instance) but is fix due to the airtable api design in Formbricks? What's the expected value for the `AIR_TABLE_REDIRECT_URL`?

expected value for the `AIR_TABLE_REDIRECT_URL` should match the redirect URL provided during the OAuth application's creation. yeah the value should be same depending on the `WEBAPP_URL` of the instance

**Comment by mattinannt** [comment]
> > @G3root Thanks a lot for the PR 😊🙏 It's nearly ready to merge from my side. Why do we need the `AIR_TABLE_REDIRECT_URL` environment variable? Isn't this something that is always the same (of course depending on the WEBAPP_URL of the instance) but is fix due to the airtable api design in Formbricks? What's the expected value for the `AIR_TABLE_REDIRECT_URL`?
> 
> expected value for the `AIR_TABLE_REDIRECT_URL` should match the redirect URL provided during the OAuth application's creation. yeah the value should be same depending on the `WEBAPP_URL` of the instance

Thanks. So the url should redirect to the airtable/callback api endpoint you provided?

**Pull request merged**
