### PR TITLE
fix: docker compose upload volume mapping

### PR DESCRIPTION
**Pull request by Candinya**
## What does this PR do?

Docker upload volume is now in `/home/nextjs/apps/web/uploads/`

image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Start a docker compose project, upload a file and see where is it (in the container). It's in `/home/nextjs/apps/web/uploads/`

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey, thanks for the PR! This works because we have set the working directory base as `/home/nextjs`: https://github.com/formbricks/formbricks/blob/main/apps/web/Dockerfile#L51

However, is image upload not working for you? I'm trying to understand what this fixes 😅

**Comment by Candinya** [comment]
> Hey, thanks for the PR! This works because we have set the working directory base as `/home/nextjs`: https://github.com/formbricks/formbricks/blob/main/apps/web/Dockerfile#L51
> 
> However, is image upload not working for you? I'm trying to understand what this fixes 😅

The image upload works (although nextjs' image proxy is not working correctly in our production server with error `"url" parameter is not allowed`, it's not about this PR), but it's a volume mapping issue, the old volume is mapped to a not exist path, and the real upload path under `/home/nextjs` is not exposed, thus the images will get lost when docker container recreates.

A simple proof is to start a local server, upload an image, and recreate it with `docker compose up formbricks -d --force-recreate`, then the image just disappeared.

**Comment by ShubhamPalriwala** [comment]
Ahh. that makes sense, let me just reproduce the case you've mentioned (out of curiosity), and then get back to you 😎 
Thanks again

**Comment by Candinya** [comment]
However I just found a directory permission bug about this fixed mapping... I'm not sure if it's just on my device (Windows) or is a common problem, that when upload path has been mapped out, it seems like the container user `nextjs` don't have enough permission to write to that directory.

This could be fix manually by `docker compose exec --user root formbricks chown -R nextjs:nogroup /home/nextjs/apps/web/uploads/` to correct the directory permission, but I'm not sure if there's any other elegant ways to fix this (maybe use an entrypoint shell script? but I'm not sure which user will run it.)

**Comment by ShubhamPalriwala** [comment]
Hey, I just tested as per the steps you provided and for me:
- The old mappings work as expected
- The new mapping does not even allow me upload an image in the first place.

Which confirms the bug the you are also facing! Please see if you can fix that as well in a declarative way ie prolly playing around with our Dockerfile [here](https://github.com/formbricks/formbricks/blob/main/apps/web/Dockerfile)

**Comment by Candinya** [comment]
I think the latest commit fixed this proplem, let's have a look 👀

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey, just tested:
1. Upload an image (works)
2. View it (works)
3. Stop & Recreate the image
4. View the previously uploaded image (does **not** work)
```sh
 ⨯ upstream image response failed for http://localhost:3000/storage/clqm9i5y7000aswviybqdkvf7/public/Group%2015.png 404
```


Can you test this flow and 
1. reproduce this
2. see where this is going wrong

Thanks 🤞🏼

**Comment by Candinya** [comment]
> reproduce this

Actually not reproduced here... We are testting the locally built image with exposed volume, right?

<details>
<summary>The patch I'm using for the <code>docker-compose.yml</code> in repository root: </summary>

```patch
diff --git a/docker-compose.yml b/docker-compose.yml
index cccde14b..9d222cbd 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -118,6 +118,10 @@ services:
       GOOGLE_CLIENT_SECRET: *google_client_secret
       CRON_SECRET: *cron_secret

+    volumes:
+      - uploads:/home/nextjs/apps/web/uploads/
+
 volumes:
   postgres:
     driver: local
+  uploads:
```

</details>

**Comment by Candinya** [comment]
> The patch I'm using for the docker-compose.yml in repository root

I've committed this patch, may this can help

**Review by ShubhamPalriwala — APPROVED** [review]
Aye, apologies for the delay in the review! Happy new Year 🎆 

Just tested the flow and it works smoothly now without any bugs/errors that were being encountered before! Great work 🚀

**Pull request merged**
