### PR TITLE
[WIP] Feat: Add one click gitpod setup

### LINKED ISSUE #509: [FEATURE] GitPod One Click Setup
**Is your feature request related to a problem? Please describe.**
Running Formbricks on GitPod is not working out of the box:

grafik

**Describe the solution you'd like**
As a developer I'd love to use GitPod to run Formbricks with one click.

**Additional context**
Ideally, it also works for GitHub Code Spaces :)

### PR DESCRIPTION
**Pull request by Ashutosh-Bhadauriya**
## What does this PR do?

Fixes #509 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [ ] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by Ashutosh-Bhadauriya** [comment]
@Palanikannan1437 so this is the issue I'm facing right now

I'm encountering an issue related to the database. I suspect the problem might be associated with the port selection. Presently, I've set port 5432 for the database (in gitpod.yml) as it's the designated port for its operation. However, I'm uncertain as to what's causing the problem.

Screenshot (4)

**Comment by Ashutosh-Bhadauriya** [comment]
Just tried it manually on gitpod, this error is also coming if we run all the commands manually. @jobenjada can you please take a look at it, when you get a chance? cc: @Palanikannan1437

It comes when running `pnpm go` command

Screenshot (54)

**Comment by Palanikannan1437** [comment]
> @Palanikannan1437 I'm encountering an issue related to the database. I suspect the problem might be associated with the port selection. 

Ahh, I just went through the monorepo and figured out the problem, it's not a very trivial one (but after tinkering with monorepos for months you learn a thing or two :p)

So the issue is with "./dist/index.js" not being generated at the start of the setup as we've not run either "tsup --watch" or "tsup build" with the "pnpm go" script, HENCE essentially "dist" folder not being built and hence the app isn't able to find the "@formbricks/database".

The solution could be very straightforward....

Specific to Gitpod: We run "pnpm run dev" command for each of package to build it and then via "gp sync" we can start the nextjs dev server so that it runs without errors...

General solution: We can add a build step i.e. running tsup (just for packages) in the pnpm "go" scripts....

PS: It doesn't have to do with the db container's ports being exposed or not...

**Comment by mattinannt** [comment]
> > @Palanikannan1437 I'm encountering an issue related to the database. I suspect the problem might be associated with the port selection.
> 
> Ahh, I just went through the monorepo and figured out the problem, it's not a very trivial one (but after tinkering with monorepos for months you learn a thing or two :p)
> 
> So the issue is with `./dist/index.js` not being generated at the start of the setup as we've not run either `tsup --watch` or `tsup` to build the monorepo packages with the `pnpm "go"` script, HENCE essentially **dist** folder is not being built and hence the app isn't able to find the "@formbricks/database".
> 
> The solution should be pretty straightforward....
> 
> 1. **Specific to Gitpod**: We run "pnpm run dev" command for each of package to build it and then via "gp sync" we can start the nextjs dev server so that it runs without errors...
> 2. **General solution**: We can add a build step i.e. running tsup (just for packages) in the pnpm "go" scripts....
> 
> PS: It doesn't have to do with the db container's ports being exposed or not...

The `pnpm go` command is pretty new in our setup (just introduced it last week). I think it's the best approach to update the `go` script in the package.json of `packages/database`, e.g.
```
"go": "pnpm db:setup && tsup --watch",
```

**Comment by mattinannt** [comment]
> > > @Palanikannan1437 I'm encountering an issue related to the database. I suspect the problem might be associated with the port selection.
> > 
> > 
> > Ahh, I just went through the monorepo and figured out the problem, it's not a very trivial one (but after tinkering with monorepos for months you learn a thing or two :p)
> > So the issue is with `./dist/index.js` not being generated at the start of the setup as we've not run either `tsup --watch` or `tsup` to build the monorepo packages with the `pnpm "go"` script, HENCE essentially **dist** folder is not being built and hence the app isn't able to find the "@formbricks/database".
> > The solution should be pretty straightforward....
> > 
> > 1. **Specific to Gitpod**: We run "pnpm run dev" command for each of package to build it and then via "gp sync" we can start the nextjs dev server so that it runs without errors...
> > 2. **General solution**: We can add a build step i.e. running tsup (just for packages) in the pnpm "go" scripts....
> > 
> > PS: It doesn't have to do with the db container's ports being exposed or not...
> 
> The `pnpm go` command is pretty new in our setup (just introduced it last week). I think it's the best approach to update the `go` script in the package.json of `packages/database`, e.g.
> 
> ```
> "go": "pnpm db:setup && tsup --watch",
> ```
> 
> We just needs to check if this also works with the turborepo script dependency (`go` in `apps/web` is executed as soon as `go` in `packages/database` is finished)

@Ashutosh-Bhadauriya Ok, it seems when we change it like this, that the `apps/web` package isn't starting correctly because it waits for the database package to complete (and it will never complete).
As a temporary workaround we can change the command to
```
"go": "pnpm db:setup && tsup",
```
And I will see to get a better fix for the go command that enables changes to the database in dev mode be reflected in other parts of the monorepo.

**Comment by Ashutosh-Bhadauriya** [comment]
@mattinannt @Palanikannan1437 I tried updating the go script as suggested `"go": "pnpm db:setup && tsup"` but it's causing the script to hang and not proceed further.

**Comment by Palanikannan1437** [comment]
> (`go` in `apps/web` is executed as soon as `go` in `packages/database` is finished)

Hey @mattinannt, this would be possible to do in Gitpod for sure, but for local dev environments we'd have to specify it in the docs. Will get back to you after some further experimentation...

**Comment by mattinannt** [comment]
@Ashutosh-Bhadauriya @Palanikannan1437 I just updated the `pnpm go` flow in the main branch ( https://github.com/formbricks/formbricks/commit/2199a4b1029d99113331ada0cc4250fa6ec81dea ). It now uses turborepo to make sure, that everything is build before starting the dev server. Unfortunately this takes some time due to the long building time of `formbricks-js`. But I will solve this in a separate PR.
Additionally I removed the need to build the database package and import the typescript sources directly in formbricks-app.
Please give it a try with Gitpod :-) 

Is there something else missing for the gitpod setup?

**Comment by Palanikannan1437** [comment]
> Unfortunately this takes some time due to the long building time of formbricks-js

Hey @mattinannt, this is awesome, no issues at all now! This long build step can be kind off "hidden" with prebuilds in gitpod...

https://www.gitpod.io/docs/configure/projects/prebuilds

**Comment by Ashutosh-Bhadauriya** [comment]
@mattinannt this built issue is still there, btw I'm also facing this locally

Screenshot (57)

**Comment by mattinannt** [comment]
@Ashutosh-Bhadauriya @Palanikannan1437 How is the Gitpod integration progressing? Are there still changes that need to be made, or can we start with the current version of `.gitpod.yml`?

**Comment by Palanikannan1437** [comment]
> @Ashutosh-Bhadauriya @Palanikannan1437 How is the Gitpod integration progressing? Are there still changes that need to be made, or can we start with the current version of `.gitpod.yml`?

Hey @mattinannt, I'm almost done with it, just some minor things have to be fixed, (got a bit occupied with some work...was thinking of making the final changes over the weekend)

You can see it here...

**Comment by mattinannt** [comment]
> > @Ashutosh-Bhadauriya @Palanikannan1437 How is the Gitpod integration progressing? Are there still changes that need to be made, or can we start with the current version of `.gitpod.yml`?
> 
> Hey @mattinannt, I'm almost done with it, just some minor things have to be fixed, (got a bit occupied with some work...was thinking of making the final changes over the weekend)
> 
> You can see it here, I should be able to complete and fix the scripts by this weekend (it has some bugs now)
> 
> (you can see the shell scripts I've written, it tries to automatically detect the pipeline and seperate build tasks and runtime tasks from turbo.json and installs necessary things to run in the prebuild automatically!)
> 
> [Palanikannan1437#1](https://github.com/Palanikannan1437/formbricks/pull/1)

Sounds great :-) I will take a look at the current script :-)
Looking forward to the finished PR 💪🤗

**Comment by mattinannt** [comment]
@Ashutosh-Bhadauriya @Palanikannan1437 As we have now successfully merged the new PR by @Palanikannan1437 I will close this PR. Thanks a lot for all your work making the Gitpod Integration possible 😊💪

**Pull request closed without merging**
