### PR TITLE
feat: improved UI for single select logic jumps

### PR DESCRIPTION
**Pull request by karishmashuklaa**
## What does this PR do?

This PR addresses UI issues in the Single Select Logic Jumps section of the Logic Editor on common laptop dimensions.
It includes improvements for better responsiveness and readability.

### Before

Screenshot 2023-12-11 233253

### After

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by karishmashuklaa — COMMENTED** [review]
The UI looks cleaner without the index numbers in questions. Please let me know if they were required by design

**Comment by mattinannt** [comment]
@karishmashuklaa Thanks a lot for the contribution 😊
I think if we tackle this, we should find a good approach for all the different logic combinations.
Can we find a solution where we always fill the full width with the configuration without much white space in between? also the chevron icon on the right of the dropdown isn't always visible.

Are you willing to give this a try?
We can always assign it to someone on the team.

Screenshot 2023-12-12 at 12 26 37

**Comment by karishmashuklaa** [comment]
@mattinannt You're right - thanks for the feedback! I'll work on it 😊

**Comment by karishmashuklaa** [comment]
All changes in #1773. Closing.

**Pull request closed without merging**
