### PR TITLE
fix: Data is not being sent webhook api on trigger (#1285)

### PR DESCRIPTION
**Pull request by rohan9896**
## What does this PR do?

This PR fixes the issue where the webhook triggered by survey form doesn't pass any request body in webhook call.

Fixes # (issue)
#1285

https://www.loom.com/share/68e9508ea459452199bca57ffc68aa21?sid=68677a2d-f9d6-4b0c-9482-59847f12289f

## Type of change
Fix

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
Hey @rohan9896, thanks for the PR! But I'm unable to reproduce the same! I tested the same in the current prod and it seems to work for me when tested via webhook.site:
image

Can you see if you can still reproduce this?  So can you tell me what body you're receiving from the webhook? And test the same on another webhook provider to understand if there's a parsing issue in your app or in our system for easier fixing?

**Comment by HananMehmood5** [comment]
When i was testing formbricks on local as well as on Prod, I tested the webhook via both local and ngrok url. Body was empty for me in the post request api url which i have passed there on the webhook.

**Comment by rohan9896** [comment]
Hey @ShubhamPalriwala @HananMehmood5 

So, according to me, the issue was the request body was of type text, which was getting parsed as json.

How i debugged - 
I am using express framework for creating POST API that I have created which will be triggered by webhook. So, when I added the middleware `app.use(bodyParser.text());`, I was able to see the data in the request body of my POST api. But, when i changed it to `app.use(bodyParser.json());` (which i think most people do while creating an api), it was giving empty data in the request.
That's why I added header `"content-type": "application/json"` in the headers body.

**Review by ShubhamPalriwala — APPROVED** [review]
Ahh okay! That makes sense! Thanks for the PR! LGTM 🚀

**Pull request merged**
