### PR TITLE
fix: button size in all modals to size "sm"

### LINKED ISSUE #3796: [🕹️] Change the button size in all modals to size "sm"
### Is your feature request related to a problem? Please describe.

the buttons in the modals are very big

### Describe the solution you'd like

we want them in `size="sm"`

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Chirag8023**
## What does this PR do?

Fixes #3796 
Points: 300

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Updated the default size of the button from "base" to "sm," enhancing its visual presentation.

- **Bug Fixes**
	- Retained functionality for loading states, icon rendering, and tooltip integration without issues.

### CODE REVIEW

**Comment by Ayushkumarsinha123** [comment]
/assign
s

**Review by jobenjada — APPROVED** [review]
looks good :)

**Pull request merged**
