### PR TITLE
- Feature Enhancement : Edit and Resolve Notes

### PR DESCRIPTION
**Pull request by kuluruvineeth**
## What does this PR do?

[FEATURE] Edit and Resolve Notes #390

- [x] Make notes editable. On hover next to the actual note (in this case the text “That’s a note”) display a small pen icon. On click, the note is loaded back into the textarea for the user to update it. The Button text change to “Save” and saved.
- [ ]  once saved, little “ (edited) “ appears next to the note text in the same format like the date. ***Could i go ahead and make change for this too by adding additional column in responseNote model like *isEdited: boolean* and then make necessary changes.***
- [ ]  Need Clarification : Make notes resolveable. Next to the Minimize icon, add a checkmark icon. The icon will hide the note completely so that no notes indiciator is shown anymore. This is the notes indicator which should be hidden after resolve. ***On clicking on checkmark icon we will hide the note completely, but to reopen it where should we handle it i mean should we place icon next to delete icon or you have something in mind, Please lets discuss on this.***
- [x] Added a screen recording or screenshots to this     ####[PR]

https://github.com/formbricks/formbricks/assets/47528651/cbdac691-3660-41bc-94c9-b2a06ee6c0af

### CODE REVIEW

**Comment by kuluruvineeth** [comment]
@jobenjada, could we please discuss on these two points for more clarifications, so that i can go ahead and implement them too : 
 -[ ] once saved, little “ (edited) “ appears next to the note text in the same format like the date. Could i go ahead and make change for this too by adding additional column in responseNote model like isEdited: boolean and then make necessary changes.
- [ ] Need Clarification : Make notes resolveable. Next to the Minimize icon, add a checkmark icon. The icon will hide the note completely so that no notes indiciator is shown anymore. This is the notes indicator which should be hidden after resolve. On clicking on checkmark icon we will hide the note completely, but to reopen it where should we handle it i mean should we place icon next to delete icon or you have something in mind, Please lets discuss on this.

**Comment by jobenjada** [comment]
Hey @kuluruvineeth - thanks for picking this up! 😊 

When we tackle Multiplayer mode properly, there will be more design work preceeding this. We dont want to add fields to the model which we might have to remove change as this can cause compatibility issues down the line.

The edit functionality is a great edition, @mattinannt will check the code and get back to you or merge it.

Thanks a lot! 🙌

**Comment by mattinannt** [comment]
@kuluruvineeth Thanks a lot for the PR 😊
We are currently in the transformation to using React Server Components and Server Action. For this we are building services that handle the data management in `/packages/lib/services` and then call them in the server components for data fetching or server actions for mutating data.
We haven't moved the Response Notes mutations to server actions yet, but when now the functionality should be expanded I would strongly prefer to have it as server actions instead of extending a deprecated approach. For server actions please see for example our person detail page which has an action to delete a person [`apps/web/app/(app)/environments/[environmentId]/people/[personId]/actions.ts`.](https://github.com/formbricks/formbricks/blob/main/apps/web/app/(app)/environments/%5BenvironmentId%5D/people/%5BpersonId%5D/actions.ts)
Also currently you allow the notes to be edited by everyone and don't check if it's the same user who created it. We shouldn't allow this 😊
Is it possible for you to make the requested changes? 😊

**Comment by kuluruvineeth** [comment]
> @kuluruvineeth Thanks a lot for the PR 😊 We are currently in the transformation to using React Server Components and Server Action. For this we are building services that handle the data management in `/packages/lib/services` and then call them in the server components for data fetching or server actions for mutating data. We haven't moved the Response Notes mutations to server actions yet, but when now the functionality should be expanded I would strongly prefer to have it as server actions instead of extending a deprecated approach. For server actions please see for example our person detail page which has an action to delete a person [`apps/web/app/(app)/environments/[environmentId]/people/[personId]/actions.ts`.](https://github.com/formbricks/formbricks/blob/main/apps/web/app/(app)/environments/%5BenvironmentId%5D/people/%5BpersonId%5D/actions.ts) Also currently you allow the notes to be edited by everyone and don't check if it's the same user who created it. We shouldn't allow this 😊 Is it possible for you to make the requested changes? 😊

sure on it

**Comment by kuluruvineeth** [comment]
@mattinannt i have made changes as suggested by you, moved code to server actions approach and now only the user who has created note would be able to update that note.

https://github.com/formbricks/formbricks/assets/47528651/341d9d60-ee56-4cb6-9e7c-635a72e90b2c

**Review by mattinannt — APPROVED** [review]
@kuluruvineeth thanks a lot for making the changes 💪🙏 Feature looks great and improves the notes functionality a lot 🚀 Thanks you for the contribution 😊
Sorry for taking so long with the final review. I will merge the feature now into main 😊

**Pull request merged**
