### PR TITLE
feat: add LoadingSpinner component to storybook component

### PR DESCRIPTION
**Pull request by Saurabhchaddha6**
## What does this PR do?

Adds LoadingSpinner component to the storybook

Fixes #(issue)
#2895

Fixes # (issue)
[Screencast from 21-07-24 04:31:47 PM IST.webm](https://github.com/user-attachments/assets/0af7921c-2063-4a0b-bdae-fcdd38fbd56d)

## How should this be tested?

-Run Storybook using `pnpm storybook`

    Inspect Storybook on `http://localhost:6006/`

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by gupta-piyush19** [comment]
Hi, @Saurabhchaddha6. Thanks for the changes, but the storybook feature seems to be working incorrectly. Can you please fix it?
This component is fairly simple and doesn't have variants/props.
Please let me know if you need any help. 😊

**Review by gupta-piyush19 — CHANGES_REQUESTED** [review]
Please fix the storybook component

**Comment by Saurabhchaddha6** [comment]
Please check the changes now

**Review by mattinannt — APPROVED** [review]
@Saurabhchaddha6 thank you for the PR 🚀💪

**Pull request merged**
