### PR TITLE
Fixing the Button's Color Issue in Concierge Service Page

### PR DESCRIPTION
**Pull request by Srijan-Baniyal**
## What does this PR do?

Color of the Button was Fixed. 

Issue : - 

#1139 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Just by normal dev setup or the Vercel preview 

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by Srijan-Baniyal** [comment]
#1139

**Comment by ratishjain12** [comment]
@Srijan-Baniyal atleast get assigned to the issue first then only send the PR

**Comment by Srijan-Baniyal** [comment]
Well . I'll make sure next time this won't happen.

**Comment by Srijan-Baniyal** [comment]
@mattinannt sir , Please review My PR

**Comment by Srijan-Baniyal** [comment]
#1139

**Comment by jobenjada** [comment]
solved already, thanks :)

**Pull request closed without merging**
