### PR TITLE
feat: standardize menu ui

### LINKED ISSUE #3214: [🕹️] Unify all context menus UI
### Is your feature request related to a problem? Please describe.

Our contact menus look slightly different throughout the app:

image

The differ in: 
- font
- strokeWidth of icons
- roundeness
- border
- border color
- shadow

### Describe the solution you'd like

The should alllll look the same!

Like this:
image

### Attention
When you refactor, please make sure that you follow the DRY principle. Don't add the same CSS to all instances of the dropdown. Instead, style the base Radix component correctly and remove all overwriting CSS 💪 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devcodes9**
## What does this PR do?

Fixes #3214 

## How should this be tested?
- Check all the dropdown menu app-wide

### Required

- [x] Filled out the "How to test" section in this PR
- [x]  Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

image
image
image
image
image
image

## Open Questions 
@jobenjada 
- w-56 static height was given to dropdown's css for the expected dropdown image attached in the issue. I have removed that to take width dynamically based on content. Do we want it to be static app-wide?
- Do we need hover:ring-0 experience on DropdownItem? (found it's repititive implementation at places)
- Is there a need to also update DropdownSelector UI component?

## Summary by CodeRabbit

- **New Features**
	- Introduced an icon prop for DropdownMenuItem components, enhancing visual representation of actions.
	- Updated dropdown menu items to allow selection of predefined date ranges and improved response downloading options.
	- Enhanced the HiddenFieldsCard component with user notifications for actions related to hidden fields.

- **Bug Fixes**
	- Improved user feedback with toast notifications for actions related to hidden fields.

- **Refactor**
	- Simplified the DropdownMenu component's prop handling for improved maintainability and readability.
	- Streamlined onClick handlers and logic for DropdownMenuItem components, enhancing clarity and performance.
	- Enhanced user interaction flow for creating surveys with better handling of question types and logic.

These changes enhance the overall user experience and clarity of the DropdownMenu component while maintaining existing functionalities.

### CODE REVIEW

**Comment by jobenjada** [comment]
hey :) thanks so far, by when do you plan on wrapping this up? 🤓

**Comment by devcodes9** [comment]
> hey :) thanks so far, by when do you plan on wrapping this up? 🤓

Would it be okay if I wrap this up by end of this week?

**Comment by devcodes9** [comment]
@jobenjada Please do review

**Review by jobenjada — APPROVED** [review]
good work, tweaked it a bit :) LGTM!

**Pull request merged**
