### PR TITLE
fix: initial fix for mail logger

### LINKED ISSUE #2767: [FEATURE] Option to Disable Mail
### Is your feature request related to a problem? Please describe.

We do not have Mail configured and do not wish to configure it as we do not see the additional value. Currently, our logs are getting spammed with messages like: `Could not Email :: SMTP not configured :: [...]`
This clutter makes it harder to identify other important log messages.

### Describe the solution you'd like

Introduce a new environment variable, DISABLE_MAIL. When this variable is set:

- The notification settings related to email are disabled in the frontend.
- The application does not attempt to send emails.

Benefits:

- Cleaner logs without unnecessary error messages.
- A more user-friendly configuration for teams not using the mail feature.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by devsargam**
## What does this PR do?

- Prior this pr, the logs were filled with `Could not Email :: SMTP not configured :: [...]`
- Now, there are no logs when SMTP is not configured

Fixes #2767 

## How should this be tested?

- Create a new formbricks standbox without smtp configuration the server will not output any warnings/errors regarding the same.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by devsargam** [comment]
Hey guys, just ran `pnpm i` got this huge diff?

**Comment by devsargam** [comment]
Also, @mattinannt can you review this? and potentially propose some changes?

**Review by mattinannt — APPROVED** [review]
@devsargam Thanks for the fix; looks great!! 😊🚀

**Comment by jonas-hoebenreich** [comment]
I just had an idea: Formbricks could log a single message on server startup if SMTP is not configured. The message could be something like, "SMTP not configured. This instance will not send emails."

**Comment by mattinannt** [comment]
> I just had an idea: Formbricks could log a single message on server startup if SMTP is not configured. The message could be something like, "SMTP not configured. This instance will not send emails."

Sounds like a good idea :-) We will check how we can hook into the server startup without logging this for every function invocation in serverless environments.

**Pull request merged**
