### PR TITLE
[FEATURE] identify users in link surveys #384

### LINKED ISSUE #384: [FEATURE] Identify users in link surveys with URL parameter
**Is your feature request related to a problem? Please describe.**
As a user I cannot connect link survey responses to Persons in the Formbricks database. To be able to merge all feedback touch points, this is essential.

**Describe the solution you'd like**
Pass a user ID in the URL to connect a response with a person in the database. If there is not person existing with this user ID, create one.

**Note**

Users are called Persons in Formbricks.

Each Person has a unique Formbricks Id.

Each Person can have an attribute called User Id:

grafik

The user Id is the ID which the Formbricks users assign to their users in their applications. This external user ID is important to identify users across different apps e.g. when you want to send an email via [customer.io](http://customer.io) etc.

This feature deals with this external user ID which is passed to Formbricks via the URL parameter.

**Tasks**

1. Create a new API endpoint called “getOrCreate” under  /api/v1/client/environments/environmentId/people
    1. Pass the user ID from the URL parameter to it ( "?userId=ABC123" )
    2. The endpoint checks if a Person with this user ID exists:
        1. If person exists in db: get this Person
        2. If person does not exist: create new Person
    3. Return Person
2. Add the logic to LinkSurvey to check for “?userId=ABC123”
3. On page load, before the display gets created, send a request to the newly created endpoint and wait for the person to be sent back. Show loading spinner while waiting.
4. Use the internal Formbricks Id you got from the API to connect the response with the respondent
5. Show survey
6. Create display
7. Update the UI in the Responses tab to not display “Anonymous”  but the user ID which links to the User Detail Page:

grafik

## How to code for Formbricks

1. Make sure everything is type-safe
2. If you run `pnpm dev` you'll find a demo app to test in-app surveys at `localhost:3002`
3. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better). Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

### PR DESCRIPTION
**Pull request by Zorig**
## What does this PR do?

Connects link survey responses to **Person** in the Formbricks database.

Fixes #384 

https://github.com/formbricks/formbricks/assets/1277672/c288e038-862a-495a-a38d-4c7d28bdb677

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Create responses and then check the survey responses from `Responses` tab.

## Checklist

- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey Zorig!

Thanks a lot, the core functionality works well, good job 🙌 

There is one issue with the API being called too frequently, specifically everytime you click back onto the tab. This leads to the list of People to be filled even though only one Person responded:

grafik
grafik

The problem is that the userId in the URL param is not added to the newly created person:
grafik

This leads to more People being created.

Other than that it works great, thanks! 🙏

**Comment by jobenjada** [comment]
@Zorig Works well, thanks a lot :) 🙌 

@mattinannt Please do a code review

**Review by mattinannt — APPROVED** [review]
@Zorig thanks a lot for this feature PR 💪 Works great and code looks good 😊  🚀

I just made a few little improvements by relocating the client API endpoint to make it more consistent with the new client endpoints (removed the environment in the route) and I fixed an edge case where a user is created in preview mode.

I will merge the changes now 😊

**Comment by Zorig** [comment]
@mattinannt Thanks

**Pull request merged**
