### PR TITLE
feat: Introduce Dynamic Pixel Server for Seamless Self-Hosting

### PR DESCRIPTION
**Pull request by jonas-hoebenreich**
## What does this PR do?

For self-hosting users seeking an alternative to utilizing unpkg.com as a CDN for the Formbricks pixel, this pull request addresses the current manual effort required for URL changes within the pixel files. The proposed enhancement streamlines the updating process for such users, enabling them to effortlessly serve the latest version by incorporating the following script into their web pages:
`<script async="" defer="" src="https://example.com/api/js?environmentId={environmentId}"></script>`

This newly introduced endpoint facilitates automatic updates, delivering the JavaScript with the correct version. Additionally, it initializes Formbricks directly with the accurate host and environmentId, resulting in a more elegant and efficient script for seamlessly integrating Formbricks into web pages.

Please note that this pull request does not yet address the internal URLs within the script.
I would also classify this as an experimental feature that might still need redefining.

Fixes # (issue)

## How should this be tested?

- request /api/js?environmentId={environmentId}
- request /api/js?environmentId={environmentId}&format=iife
- request /api/js?module=question-date
- request /api/js?module=widget

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@jonas-hoebenreich Thanks for the PR 😊 This is a pretty cool approach 🚀
The script is now very specific to your use case for public websites and unidentified users, and would not work with the predefined init call if you have a `userId' or `attributes' set for that user when the init call is prebuilt. I would prefer if we make the `handleEnvironment` / init call append opt-in so that by default the init call is still required as for the unpkg version.

**Comment by jonas-hoebenreich** [comment]
Yeah true, `handleEnvironment` should probably be called `handleInit` and accept the following searchParams
- `environmentId` (do not init when not set/unknown environment -> traditional init required)
- `debug` true/false
environmentId is actually already optional, so you are not required to set it

Up for discussion:
- `userId`: when using this you will get a pretty bad Cache-Hit-Ratio resulting in high server load during peak traffic. So for identified users I would recommend to initiate formbricks in the traditional way
- `attributes`: similar to userId

**Comment by mattinannt** [comment]
The suggestions sounds great to me 😊 I would also skip userId and attributes for now and require the traditional init approach if the Formbricks user / developer wants to set it.

**Review by mattinannt — APPROVED** [review]
@jonas-hoebenreich Thanks for the changes :-) 
I also made some minor changes for more consistent wording throughout the app (`widget` -> `surveys`) and added a bit more error handling 😊.

Let's merge this 😊

**Comment by mattinannt** [comment]
@jonas-hoebenreich It seems that our CLA bot has stored a different Github username from you. Can you please re-sign the CLA using the CLA bot? :-)
(see comment: https://github.com/formbricks/formbricks/pull/2015#issuecomment-1926996385 )

**Pull request merged**
