### PR TITLE
fix: createdAt undefined during initializations

### PR DESCRIPTION
**Pull request by beowulf11**
fix: `displaysState` is an array which we filter and use to get `lastDisplayAt` (if present) but we don't check the size. So if the array is empty the initializations fails.

## What does this PR do?

Added an addition check for initializations to check the size of the array so we don't get an undefined error.

## How should this be tested?

Modify the state object in local storage to have `"displays": []`. This passes all the checks and attempts to get `lastDisplayAt` which fails.

### Required

- [X] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [X] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [X] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

~- [ ] If a UI change was made: Added a screen recording or screenshots to this PR~
~- [ ] Updated the Formbricks Docs if changes were necessary~

## Summary by CodeRabbit

- **New Features**
	- Enhanced migration logic for local storage data.
	- Improved initialization process for website configuration with better error handling.
	- Streamlined handling of configuration parameters.

- **Bug Fixes**
	- Added checks to ensure valid configuration before initialization.

- **Documentation**
	- Improved logging for better debugging during the initialization process.

### CODE REVIEW

**Comment by mattinannt** [comment]
@beowulf11 Thanks a lot for the PR :-) 

@pandeymangg Can you please check if this fix is also relevant after the website & app SDK merge and if we should port this to app surveys?

**Comment by pandeymangg** [comment]
@beowulf11  Thanks for the PR!
we recently merged some changes which changed the way our js sdk works, so now for migrating the sdk's local state backwards, we just copy over the previous state, so this change is not needed now 😊 
If you're using the older version of the sdk, please update to the newest version 🙏

**Pull request closed without merging**
