### PR TITLE
feature/skip logic

### PR DESCRIPTION
**Pull request by moritzrengert**
ui and question / select option delete behaviour are tbd.

### CODE REVIEW

**Comment by mattinannt** [comment]
@moritzrengert When I start a survey from scratch, add Logic to the first question and then create a new Open Text Question I get this error:
Screenshot 2023-05-15 at 17 45 04

**Comment by mattinannt** [comment]
Just played around a bit with the logic editor. Looks great and gives a lot of options 💪💪💪
Found a missing option: when an NPS question is not required there should also be an option "is skipped" in addition to "is submitted". the same with rating question.
Screenshot 2023-05-15 at 17 48 25

**Comment by mattinannt** [comment]
@moritzrengert If a question is deleted that is linked as a logic destination in another question, please set the destination in this question to `end`.
If a multiple choice option is deleted, please just clear the option-select so the user can select a new option.

**Comment by mattinannt** [comment]
@moritzrengert Thanks a lot for the changes 💪 Johannes changed a bit in the survey editor and I prepared the PR for a merge by fixing the merge conflicts that came from these new changes. But I just noticed that the logic jumps don't work in the link surveys. Can you please take a look at this? 😊

(I also added the logicEditor to CTA question. Was there a reason you did not add it to that question type?)

**Comment by mattinannt** [comment]
@moritzrengert Thanks a lot for the changes 😊 I merged the latest changes from main and fixed a bug that prevents the linksurvey reaching the thank you slide.
One issue that I found is that the survey isn't marked as finished (both linksurvey and sdk) when logic jumps leads to the end. It's only marked as finished when you go the non-jump route. Can you please implement a logic that always marks the response as finished when the user reaches the end (thank you slide if exists or survey closes)
Screenshot 2023-05-22 at 13 30 24

**Comment by moritzrengert** [comment]
> @moritzrengert Thanks a lot for the changes 😊 I merged the latest changes from main and fixed a bug that prevents the linksurvey reaching the thank you slide. One issue that I found is that the survey isn't marked as finished (both linksurvey and sdk) when logic jumps leads to the end. It's only marked as finished when you go the non-jump route. Can you please implement a logic that always marks the response as finished when the user reaches the end (thank you slide if exists or survey closes) Screenshot 2023-05-22 at 13 30 24

The issue is resolved, it should now be marked as finished if it does via logic jumps. 🙂

**Comment by mattinannt** [comment]
@moritzrengert thanks for the update :-)  I'm still deep in testing everything. I really like the multiple choice include select in the logic editor - great job 😊

* I still found an issue in NPS questions: I configured a jump but it isn't executed in the preview (right) and just sending me to the next question instead of the end.
Screenshot 2023-05-23 at 11 53 52

* Same problem with `is skipped` in NPS questions
Screenshot 2023-05-23 at 11 56 52

* `is skipped` is not working in CTA questions (no jump happening)

* `is skipped` is not working for Rating questions (no jump happening)

* Multiple Choice Single Select needs an additional `is skipped` logic option if it is not required.

* If I setup the logic (in any question type) and then change the first part of the equation:
Screenshot 2023-05-23 at 12 02 22
It looks like everything worked great
Screenshot 2023-05-23 at 12 03 15
But if I change the question and then go back to this question, the middle value is gone:
Screenshot 2023-05-23 at 12 04 06
Same seems to be the case for the jump destination when e.g. `is skipped` is selected

----
Please test the functionality better before pushing the PR to avoid these long review cycles 😊

**Comment by moritzrengert** [comment]
> @moritzrengert thanks for the update :-) I'm still deep in testing everything. I really like the multiple choice include select in the logic editor - great job 😊
> 
> * I still found an issue in NPS questions: I configured a jump but it isn't executed in the preview (right) and just sending me to the next question instead of the end.
> 
> Screenshot 2023-05-23 at 11 53 52
> * Same problem with `is skipped` in NPS questions
> 
> Screenshot 2023-05-23 at 11 56 52
> * `is skipped` is not working in CTA questions (no jump happening)
> * `is skipped` is not working for Rating questions (no jump happening)
> * Multiple Choice Single Select needs an additional `is skipped` logic option if it is not required.
> * If I setup the logic (in any question type) and then change the first part of the equation:
> 
> Screenshot 2023-05-23 at 12 02 22 It looks like everything worked great Screenshot 2023-05-23 at 12 03 15 But if I change the question and then go back to this question, the middle value is gone: Screenshot 2023-05-23 at 12 04 06 Same seems to be the case for the jump destination when e.g. `is skipped` is selected
> Please test the functionality better before pushing the PR to avoid these long review cycles 😊

I added all the missing functionality and cleaned / updated the logic so that values are only cleaned if there is a switch between multiSelect and singleSelect conditions or in a condition where no value is needed (submit, skip). 🙂

**Review by mattinannt — CHANGES_REQUESTED** [review]
@moritzrengert Thanks for the latest changes. It works pretty well now :-) I think we are close to perfection! ;-) Only one small thing:

*  When I have the multiple options in e.g. `includes all of` the dropdown closes as soon as I select one option. I would like to have it open and let me select as many options as I like and closes on outside click.
Screenshot 2023-05-26 at 15 41 31

And please also fix the merge conflict that come up :-) 🙏

**Comment by moritzrengert** [comment]
Fixed the dropdown closing issue and merge conflicts. 🙂

**Review by mattinannt — APPROVED** [review]
@moritzrengert thanks a lot for the changes 🤗 Looks great! I am going to merge it now 🎉

**Pull request merged**
