### PR TITLE
Revamp NoCode Actions 

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## What does this PR do?
Revamp No Code Actions across the project ie:
- App frontend: Introduce a new modal to have combined selectors in the form of Page URL, inner HTML, and CSS Class selectors!
- Backend: Backward compatible minimal change in a type casting to support the revamp
- JS library: Handle the calling and checking of event triggers for mouse clicks as well as page switches!

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [ ] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey! Thanks a lot for the quick turnaround :)

Here are some remarks:

1. The Modal causes an error in the console, can you fix it?
image

2. Creating a reusable component: I think I didn't describe the task well, so I'll add some explanations and dummy code:

**Objective**: Reduce redundant code and learn how to write reusable components :) 
**Status Quo**: In the Settings View in the SurveyEditor and in the modal you built, we have a total of almost 10 checkboxes which unfold a gray frame with advanced settings:

Screenshot 2023-08-14 at 16 49 05

Screenshot 2023-08-14 at 16 53 10

etc.

Now your task is to create an "AdvancedOptionsToggle" which can be reused. Here is what I would've liked you to do:

1.  Go to the ResponseOptionsCard.tsx and find a piece of code for such an AdvancedOptionsToggle:

`
<div className="p-3">
            <div className="ml-2 flex items-center space-x-1">
              <Switch id="autoComplete" checked={autoComplete} onCheckedChange={handleCheckMark} />
              <Label htmlFor="autoComplete" className="cursor-pointer">
                <div className="ml-2">
                  <h3 className="text-sm font-semibold text-slate-700">Close survey on response limit</h3>
                  <p className="text-xs font-normal text-slate-500">
                    Automatically close the survey after a certain number of responses.
                  </p>
                </div>
              </Label>
            </div>
            {autoComplete && (
              <div className="ml-2 mt-4 flex items-center space-x-1 pb-4">
                <label
                  htmlFor="autoCompleteResponses"
                  className="flex w-full cursor-pointer items-center rounded-lg  border bg-slate-50 p-4">
                  <div className="">
                    <p className="text-sm font-semibold text-slate-700">
                      Automatically mark the survey as complete after
                      <Input
                        autoFocus
                        type="number"
                        min={
                          localSurvey?._count?.responses
                            ? (localSurvey?._count?.responses + 1).toString()
                            : "1"
                        }
                        id="autoCompleteResponses"
                        value={localSurvey.autoComplete?.toString()}
                        onChange={handleInputResponse}
                        onBlur={handleInputResponseBlur}
                        className="ml-2 mr-2 inline w-20 bg-white text-center text-sm"
                      />
                      completed responses.
                    </p>
                  </div>
                </label>
              </div>
            )}
          </div>
`

Copy it to GPT with the prompt to make a reusable component out of it. You'll get this:

`
import React from 'react';

function AdvancedOptionToggle({
  isChecked,
  onToggle,
htmlId,
  title,
  description,
  children
}) {
  return (
    <div className="p-3">
      <div className="ml-2 flex items-center space-x-1">
        <Switch id={htmlId} checked={isChecked} onCheckedChange={onToggle} />
        <Label htmlFor={htmlId} className="cursor-pointer">
          <div className="ml-2">
            <h3 className="text-sm font-semibold text-slate-700">{title}</h3>
            <p className="text-xs font-normal text-slate-500">{description}</p>
          </div>
        </Label>
      </div>
      {isChecked && <div className="ml-2 mt-4 flex items-center space-x-1 pb-4">{children}</div>}
    </div>
  );
}

export default AdvancedOptionToggle;
`

Use it in the ResponseOptionsCard:

`
<AdvancedOptionToggle
  isChecked={autoComplete}
  onToggle={handleCheckMark}
  title="Close survey on response limit"
  description="Automatically close the survey after a certain number of responses."
>
  <label
    htmlFor="autoCompleteResponses"
    className="flex w-full cursor-pointer items-center rounded-lg  border bg-slate-50 p-4">
    <div className="">
      <p className="text-sm font-semibold text-slate-700">
        Automatically mark the survey as complete after
        <Input
          autoFocus
          type="number"
          min={
            localSurvey?._count?.responses
              ? (localSurvey?._count?.responses + 1).toString()
              : "1"
          }
          id="autoCompleteResponses"
          value={localSurvey.autoComplete?.toString()}
          onChange={handleInputResponse}
          onBlur={handleInputResponseBlur}
          className="ml-2 mr-2 inline w-20 bg-white text-center text-sm"
        />
        completed responses.
      </p>
    </div>
  </label>
</AdvancedOptionToggle>
`

-> See if it works and adapt component
-> Replace all other AdvacedOptionToggles with the component and keep improving it while you apply it
-> Use it for the Modal you have been working on :)

--------

The advantages of this approach:

- Better maintainable code
- Less redundant code
- All AdvancedOptionToggles are accessible and properly labeled (the ones you added are not)
- Consistent look and feel of UI

I didn't check the code from GPT in detail, so please make changes to it as you see fit.

I hope this explanation helps you for upcoming frontend tickets, thats why I wrote it up in a bit more detail :)

Thanks!!

**Comment by ShubhamPalriwala** [comment]
Hey @jobenjada, thanks a lot for the detailed approach! I have made the changes as you recommended, please take a look now 🙏🏼

**Comment by ShubhamPalriwala** [comment]
Hey @jobenjada, thanks a lot for the detailed approach, just made the changes, please take a look now, thanks 🙏🏼

**Comment by jobenjada** [comment]
Hey! The refactoring looks good :) 

Is there a specific reason why you did not add the gray box to the component itself? I think that would help keeping the look and feel consistent.

Secondly, I cannot submit the AddActionModal:

https://tella.video/johanness-video-bmb5

Im not getting an error in the console nor as a toast. Am I doing something wrong? :)

**Comment by ShubhamPalriwala** [comment]
Hey @jobenjada, thanks for the feedback, I have made the changes! please take a look 🤞🏼

**Comment by jobenjada** [comment]
Hey!

1. Merged main
2. Had a bug
3. ran pnpm clean, i, build and go
4. Got this:

Screenshot 2023-08-18 at 16 01 42

and an error log in the console which is longer than the max console scroll depth 🗡️ 

@mattinannt any suggestion?

**Comment by ShubhamPalriwala** [comment]
Hey @jobenjada I tried to run it again locally after pulling the main merge commits and it still works for me :/

I used to get this error while development whenever I missed adding the `z.optional()` in the following field in actionClasses types:
```ts
  type: z.optional(z.union([z.literal("innerHtml"), z.literal("pageUrl"), z.literal("cssSelector")])),
```

this used to happen because the validation expected the `type` to be present but in the newer (the ones I added in the PR) actions, it is passed as null! And as soon as I made it optional, I did not face that error again.

I'm still trying to figure out, why you got that error at the first run :/

**Comment by jobenjada** [comment]
Hey Shubi!

The data validation model was on my end, sorry for the confusion.

1. I noticed that adding both a CSS class and an ID does not work:

image

Screenshot 2023-08-21 at 19 36 51

So you might have to split the string, identify if its class or ID and then idenfify separately?

2. Similarly, does class + class also not work:
Screenshot 2023-08-21 at 19 47 45

Ideally you can also update the code so that it is searches for both the classes and only if both match, the event is fired?

What do you think?

This is what I'm testing:

image

Thanks a lot! 🙌

**Comment by ShubhamPalriwala** [comment]
Hey @jobenjada, thank you so much for the feedback! I have made the fix and have tested both the cases ie:
- Class and Class
- Class and ID
and both of them work now! Please take a look 🙌🏼

**Comment by jobenjada** [comment]
Everythings works well! 🚀 

 @mattinannt will give it a last review and then merge it :)

**Review by mattinannt — APPROVED** [review]
@ShubhamPalriwala Great job 🎉 Will merge the changes into main now 😊

**Pull request merged**
