### PR TITLE
feat: improved UI for select & multi-select logic jumps

### PR DESCRIPTION
**Pull request by karishmashuklaa**
## What does this PR do?
This PR is a continuation of #1767, addressing UI issues in the Multi Select Logic Jumps section of the Logic Editor. 

@mattinannt I've also fixed the Chevron visibility as per #1767 

### Before
image

### After
Screenshot 2023-12-12 192318

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@karishmashuklaa thanks :-) Please update your existing PR with this PRs code and close this one so we can test and merge this all together :-)

**Comment by karishmashuklaa** [comment]
@mattinannt This PR has all the code from #1767. I'll be closing the previous one.

**Comment by mattinannt** [comment]
@karishmashuklaa thanks, looks great! :-) Only last issue that I have is that with "equals" and a long text the chevron is very small:
Screenshot 2023-12-12 at 16 09 40

**Comment by karishmashuklaa** [comment]
@mattinannt Fixed. Please check and let me know

**Comment by mattinannt** [comment]
@karishmashuklaa thank you, the logic editor looks great! 😊💪
The only issue that I'm facing is that the dropdown is scrollable horizontally:

https://github.com/formbricks/formbricks/assets/675065/4db48b5f-3d15-482b-bc8c-e6838ddd5c90

**Review by mattinannt — APPROVED** [review]
@karishmashuklaa The horizontal scroll issue still occurred for me. I changed the may width of the select label as the easiest way to solve the issue 🙈
I also changed the alignment for the labels to `text-right`.
Thanks a lot for your changes in this PR; it looks much better now than before :-) 💪🙏

**Pull request merged**
