### PR TITLE
fix: Server Actions errors on self-hosting because of missing allowedOrigins

### LINKED ISSUE #1594: [BUG] - Cannot use server actions at all within a proxied Docker environment due to Nextjs 14 upgrade
### Issue Summary

[This PR](https://github.com/formbricks/formbricks/pull/1483) caused a regression that completely broke my ability to use the app in a dockerized production environment 

I was able to get the app back up and running properly by reverting back to version 1.1.2 which is the last one before the Nextjs 14 upgrade

[More info](https://github.com/vercel/next.js/issues/58019)

### Steps to Reproduce

1. Installed the app's Docker container in a production environment behind Cloudflare (I believe this would also happen behind a typical reverse proxy setup)
2. Successfully created an account
3. Got stuck at onboarding step
4. Examined logs and found the error --- `x-forwarded-host` and `host` headers do not match `origin` header from a forwarded Server Actions request. Aborting the action.

### Expected behavior

App works normally and user doesn't get stuck at onboarding due to broken Server Actions.

### Other information

This appears to be due to the Next 14 upgrade, and there appear to be some fixes [coming soon](https://github.com/vercel/next.js/issues/58019#issuecomment-1795133629) in Nextjs, that will likely need to be integrated into this app.

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
Running on ControlPlane, a k8s-based hosting platform
```

### PR DESCRIPTION
**Pull request by therecluse26**
## What does this PR do?

Adds process.env.ALLOWED_ORIGIN to be bound to server actions 

Fixes #1594

[Fix origin](https://github.com/vercel/next.js/issues/58019)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Run the latest codebase in a docker container behind a proxy like Cloudflare

### Required

- [X] Filled out the "How to test" section in this PR
- [X] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [X] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@therecluse26 thank you for the PR :-) What `ALLOWED_ORIGIN` value do you use?
I would like to avoid introducing a new environment variable. Would it also work for you if we use the value from `WEBAPP_URL` (without the `http://`/`https://`)

**Comment by therecluse26** [comment]
@mattinannt Yes, I believe using the webapp_url should work :)

**Comment by mattinannt** [comment]
@therecluse26 I made the changes only using the WEBAPP_URL and will now merge the PR into main 😊
Thanks for the contribution 🤗🙏

**Comment by therecluse26** [comment]
Sweet, thanks @mattinannt!

**Pull request merged**
