### PR TITLE
fix: Align the UI for the different survey states

### LINKED ISSUE #3206: [🕹️] Align the UI for the different survey states
### Is your feature request related to a problem? Please describe.

Currently, we have two different UIs for the survey states: in the indicator and in the dropdown:

Indicator
image

Dropdown:
image

### Describe the solution you'd like

The UI in the indicator looks better, so pls update the icons in the dropdown to match the ones in the indicator

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SaiSawant1**
## What does this PR do?
Changed the UI. Now icons in the dropdown match the indicator.

Fixes #3206 

https://github.com/user-attachments/assets/73008861-826a-4683-b7a8-28856a0a770e

## How should this be tested?

- Test A
- Test B

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Improved layout of the survey status dropdown for better visual coherence, with status indicators now displayed alongside status labels.
- **Bug Fixes**
	- Enhanced the rendering of status options to ensure consistent alignment and presentation.

### CODE REVIEW

**Comment by jobenjada** [comment]
hey mate! We love your excitement but all oss.gg issues will be free'd up on the 1st so it's fair for everyone.

Please self-assign yourself to the issue to work on it tomorrow :)

I'll close this for now - feel free to reopen once you've self-assigned the issue to you 🙌

**Comment by jobenjada** [comment]
bro did you even test it? :D even in your video it seems like you're avoiding to test it properly 🤔 pls dont waste my time...

https://github.com/user-attachments/assets/b43814ba-0e5f-4c64-a2cc-80d49931985a

**Comment by SaiSawant1** [comment]
@jobenjada,  I don't think my changes would break anything.

https://github.com/user-attachments/assets/f88d55ae-f20b-4566-a7ff-ca0f581e5370

**Comment by SaiSawant1** [comment]
Hey @jobenjada , sorry to disturb you but I checked everything and merged the latest changes. Everything looks fine on my end. Are you still facing the same issues? Pls let me know if there are any issues.

**Review by jobenjada — APPROVED** [review]
works well now, sorry for delay!

**Pull request merged**
