### PR TITLE
fix: removed the tabs border

### LINKED ISSUE #3263: [🕹️] Remove border from tab in Segment filter modal
### Is your feature request related to a problem? Please describe.

image

The border around the tabs looks off

### Describe the solution you'd like

Remove it :) please don't edit the root component though (we use it in many other spots)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pratham271**
## What does this PR do?
removed the border of tabs as shown in the image 
resolves #3263 

Fixes # (issue)

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **Style**
	- Simplified the appearance of the TabBar component by removing the border style from the outer wrapper.
  
- **Bug Fixes**
	- No bug fixes were necessary as the functionality of the TabBar component remains unchanged.

### CODE REVIEW

**Review by jobenjada — APPROVED** [review]

**Comment by jobenjada** [comment]
@Pratham271 you need to sign the CLA to get this merged 🤓

**Comment by Pratham271** [comment]
@jobenjada how can I sign it

**Comment by jobenjada** [comment]
image

click on the link

**Comment by Pratham271** [comment]
@jobenjada I think I have signed it

**Pull request merged**
