### PR TITLE
chore: Introduce unified survey UI package @formbricks/surveys

### PR DESCRIPTION
**Pull request by mattinannt**
## What does this PR do?

Introduce unified survey UI package @formbricks/surveys

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- View and test survey preview in templates view
- View and test survey preview in survey editor

### CODE REVIEW

**Comment by jobenjada** [comment]
Good work, so much smoother!

**Brand Color:** Something is off. In the Onboarding I set it to Pink which is used for Link surveys. In the look & feel settings, the survey editor and the widget its default gray.

---

What I noticed for **LINK** surveys:

1. Power by Formbricks in Link Surveys below the fold, adds scrolling:
image


2. Survey disappeared after second question (Churn Survey in Demo Product). Looks like the Thank You card isnt displayed, happens on all options when the survey is over:
https://tella.video/johanness-video-agln


3. NPS Layout with short text:
image
image


4. Star and Smiley hover and select states not visible:
image


5. Spacing a bit off on right side:
image


6. Even though the last question is required, the Finish button ends the survey without a response:
image


7. Back Button logs IDs:
image


8. Preview Progress Bar looks different and kinda off (fat and too wide):
image


9. Options randomized visibly (I saw them shuffle):
image


10. Progress bar not visible for link survey:
image


11. Other Focus color not brand color:
image


12. Multi Select: Non required question is still required + No hint that I have to fill this out
image


13. No confetti on thank you page :(
image


14. Going back and forth to the first question creates new submissions (link & in app:
Screenshot 2023-08-22 at 12 20 39


What I noticed for **IN APP** surveys:

1. Progress Bar has 1px white line at the bottom, looks cheap:
image


2. Same with focus state color not being brand color on "Other" option:
image


3. The preselect state of the NPS question isnt 100% clear. It kinda looks like the state that you previously clicked there but not that its selected. Pls use the same state like hover (with a light gray background):
image


4. Here it works with the hover state
Screenshot 2023-08-22 at 12 18 05


I'll now test branching :)

**Comment by jobenjada** [comment]
1. The Progress bar in the preview now is broken, dont know yet why:
image

Might be related to this bug: Progress bar moving ahead with every action in the logic editor
https://tella.video/johanness-video-gpnh

On "Restart", the progress bar moves back a little bit.

Maybe this happens when opening a duplicated survey 🤔 

2. Remove shadow of progress bar
image


Other than that I did not spot any issues with the branching or back button - great work!!! 🚀

**Review by jobenjada — COMMENTED** [review]
Left my remarks in the PR, looking really good - love the speed!! ⚡

**Comment by ShubhamPalriwala** [comment]
Looks solid 💯 

A few bugs that I encountered:
- Adding an "Other" option does not show in the Survey Preview in both Single Select and Multi Select:
https://www.loom.com/share/d3ca4ed0982c4d278335b4691b99f71a

- Deleting all questions throws me this errror:
image

- The Progress Bar is not accurate:
https://www.loom.com/share/4acae29af76f4e11aa2e30597e323f6e

- On clicking "Back" button in the 3rd question gives me this error:
image

- Call to Action question editor when selected to link to external link, has a very small URL option (it's the same currently as well on Prod):
image

- Smileys on Survey Preview in Phone mode go out of bounds when selected 10
image

- Cannot select Smileys in Rating question
https://www.loom.com/share/bd7093a02df341daaac73c2c2acd22fc

- In In-app surveys, the 1st question got 2 answers from the same UserID which is weird :// I tried to reproduce it but couldn't
image

- Okay, same for the link surveys as above but instead of 2, I got 10 ://
image

Screen recording for the above 2 in detailed responses page:
https://www.loom.com/share/00e6122d61724d528bf7afc6bdbf0bcf

- On setting the userId from URL, I can see the userId in the people/userId tab:
image

- but in the responses summary, I see the internalID, is this how it should be? 
image

- Again I witnessed multiple first question responses:
image


Error logs on viewing the /responses/[responseId] page:
```
@formbricks/web:go: - wait compiling /api/v1/client/responses/[responseId]/route (client and server)...
@formbricks/web:go: - wait compiling /api/pipeline/route (client and server)...
@formbricks/web:go: - event compiled client and server successfully in 5.5s (11349 modules)
@formbricks/web:go: [next-auth][warn][EXPERIMENTAL_API]
@formbricks/web:go: `getServerSession` is used in a React Server Component.
@formbricks/web:go: https://next-auth.js.org/configuration/nextjs#getServerSession}
@formbricks/web:go: https://next-auth.js.org/warnings#EXPERIMENTAL_API
@formbricks/web:go: ZodError: [
@formbricks/web:go:   {
@formbricks/web:go:     "code": "invalid_union",
@formbricks/web:go:     "unionErrors": [
@formbricks/web:go:       {
@formbricks/web:go:         "issues": [
@formbricks/web:go:           {
@formbricks/web:go:             "code": "invalid_type",
@formbricks/web:go:             "expected": "string",
@formbricks/web:go:             "received": "date",
@formbricks/web:go:             "path": [
@formbricks/web:go:               "response",
@formbricks/web:go:               "data",
@formbricks/web:go:               "gvf0r8xwyy1fvfk6pcrzu97p"
@formbricks/web:go:             ],
@formbricks/web:go:             "message": "Expected string, received date"
@formbricks/web:go:           }
@formbricks/web:go:         ],
@formbricks/web:go:         "name": "ZodError"
@formbricks/web:go:       },
@formbricks/web:go:       {
@formbricks/web:go:         "issues": [
@formbricks/web:go:           {
@formbricks/web:go:             "code": "invalid_type",
@formbricks/web:go:             "expected": "number",
@formbricks/web:go:             "received": "date",
@formbricks/web:go:             "path": [
@formbricks/web:go:               "response",
@formbricks/web:go:               "data",
@formbricks/web:go:               "gvf0r8xwyy1fvfk6pcrzu97p"
@formbricks/web:go:             ],
@formbricks/web:go:             "message": "Expected number, received date"
@formbricks/web:go:           }
@formbricks/web:go:         ],
@formbricks/web:go:         "name": "ZodError"
@formbricks/web:go:       },
@formbricks/web:go:       {
@formbricks/web:go:         "issues": [
@formbricks/web:go:           {
@formbricks/web:go:             "code": "invalid_type",
@formbricks/web:go:             "expected": "array",
@formbricks/web:go:             "received": "date",
@formbricks/web:go:             "path": [
@formbricks/web:go:               "response",
@formbricks/web:go:               "data",
@formbricks/web:go:               "gvf0r8xwyy1fvfk6pcrzu97p"
@formbricks/web:go:             ],
@formbricks/web:go:             "message": "Expected array, received date"
@formbricks/web:go:           }
@formbricks/web:go:         ],
@formbricks/web:go:         "name": "ZodError"
@formbricks/web:go:       }
@formbricks/web:go:     ],
@formbricks/web:go:     "path": [
@formbricks/web:go:       "response",
@formbricks/web:go:       "data",
@formbricks/web:go:       "gvf0r8xwyy1fvfk6pcrzu97p"
@formbricks/web:go:     ],
@formbricks/web:go:     "message": "Invalid input"
@formbricks/web:go:   }
@formbricks/web:go: ]
@formbricks/web:go:     at Object.get error [as error] (webpack-internal:///(sc_server)/../../node_modules/.pnpm/zod@3.21.4/node_modules/zod/lib/index.mjs:615:31)
@formbricks/web:go:     at POST (webpack-internal:///(sc_server)/./app/api/pipeline/route.ts:33:39)
@formbricks/web:go:     at runMicrotasks (<anonymous>)
@formbricks/web:go:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@formbricks/web:go:     at async eval (webpack-internal:///(sc_server)/../../node_modules/.pnpm/next@13.4.10_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/future/route-modules/app-route/module.js:253:37) {
@formbricks/web:go:   issues: [
@formbricks/web:go:     {
@formbricks/web:go:       code: 'invalid_union',
@formbricks/web:go:       unionErrors: [Array],
@formbricks/web:go:       path: [Array],
@formbricks/web:go:       message: 'Invalid input'
@formbricks/web:go:     }
@formbricks/web:go:   ],
@formbricks/web:go:   addIssue: [Function (anonymous)],
@formbricks/web:go:   addIssues: [Function (anonymous)],
@formbricks/web:go:   errors: [
@formbricks/web:go:     {
@formbricks/web:go:       code: 'invalid_union',
@formbricks/web:go:       unionErrors: [Array],
@formbricks/web:go:       path: [Array],
@formbricks/web:go:       message: 'Invalid input'
@formbricks/web:go:     }
@formbricks/web:go:   ]
@formbricks/web:go: }
```


- Multiple responses again ://
image


- NPS answers are not visible in the summary page:
image

- Okay this time, this is how it send responses from a link survey:
https://www.loom.com/share/dbe7f87592b6491596ba2041ebaf6c01


- Possibly due to weird responses and their count, the summary metrics are also flaky:
image


Please let me know if you need any other info/context! I have it running locally

**Comment by mattinannt** [comment]
Issues mentioned above are fixed 😊
Zod error will be solved in a separate ticket. Ready for merge.

**Pull request merged**
