### PR TITLE
fix: Make js assets cachable

### LINKED ISSUE #3336: [BUG] JS assets not cachable by Cloudflare & Cloudfront
### Issue Summary

The js assets provided by Formbricks are not cachable by Cloudflare or Cloudfront since those platforms cannot properly handle the `vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch` header that is set by Nextjs.

### Steps to Reproduce

1. Open https://app.formbricks.com/api/packages/js
2. Check `cf-cache-status` header to see that this resource is not cached by Cloudflare
3. Check `x-vercel-cache` header to see that this resource is cached by Vercel
4. Users that do not host Formbricks on Vercel will have issues scaling the application since the uncached js assets will lead to high server load

### Expected behavior

js assets can be easily cached when using Cloudflare / Cloudfront

### Other information

_No response_

### Screenshots

image
Cloudflare does not cache the request to https://app.formbricks.com/api/packages/js despite the cache-control header being set. This will lead to a high Vercel bill in the long run (since Cloudflare bandwidth is cheaper).

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by jonas-hoebenreich**
## What does this PR do?

This PR changes the build pipeline for the js assets `js`, `js-core` & `surveys`. The output files of the pipeline are now copied to the /apps/web/public/js folder where they will be natively served by Nextjs.
So instead of `https://app.formbricks.com/api/packages/surveys` the new asset endpoint will look something like this: `https://app.formbricks.com/js/surveys.umd.cjs`.
The new endpoints can be cached by Cloudflare / Cloudfront.

Fixes #3336

So far this is still a WIP (eg asset endpoints need to be changed throughout Formbricks & rewrites should be added). Also it seems like changing the filenames has some implications on the build process se we might have to come up with a simple solution for this (also also decide how the filenames should be named).

## How should this be tested?

- Check headers when requesting public files.

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced a global interface for the `Window` object to enhance integration with the Formbricks application.
	- Added improved error handling and message validation in the `SurveyWebView` component.
	- Added a new plugin for copying compiled assets during the build process.

- **Chores**
	- Updated script source URLs for loading the Formbricks SDK to ensure consistency.
	- Updated Vite configuration to facilitate file copying post-build for better resource management across applications.
	- Enhanced `.gitignore` to include additional patterns for ignored files and directories.
	- Removed deprecated API endpoint for improved performance and clarity.
	- Incremented version number of the `@formbricks/js` package from `3.0.0` to `3.0.1`.

### CODE REVIEW

**Comment by mattinannt** [comment]
@jonas-hoebenreich Thanks for raising a PR for this 😊💪
The caching approach looks good 🚀 But it seems like you are mixing a few different topics in one PR. For the future it would be easier for us if you raise one PR for every feature (e.g. one for caching headers; one for iife,..) so we can review and merge more quickly :-)

**Comment by pandeymangg** [comment]
@jonas-hoebenreich Thanks for opening the PR, looks good, I just have a couple of comments, can you please look at these and implement them:
1. the `@formbricks/js` package doesn't need to be copied over to the `public/js` directory since its just a wrapper over the `@formbricks/js-core` package and should only be used through npm and not requested over network
2. the PR size gets too big because of all the additions in the `public/js` directory, could you please add them to the `.gitignore` so that they don't get commited 😊 
3. I think we have the same plugin code repeated at a couple of places, can we maybe extract this into a separate rollup plugin under the `packages/` directory, it can accept the package its being called from as an argument and then copy over the files, also, in the plugin logic, I think we should probably check if the `public/js` directory does not exist, we should create it as well, it seems a bit unideal that if the `public/js` directory gets deleted for some reason, the packages fail to build 😊

**Comment by jonas-hoebenreich** [comment]
> @jonas-hoebenreich Thanks for raising a PR for this 😊💪 The caching approach looks good 🚀 But it seems like you are mixing a few different topics in one PR. For the future it would be easier for us if you raise one PR for every feature (e.g. one for caching headers; one for iife,..) so we can review and merge more quickly :-)

Haha, I hoped I could slip in the iife change

**Comment by mattinannt** [comment]
@jonas-hoebenreich thanks for the code updates :-) @pandeymangg take over the PR tomorrow and add some missing docs updates and will fully test the functionality with all edge cases. I think we can merge it soon 🚀

**Review by pandeymangg — APPROVED** [review]

**Pull request merged**
