### PR TITLE
Feature create team v2

### PR DESCRIPTION
**Pull request by jobenjada**
## What does this PR do?

Allows people to create a new team. Helpful to handle several products / projects with Formbricks.
grafik
grafik

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by jobenjada** [comment]
updated :) forward works now!

**Review by mattinannt — CHANGES_REQUESTED** [review]
@jobenjada Unfortunately the PR has a merge conflict in the `PULL_REQUEST_TEMPLATE.md`
Please fix the issue and make two separate PRs next time so one feature isn't blocking the other 😊🙏

**Comment by jobenjada** [comment]
updated, good points!

**Review by mattinannt — APPROVED** [review]
@jobenjada thank you for the changes 🤗 I am going to merge the changes now 🎉

**Pull request merged**
