### PR TITLE
feat: Enable Prefilling of several values

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
Enables Prefilling of several values

Fixes
https://github.com/formbricks/internal/issues/73
https://github.com/formbricks/formbricks/issues/2433

https://github.com/formbricks/formbricks/assets/56182734/fde78663-d0e4-40ae-95c8-7604c7f0e95d

## How should this be tested?

- Create a survey with more than 1 question, try to prefil multiple question by providing `id=value` in the query params.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by jobenjada — CHANGES_REQUESTED** [review]
Hey! Works well so far :) A few questions:

1. Please update the Prefilling docs in the link survye section with the changes. Add a section where you explain the format needed for each question type as well as potential edge cases, what happens when the validation doesn't work and add an example for all question types which can be prefilled.
2. Currently, it's not possible to get the initial UX of clicking on an answer in an email which then gets prefilled and the question is skipped. My idea was to do use logic jumps to still enable this UX, even if not by default (see image). Is this possible without being too hacky? So essentially: Don't skip prefilled values unless a logic jump says so?
3. Not sure if it was part of the ticket but is it possible to introduce another link parameter skipPrefill  which when set to true skips prefilled questions? How hacky would it be?

Thanks!

**Comment by gupta-piyush19** [comment]
Thanks, @jobenjada, for the review.
As per your suggestions,
1. I've updated the docs and added examples for all the questions that can be prefilled.
2. We're keeping the logic very simple in this PR, just to show the prefilled value to the user. This could create messed-up logic if done with startAt functionality.
3. To support `skipPrefill`, we would still need two different urls, one with `skipPrefill` query params and the other without them. If we've got to create two different links anyway, it'd be better to just remove the prefiling parameters in the second one instead of adding one extra param.


> Hey! Works well so far :) A few questions:
> 
> 1. Please update the Prefilling docs in the link survye section with the changes. Add a section where you explain the format needed for each question type as well as potential edge cases, what happens when the validation doesn't work and add an example for all question types which can be prefilled.
> 2. Currently, it's not possible to get the initial UX of clicking on an answer in an email which then gets prefilled and the question is skipped. My idea was to do use logic jumps to still enable this UX, even if not by default (see image). Is this possible without being too hacky? So essentially: Don't skip prefilled values unless a logic jump says so?
> 3. Not sure if it was part of the ticket but is it possible to introduce another link parameter skipPrefill  which when set to true skips prefilled questions? How hacky would it be?
> 
> Thanks!

**Comment by jobenjada** [comment]
Hey Piyush!

Works great, good job until here!

As you mentioned, once you bring startAt to the party, things get messy. Let's have a chat re this tomorrow and then merge this 💪

**Comment by jobenjada** [comment]
Hey! A few bugs:

The first question gets a "back" button on prefill:

image
image

And the second question doesn't?
image

That should be it :)

**Review by jobenjada — CHANGES_REQUESTED** [review]
pls see comment

**Comment by gupta-piyush19** [comment]
@jobenjada Thanks for testing the feature. I've pushed the fix for the issues.

https://github.com/formbricks/formbricks/assets/56182734/c366a8e2-d421-467d-8374-74fff7b24f55

**Review by pandeymangg — CHANGES_REQUESTED** [review]
Thanks for the PR @gupta-piyush19 😊  looks great!
I just found this bug while testing, could you please take a look at it 🙏 
https://github.com/formbricks/formbricks/assets/54475686/2614b8a9-66e4-405b-a45c-0847c30bbaa0

**Review by pandeymangg — APPROVED** [review]
LGTM! 🚀

**Review by jobenjada — APPROVED** [review]

**Pull request merged**
