### PR TITLE
fix: Disabling Welcome Card leads buggy preview

### LINKED ISSUE #1289: [BUG][FormTribe 🔥][200 Points] Disabling Welcome Card & Thank You card leads to buggy preview
### Issue Summary

When you currently inspect the Welcome Card and then disable it, the Preview should jump to the first question of the survey instead of showing an empty card:

image

### Steps to Reproduce

1. Enable Welcome Card
2. Clicked on it to preview it
3. Disable it via Toggle

### Expected behavior

Jump to first question

### PR DESCRIPTION
**Pull request by HarshitVashisht11**
## What does this PR do?

Fixes #1289 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by Dhruwang** [comment]
Hey @HarshitVashisht11 , this looks good 😊🥳

However it would be better if we don't repeat the code for rendering `QuestionConditional` twice
Can you please find a generic solution for it ?😊

Because we also want to use this fix for thank you card and as per this approach we have to create one more render for `QuestionConditional`

And can you also create similar fix for thank you card (if disabled, show last question) 

Thank you ! 🚀

**Comment by HarshitVashisht11** [comment]
sure i will try

**Comment by Dhruwang** [comment]
Hey @HarshitVashisht11 😊 , is it ready for review ?
Because I tested the functionality after pulling the latest changes and it is not working :(
Converting this to draft for now, please mark it as ready for review once its completed 😊

**Comment by HarshitVashisht11** [comment]
Hi @Dhruwang can tell how to remove thankyou card because i am not able to find option of removing thank you card in the website

**Comment by Dhruwang** [comment]
Actually thank you card is mandatory for link surveys but optional for in-app survey (web app), so you will see toggle for it only for in-app surveys
Screenshot 2023-10-21 at 6 00 32 PM

Hope this helps
If you have any other question feel free to reach out 😊

**Comment by HarshitVashisht11** [comment]
i can't understand when thank you card is disabled so what will it display when you click on finish

**Comment by Dhruwang** [comment]
It should display last question

**Comment by HarshitVashisht11** [comment]
But on last question if someone clicked on finish so why will it show last question

**Comment by Dhruwang** [comment]
For link surveys, thank you card is compulsory to after last questions respondent sees the thank you card
But for web app (in-app) surveys, can you create this behaviour 😊
Screenshot 2023-10-22 at 10 40 43 AM

**Comment by HarshitVashisht11** [comment]
https://github.com/formbricks/formbricks/assets/120767685/102d979e-1c38-46c2-936c-65c1255f34f1

**Comment by HarshitVashisht11** [comment]
https://github.com/formbricks/formbricks/assets/120767685/642d0711-5001-4e50-9054-7663406511ce

@Dhruwang is these changes are good ?

**Comment by jobenjada** [comment]
@HarshitVashisht11 The Welcome Card behaviour is good, this works :) People can check out the card but the Preview doesnt break!

On the Thank You card, its not good:

1. When the Thank You card is disabled, after the last question the web app survey has to go away. In the Survey Editor we have it slide out to the right, reset to the first question and slide back in from the right to indicate that the survey was over.
2. The Thank You Card should behave exactly like the Welcome Card: When its disabled and people click on it, it should still open but the Preview should not change. You've built it already for the Welcome Card, just apply it to the Thank You card as well.

Thanks!! 🙏

**Comment by Dhruwang** [comment]
Thank you @HarshitVashisht11 for the changes, works good 😊🚀
I just pushed a minor fix for welcome card 😊

**Review by Dhruwang — APPROVED** [review]

**Comment by HarshitVashisht11** [comment]
Hi @Dhruwang Thank you for reviewing my PR, I'm excited to know when my PR might get merged , as hacktoberfest is about to end and I still left 1 more PR.

**Comment by jobenjada** [comment]
Works well, sorry for the delay and thanks! :)

**Pull request merged**
