### PR TITLE
[FEATURE] Filter by Date Range

### PR DESCRIPTION
**Pull request by gitstart-formbricks**
### DEMO VIDEO
https://www.loom.com/share/0c93b54a49ae43da8185cc94ae026161?sid=87525dc4-4af6-4ac9-b201-c4daed796f6a

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey! Played around with it and got this error:

grafik

How to reproduce:

- Double click on the same day without Resetting the filter.

This also leads to the filter seeming broken.  If you select the current day by clicking the same day in the Date Picker twice, it doesnt show the results for this day.  As you can see here, I have a submission from a few minutes ago:
grafik


When I only choose today by clicking the 25th twice without resetting it before, it doesnt show any submissions:
grafik

Please fix that. Apart from that, looks great! 😊

**Comment by gitstart-formbricks** [comment]
@jobenjada The above issuses have been addressed. You can have another look. Thanks.

**Comment by jobenjada** [comment]
Works great, thanks! :) @mattinannt will do a final code review before merging.

**Comment by gitstart-formbricks** [comment]
Addressed in https://github.com/formbricks/formbricks/pull/474

**Pull request closed without merging**
