### PR TITLE
fix: Webhook testing is throwing not useful error

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
Fixes webhook testing endpoint

Fixes
https://github.com/formbricks/internal/issues/280

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by gupta-piyush19** [comment]
https://discord.com/developers/docs/resources/webhook#execute-webhook

**Comment by mattinannt** [comment]
@gupta-piyush19 Can you please give a bit more explanation here what the issue was and how the fix works?

Also this is not preventing the user from seeing the message
```
An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details…
```

**Comment by gupta-piyush19** [comment]
Fixed the issue. Now, the user will see the error 😊 
image

**Review by Dhruwang — CHANGES_REQUESTED** [review]
Hey @gupta-piyush19 , works well 😊🚀

I just pushed a few tweaks related to add Webhook modal

- Scroll to survey select section
- Disabled test Endpoint button when no url is entered

For long error messages, toast looks a bit odd 

Screenshot 2024-07-08 at 5 17 52 PM

Can you please fix that 😊

**Review by Dhruwang — APPROVED** [review]
Looks good 😊

**Pull request merged**
