### PR TITLE
fix: forbricks widget loading issue

### LINKED ISSUE #1409: [BUG] Cannot read properties of undefined (reading 'init') while widget load
### Issue Summary

1. Run Formbricks with Docker locally and initial setup in dashboard.
2. Add this code to local html page in `<head>` tag:
```
<!-- START Formbricks Surveys -->
<script type="text/javascript">
!function(){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src="https://unpkg.com/@formbricks/js@^1.0.0/dist/index.umd.js";var e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(t,e),setTimeout(function(){window.formbricks=window.js;window.formbricks.init({environmentId: "clo0n171n000pov01lckewbam", apiHost: "http://localhost:3000"})},500)}();
</script>
<!-- END Formbricks Surveys -->
```
and getting error in browser console:

Chromium
```
Uncaught TypeError: Cannot read properties of undefined (reading 'init')
```
Firefox
```
Uncaught TypeError: window.formbricks is undefined
```

### Steps to Reproduce

1. Setup Formbricks from Docker
2. Connect Formbricks to your app. From dashboard (Setup checklist -> HTML tab) copy code
3. Paste code to <head> tag your local html page.

### Expected behavior

Frombricks widget will be load whitout javascript error.

### Other information

Tested in:
1. Chromium 116.0.5845.180
2. Firefox 102.15.0esr x64

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:Linux Debian 11
- Node:not applicable
- npm: not applicable
```

### PR DESCRIPTION
**Pull request by ruhani2**
## What does this PR do?

This PR has change to make sure, the document is loaded then only formbricks object is loaded.

https://watch.screencastify.com/v/Y4PP9nKqxqvYr1nZnCj0

Fixes #1409

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Setup Formbricks from Docker, Connect Formbricks to your app. From dashboard (Setup checklist -> HTML tab) copy code, Paste code to tag your local html page.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by ruhani2** [comment]
Hi @jobenjada, can you please add hactoberfest label, if you think this is valid ?

**Comment by ShubhamPalriwala** [comment]
We're still investigating if the issue persists on the latest js package and only then we will consider this PR! Hence converting it to draft for now

**Comment by ruhani2** [comment]
> issue persist

Hello @ShubhamPalriwala, I think, this error is not happening because of the wrong js file or package, but object method is being accessed even before the object is created  (accessing the method within setTimeout won't ensure the js file is fully loaded or the object is accessible) and that is what I have tried to fix. 

But I would love to know your thoughts as well. :)

**Comment by mattinannt** [comment]
@ruhani2 thank you for the PR :-) 💪
@ShubhamPalriwala Can you please test the approach and if working also update the snippet in the docs as well as in the setup checklist? 💪

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey @ruhani2, apologies for the delay in the review. I tested with the latest code on main and it works just fine! Can you please test to see if you're still encountering the bug? Thanks

**Comment by ShubhamPalriwala** [comment]
Hey @ruhani2, I just tested this again in my browsers and its working fine with the latest release! Closing the PR for the same reason.

Thank you for helping us with this 💪🏼

**Pull request closed without merging**
