### PR TITLE
fix: image and page responsiveness in docs section

### PR DESCRIPTION
**Pull request by itzabhinavarya**
## What does this PR do?

This PR fixes the issue #1044 .

Fixes # (issue)

image

image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala Sir, You can see my changes at line no. - 129.
The only changes i have made in the  page.mdx File.

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Can you please, first, remove the unnecessary documentation changes since they will affect the headings/indexes/formatting. And once that's done, then I can take a look at the required change and test that as well

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala Sir, Now check please

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala Sir, The only changes i have made at **line no. - 128 in page.mdx file**. 
and may be due to code formatter it is reflecting, and no content changed by me in the page.mdx file except line no. 128. I have verified and i request you to look at the code and verify these change my changes have fixed the issue. Kindly verify by your end also.

**Comment by itzabhinavarya** [comment]
@jobenjada Sir, Kindly look at the PR as well as the previous comment also.

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @itzabhinavarya, I understand that you formatter would have made the changes. Please take a look here: https://github.com/formbricks/formbricks/pull/1048/files and you'd understand how some of the docs has changes for example some text has moved to a heading and has messed up the note. So try disabling your formatter or ask it to use in-project config. And then please revert back these changes to only avoid the changes.

Please fix the unneeded changes! And apart from that, the image still looks weird when run on local:

image

**Comment by itzabhinavarya** [comment]
@ShubhamPalriwala Sir.

Please guide with these steps :
 1. I want to revert back all the changes i have made.
      i.e : I want the actual page.mdx file again. so i avoid the
formatter           and make actual issue highlighted and commit it. I have
ran                   git checkout f'ilename' cmd , but didn't worked. I
want the current            page.mdx file from the Formbricks repo. how can
i get. So that i            can make only that change which i want to
reflect and avoid the            rest.

NOTE : Due to formatter, The alignment issue may be occurred so that's why
the image is showing wierd, But when i executed the code it is working
fine.

Guide me with that steps, how can i revert back to the original file
content. after that I'll fix this one.

I got to know that what should i have to do with this issue.

Please help me a bit Sir.

**Comment by ShubhamPalriwala** [comment]
Closing this since a new PR is opened in favour of this

**Pull request closed without merging**
