### PR TITLE
Feat/embed via iframe issue 402

### LINKED ISSUE #402: [FEATURE] As a user I want to embed the link survey via iframe
**Is your feature request related to a problem? Please describe.**
grafik

**Describe the solution you'd like**
While the survey is already iframable, it could be made easier for our users.

**Tasks**
1. Add a button "Embed" with a CodeBrackets icon next to Preview:
grafik

2. On click, switch the URL out with a CodeBlock (see formbricks/ui) which contains the needed code to embed the form with an iframe. **Make sure its responsive.**

### PR DESCRIPTION
**Pull request by Ankur-Datta-4**
## What does this PR do?

Gives user an option to embed the survey into their websites.  Thus added an embed button and related html-iframe code while sharing the link of the survey in /environments/[environmentId]/surveys/[surveyId]/summary page

Fixes #402 

How it looks now:

https://github.com/formbricks/formbricks/assets/75306530/d17c80f5-c5e6-4ef1-8586-fa76574b5841

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [X] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Create & publish a survey. On-click share-button, should reveal a modal containing embed[NEW], copy-url and preview options
- On-click embed button, the embed code-block must be displayed along with success toast that the code is copied to the clipboared
- Check if modal remains responsive when opened to share embed-iframe

## Checklist

- [X] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues
- [X] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @Ankur-Datta-4 

Thanks a lot for reworking the PR, the UI looks a lot better and works as expected 😊 

I noticed that the iframe you offer isn't responsive. I'd expect something like this:

`<div style="position: relative; overflow: auto; height: 100vh; max-height: 100vh;">
    <iframe src="http://localhost:3000/s/clj2uev1h0000u0f6gm8josl7" 
            style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;">
    </iframe>
</div>
`

Please update the code accordingly 🙌

**Comment by Ankur-Datta-4** [comment]
I've used your logic for wrapping the iframe with a div to make it responsive.

But yea, the codeblock looks a bit messier 😌
image

**Comment by jobenjada** [comment]
Thanks Ankur, looks good enough ;)

**Review by mattinannt — APPROVED** [review]
@Ankur-Datta-4 thanks a lot for the PR 💪 Works great, code looks good; I will merge it into main now 😊🎉

**Pull request merged**
