### PR TITLE
fix: Added DialogTitle and DialogDescrtiption components to the dialog.

### LINKED ISSUE #3098: [BUG] `DialogContent` requires a `DialogTitle`
### Issue Summary

Navigating to any dialog/modal throws error and warning in the browser console.

>**[ERROR]** `DialogContent` requires a `DialogTitle` for the component to be accessible for screen reader users.
>
>If you want to hide the `DialogTitle`, you can wrap it with our VisuallyHidden component.
>
>For more information, see https://radix-ui.com/primitives/docs/components/dialog

>**[WARNING]** Missing `Description` or `aria-describedby={undefined}` for {DialogContent}.

### Steps to Reproduce

1. Open browser
2. Navigate to a page with modal. E.g. `Surveys > Some Survey > Share Button`
3. Observe console

### Expected behavior

No error logs

### Other information

_No response_

### Screenshots

image

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Win 10
- Formbricks v2.5.0
- Browser: Chrome
```

### PR DESCRIPTION
**Pull request by SaiSawant1**
This will fix the warnings and errors that appear when a any modal is opened.

dialog-content final fix

Dialog Description fix

minor fix

## What does this PR do?
This PR will resolve all the warnings related to modal/dialog components.

Radix dialog content requires the DialogTitle to be children of the DialogContent.

Fixes #3098  

https://github.com/user-attachments/assets/9afc667b-728c-47f5-98ce-ce452596d88b

https://github.com/user-attachments/assets/286f4a6d-a8ab-4d33-812a-fdd393a7f631

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced dialog components for sharing surveys, improving accessibility and semantic structure.
	- Updated survey link display to allow users to modify the survey URL freely.

- **Bug Fixes**
	- Improved rendering performance in the Copy Survey Form by ensuring unique keys for list items. 

- **Documentation**
	- Added structured components for better clarity in dialog titles and descriptions across various components.

### CODE REVIEW

**Comment by jobenjada** [comment]
@Dhruwang looks good to me, pls test and add to merge queue 🤓

**Review by jobenjada — APPROVED** [review]
to enable merge once Dhru reviewed

**Review by jobenjada — CHANGES_REQUESTED** [review]
hey @SaiSawant1 

There's also this modal with the Dialog Title error (and another error and warning): 

image
image


Please fix these, the rest looks good  🙏

**Review by Dhruwang — APPROVED** [review]
Looks good, Thanks @SaiSawant1 😊🚀🙌🏻

**Review by jobenjada — APPROVED** [review]
thanks guys!

**Pull request merged**
