### PR TITLE
feat: recontactSessions new option to remind about survey for some time

### PR DESCRIPTION
**Pull request by KatSick**
## What does this PR do?

Add a feature to show survey "reminder" based on displays count. E.g. show survey 3 times and then stop.
Currently it is only possible to show once or until feedback.

image

## How should this be tested?

- Add "Recontact session times". Verify formbricks shows that number of times

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@KatSick Thanks for opening the PR :-) This approach sounds very interesting and I will discuss it with the team :-) 
I would do some renaming to make it clearer that the survey will be shown max 5 times per user and also we need to include the check into the `getSyncSurveys` function, but otherwise it looks good :-)

**Comment by KatSick** [comment]
thanks @mattinannt. added filtering to `getSyncSurveys` and fix bug with URL forming. we are using formbricks under reverse-proxy under /formbricks endpoint and if we pass <url>/formbricks to the `apiHost` property, it lose the /formbricks prefix

**Review by jobenjada — DISMISSED** [review]
pls see comment above

**Comment by KatSick** [comment]
looks awesome to me. I will change my implementation.

**Comment by jobenjada** [comment]
hey @KatSick - any updated from your end? :)

**Comment by KatSick** [comment]
Working on it. I hope to finish it today/tomorrow

**Comment by KatSick** [comment]
@jobenjada updated

**Comment by KatSick** [comment]
I noticed, that current logic is broken for "app" type surveys, since they do not have filterSurveys function anymore... investigating

**Comment by KatSick** [comment]
I tried my best to fix it, however, I does not work correctly still for app surveys, because it does not always re-fetch config in sync.ts file. If I delete the formbricks-js-app localstorage cache (to force update), it works correctly each time.

how this feature should work without local client state as in survey website type?

**Comment by mattinannt** [comment]
@KatSick Sorry for the late response.
I will look into this :-) Theoretically, it should work with app surveys as well, since we call the sync endpoint every time we show a survey (in `widget.ts` / `closeSurvey`) and should be able to recalculate which survey is shown and returned to the client.

**Comment by mattinannt** [comment]
@pandeymangg Can you please take a look at this PR and make the necessary changes? :-)

Johannes has already provided the UI design that shows the desired behaviour, but there still seem to be issues with the behaviour in app surveys compared to website surveys.

Can you please review the existing behaviour for website surveys if everything works as expected and the code is aligned with our coding guidelines. Can you please also add the same behaviour to work with app surveys through the sync endpoint? 😊🙏.

**Review by mattinannt — APPROVED** [review]

**Pull request merged**
