### PR TITLE
fix: add a flex wrap to wrap elements if the ui is getting smaller

### LINKED ISSUE #3445: [🕹️] UI Breaks for Input Type Options in Survey Creation
### What side quest or challenge are you solving?

Bug Hunter

### Points

150

### Description

When creating a survey and selecting the option to create a survey from scratch, I've encountered a responsive design issue. Specifically, the input type UI breaks when viewed on screen widths between 770px and 930px.

Steps to Reproduce:

Navigate to the survey creation page.
Select "Create Survey from Scratch."
Observe the input type options.

### Provide proof that you've completed the task

formbricks

### PR DESCRIPTION
**Pull request by DivyanshuLohani**
## What does this PR do?
Fix the ui breaking between 770px and 930px. The options for the input type overflowed which is a resposive issue
Fixes #3445 

https://github.com/user-attachments/assets/0b8ebfa2-5c5b-4e34-ba44-787baa3ae9fb

## How should this be tested?
Goto Create a survey
Create from scratch
On smaller Resolution device observe the Input Type Input

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced a `disabled` option for individual settings in the OptionsSwitch component, enhancing user interactivity.

- **Style**
	- Updated visual feedback for disabled options with new styles, improving clarity on option availability and interaction.

### CODE REVIEW

**Comment by Dhruwang** [comment]
Hey @DivyanshuLohani , thakns for the PR 😊🚀
While testing it, i noticed an inconsistency with the highlight of selected option

Screenshot 2024-10-14 at 12 15 02 PM

**Comment by DivyanshuLohani** [comment]
> Hey @DivyanshuLohani , thakns for the PR 😊🚀
> While testing it, i noticed an inconsistency with the highlight of selected option
> 
> Screenshot 2024-10-14 at 12 15 02 PM
> 

What should it look like then should the new elements begin from the start?

**Review by Dhruwang — CHANGES_REQUESTED** [review]
I am talking about this box here which denotes selected option

Screenshot 2024-10-14 at 12 15 02 PM

**Comment by jobenjada** [comment]
we will sort all of this out when tackling responsiveness :)

**Pull request closed without merging**
