### PR TITLE
feat: Validation for Number, URL, Email and Phone Number in Open Text Question

### LINKED ISSUE #909: [FormTribe 🔥][1000 Points] Validation for Number, URL, Email and Phone Number in Open Text Question
### Welcome to the FormTribe

This issue will get you **1000 points**  for the [FormTribe Hackathon](https://formtribe.com)

**Preparation:**
If this is your first time contributing, please read:

- Our [introductory blog post](https://formbricks.com/blog/join-the-formtribe)
- Overview of [Code Guidelines at Formbricks.](https://formbricks.com/docs/contributing/how-we-code)

**Only when your PR follows _all_ of the best practices it will get merged.**

Want more points quick? Complete [Side Quests 🏰 ](https://formbricks.com/formtribe#side-quests)

-------

### Is your feature request related to a problem? Please describe.

The free text field is often used for general details such as Email, Phone number, Integer, etc. Survey responses having incorrect data type makes it difficult for survey creators to parse it in a generalised and bulk way.

### Describe the solution you'd like

The survey should pack validation at the client side itself ie when a user is submitting a survey to make it more versatile and assure that the data which is put in, is actually the data the survey creator expects.

### Tasks

We primarily have 2 sides to tackle:

1. For the admin side: We have to give them an option to toggle between what they want the specific validation to be (Number, URL, Email, Phone Number) in the survey creation/editing part.
2. For the user side: Validate if the user gets appropriate error/warning if they do not pass valid information.

We will follow a top-down approach for easier understanding and slowly diving into the core engineering.

### Admin Side:

1. In the Survey JS package, you will find the OpenTextQuestion file: [https://github.com/formbricks/formbricks/blob/main/packages/surveys/src/components/OpenTextQuestion.tsx](https://github.com/formbricks/formbricks/blob/e0b04a75a4abc9fafe4b4ca6be8a94aacce58170/packages/surveys/src/components/OpenTextQuestion.tsx)
2. We now need to build a reusable multi toggle component for the question types, try to use ShadCN and add a component for faster turnaround time and uniformity across the app.
3. Add a component inside it where the survey creator can set the question type as below.
image

4. Make sure the default is set to normal open text question type
5. Once the UI is done and you are able to parse the input type the survey admin selects, we will now shift our focus to how do we make this work.
6. The next question should be, where/how do we store this input type, for which we will now go to our schema in the database and see whats the cleanest way of adding an option.
7. In this file (https://github.com/formbricks/formbricks/blob/e0b04a75a4abc9fafe4b4ca6be8a94aacce58170/packages/types/v1/surveys.ts), you will find the ZSurveyOpenTextQuestion type that we use for the Open Question. Now, add a field in here that will hold the type, name it "inputType" with possible values "text" | "email" | "url | "number" | "phone".
8. To maintain Backward Compatibility (ie to make sure the previous opentext questions do not break since we are adding a new field), keep in mind to keep the field optional and during parsing at the client side, remember to track the case of the field not existing and treat is a normal open text question.
9. Now that we have the database supporting us with a new field, we will follow the story mode (ie how this feature will come live).
10. First, the survey admin will visit the survey editor to create a survey with such a question type, so go to this file ([https://github.com/formbricks/formbricks/blob/main/apps/web/app/(app)/environments/%5BenvironmentId%5D/surveys/%5BsurveyId%5D/edit/SurveyEditor.tsx](https://github.com/formbricks/formbricks/blob/e0b04a75a4abc9fafe4b4ca6be8a94aacce58170/apps/web/app/(app)/environments/%5BenvironmentId%5D/surveys/%5BsurveyId%5D/edit/SurveyEditor.tsx)) and slowly navigate your way deeper with where you need to make the change to add the new type when a new survey is created or an old one is edited.
11. Once this is done and you can see the inputType coming in your database, you have the admin side ready!

### User Side

1. Now thinking from the perspective of a user when they see a survey, the same component is called here ([https://github.com/formbricks/formbricks/blob/main/packages/surveys/src/components/OpenTextQuestion.tsx](https://github.com/formbricks/formbricks/blob/0a08d7df680dde5aceef9ac6e86410a4d5de5c05/packages/surveys/src/components/OpenTextQuestion.tsx)), we need to validate based on the input type and set it accordingly. Look into how you can do simple validation based on the input value and the input type. 
2. Please do not install an additional library for validation. We do not require anything complex. For example, for phone numbers, we should only allow the "+" field and only numbers. Please make it work with JS validations and the HTML native tags if they exist.

### Thanks!

### PR DESCRIPTION
**Pull request by KapadiaNaitik**
## What does this PR do?

Fixes #909  (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Create a new survey with type open
- 

## Checklist

- [ ] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey @KapadiaNaitik Thanks a lot for the quick turnaround :)

I have commented on the issue that we're working with you to get this merged - this will remove the pressure to ship something super fast but allow us to get it right ;)

Here are some issues with the current PR:

1. UI - Please build a reusable component for the switch mocked up in the ticket. Use it for this case:
image

2. Its quite buggy, always switching back to Text and seems to have an issue with validation when the field is not empty:
https://tella.video/johanness-video-7upa

3. Add validation message:
image
image

Will check back in once this is done :)

**Comment by gupta-piyush19** [comment]
@KapadiaNaitik Also, I just checked the code a bit, and found several issues:
1. Can't see any change in the schema to store the open text type
2. Check if the logic you've implemented is also working with prefiling or not.
cc: @jobenjada

**Comment by KapadiaNaitik** [comment]
@jobenjada I have fixed those bugs and added a validation message. Do let me know if something is missing

**Comment by jobenjada** [comment]
@KapadiaNaitik thanks for following up!

**1. Please build the correct UI**

image

This is what we're asking you to build:

image

So make the container full-width, justify-between, use HeroIcons solid and add bg-slate-100 with proper paddings for the buttons.

2. Rename "Question Type" to "Input Type"

3. Currently, it feels like it's not working, because nothing changes when using the selector. To change that, please update the placeholder text dependent on the input type:

- Text: "Type your answer here..."
- Email: "example@email.com"
- URL: "http://..."
- Number: "42"
- Phone: "+1 123 456 789"

4. Validate on Next button click:
image

Currently, you're validating as soon as the respondent starts typing. This is pretty bad UX because people don't get a chance to do it right but our form already tells them that they are doing it wrong.

5. Use HTML validation
We already use it for required fields and its not beautiful but it works well. We will revamp our validation at some point, until then let's go with the most robust and performant validation: [Standard HTML validation.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types).

I'm aware that this alleviates the need for red borders and error messages but I prefer to keep it consistent and robust for now and we can tweak the UX when it works well :)

6. Tweak UX
image

By default, we have a textarea. When people toggle to a input type which is not 'text' please auto toggle off the "Long answer" toggle. Users might not be aware that they have this option. However, make sure that if they then toggle to long answer again, this value is stored. If they then toggle to a email, url, phone or number again, its okay for the Long answer toggle to be auto toggled off again :)

I hope I explained that well :D


### Thanks!

**Comment by KapadiaNaitik** [comment]
@jobenjada For the html validation do you want me to perform validation using pattern attribute?
Also I have modified the UI to as below:
image
Do let me know if any changes to the UI are required.

**Comment by jobenjada** [comment]
Hey @KapadiaNaitik 

This looks pretty good by now :)

I've pushed a few UI tweaks and think the validation isn't working properly. Here are some examples:

image

image

image

image


I think the key issue is that if the validation was wrong once and you try again, it doesn't validate again and always shows that the input is wrong.

The phone number field should allow spaces:

image

Apart from that, it looks pretty good from the UI side. We will do a code review shortly to get this merged over the weekend :)

**Comment by KapadiaNaitik** [comment]
Hey @jobenjada,
Thanks for pushing the UI tweaks.
I figured out what was going wrong, it passed an empty pattern attribute when switching from phone to other types which caused this issue. I have made a change and fixed it. 
I have also modified the phone pattern to allow spaces.
Do let me know if any other changes are required.

**Comment by KapadiaNaitik** [comment]
Thanks @jobenjada 🚀

**Comment by jobenjada** [comment]
@KapadiaNaitik Thanks again - lots of value add with these new validation types in our open text question 🤍 Great work!!

**Comment by KapadiaNaitik** [comment]
Thanks to @pandeymangg for incredible support : )

**Pull request merged**
