### PR TITLE
fix: use standalone output only for docker image builds

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

enable standalone output only for docker build, otherwise use regular output

## Type of change

- [x] Enhancement (small improvements)

## How should this be tested?

- Test A
- Test B

### CODE REVIEW

**Comment by mattinannt** [comment]
@G3root What's the underlying issue that we can't/shouldn't use standalone output by default?

**Comment by G3root** [comment]
> @G3root What's the underlying issue that we can't/shouldn't use standalone output by default?

getting this warning while running the build with `next start` command

`"next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.`

**Comment by mattinannt** [comment]
@G3root What's your motivation to run the built production server on your system?
Our officially supported way to run Formbricks in production is using Docker.
If you want to start the production server locally using node after the built you can then also run the command that is suggested:
```
node .next/standalone/server.js
```

**Comment by G3root** [comment]
> @G3root What's your motivation to run the production server on your system?
> Our officially supported way to run Formbricks in production is using Docker.
> If you want to start the production server locally using node after the built you can then also run the command that is suggested:
> ```
> node .next/standalone/server.js
> ```

Just for a rare case scenario, such as deploying to a platform like Netlify that doesn't support Docker deployment, the standalone output doesn't bundle the public folder, requiring us to manually copy those files to the build folder.

**Comment by mattinannt** [comment]
@G3root Thanks for the PR, but this is not currently what we pursue since there is no specific issue with the current deployment, and it introduces additional logic and environment variables that increase complexity.

**Pull request closed without merging**
