### PR TITLE
Refactor TextQuestion Component

### LINKED ISSUE #96: Refactor TextQuestion Component
Refactor/Rewrite the TextQuestion Component of EditorJS/NoCode-Editor to be better maintainable.

The TextQuestion Component (`snoopforms/components/editorjs/tools/TextQuestion.tsx`) was build using an old pattern for EditorJS. New Components like the MultipleChoiceQuestion use a new approach which works much better with React. The old components needs to be refactored / rewritten to work using the newer approach.
For that you can copy a newer component as a scaffolding and insert the logic and UI components of the TextQuestion.

### PR DESCRIPTION
**Pull request by devkiran**
Resolves #96

### CODE REVIEW

**Comment by devkiran** [comment]
@mattinannt Would you recommend creating a parent component class and moving the standard methods into it? I see we're repeating some methods such as  `render`, `save`, `onInputChange` on every component class. Any suggestions?

**Comment by mattinannt** [comment]
> @mattinannt Would you recommend creating a parent component class and moving the standard methods into it? I see we're repeating some methods such as `render`, `save`, `onInputChange` on every component class. Any suggestions?

sounds great 😊💪
could maybe go into a new `lib/editor.ts` file?

**Comment by mattinannt** [comment]
@devkiran great work again! Thanks a lot for the contribution 💪 I am merging it into the main branch 😊

**Comment by devkiran** [comment]
> > @mattinannt Would you recommend creating a parent component class and moving the standard methods into it? I see we're repeating some methods such as `render`, `save`, `onInputChange` on every component class. Any suggestions?
> 
> sounds great 😊💪 could maybe go into a new `lib/editor.ts` file?

Thanks @mattinannt. I'll work in the refactor when I have time.

**Comment by mattinannt** [comment]
> > > @mattinannt Would you recommend creating a parent component class and moving the standard methods into it? I see we're repeating some methods such as `render`, `save`, `onInputChange` on every component class. Any suggestions?
> > 
> > 
> > sounds great 😊💪 could maybe go into a new `lib/editor.ts` file?
> 
> Thanks @mattinannt. I'll work in the refactor when I have time.

awesome, thank you 🤗

**Pull request merged**
