### PR TITLE
fix: Max height

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Fixes https://github.com/formbricks/internal/issues/48

https://github.com/formbricks/formbricks/assets/67850763/da2aad09-f19b-4c21-a574-8f611d106bf0

The primary update in this pull request is the introduction of a new component named ScrollableContainer. This component is designed to modify scrolling behavior so that the scrollbar becomes visible when a user hovers over the content or interacts with the content div on mobile devices. The scrollbar then vanishes once the user stops hovering or touching the content.

## How should this be tested?

Test questions with super long contents

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
I'm having a bunch of issues starting this branch:

image

pls fix and reping ;)

**Comment by jobenjada** [comment]
Hey Dhru, thanks so far!

There are a few issues:

1. Survey content not centered anymore:
image

------

2. Can we fade the scroll bar in and out? It feel quite abrupt

-------

4. We need some spacing here and an indicator, that there is a more coming:
image

Please design it like so:
image

So you:
- Add a bit of margin above the buttons
- Overlay a container which fades from transparent to card-background-color

This indicates that even if the scroll bar isn't visible, there is more to scroll. And it looks intentional instead of broken :)

--------

5. Scroll Bar color: Is it possible to use `brand-color` as scroll bar color?\


------

6. Scroll bar width / height on Matrix Questions:
image

Can we fix this?

------

7. z-index errors:
image

image


-------

8. Max-height
In the survey editor, the max height seems okay, because it gives enough room for the other elements. However, on the link survey page, I find the cards too short:

image

image

It could grow 20-30% larger I think :) We already have a `isPreview` prop to make this adjustment, right?

------

9. Calendar question breaks
image

------

10. There is a new, odd gap here:
image

-----

That should be it :)

**Review by jobenjada — CHANGES_REQUESTED** [review]
pls see comment :)

**Comment by Dhruwang** [comment]
Hey @jobenjada , have updated the PR! 😊
1) Survey content not centered anymore
Was not able to reproduce this one, in ss it seems like its scrolled up 🤔

2) Can we fade the scroll bar in and out? It feel quite abrupt
Can't find a good solution for this one !

6) Scroll bar width / height on Matrix Questions
Here for some reason Horizontal scroll bar is not taking the default width, i also tried to override it but that too does not work 

7) z-index errors:
Will be fixed after we merge: https://github.com/formbricks/formbricks/pull/2493

**Review by jobenjada — APPROVED** [review]

**Review by mattinannt — APPROVED** [review]

**Pull request merged**
