### PR TITLE
feat: Ability to invite team members in bulk

### LINKED ISSUE #2413: [FEATURE] Ability to send team invitations in bulk
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

It would be great if there were the ability to import csv file and send team invitations in bulk, along with the single invitations.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #2413 

https://github.com/formbricks/formbricks/assets/81948346/c292ce2f-141c-4668-b476-166716970f59

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@anikdhabal thanks a lot for the PR :-) 💪 We will review it as soon as possible :-)

**Review by Dhruwang — CHANGES_REQUESTED** [review]
Hey @anikdhabal , thank you for this super cool feature, works pretty well 🤩🚀🙌🏻. Here are some minor issues that I noticed !


1. Padding is a bit odd, we can reduce it a bit

Screenshot 2024-04-11 at 1 18 07 PM

2. Invite modal does not closes, when clicking outside

3. Need to click twice on Template button in order to download it

4. Here button label feels confusing can we change the label of the button here to Download Template (with a download lucide-icon) ?
Screenshot 2024-04-11 at 2 25 45 PM


5. Role management is not available in free plan and we do now allow users to invite team members with role other than Admin on a free plan and your code handles that case well 😊🙌🏻
Screenshot 2024-04-11 at 2 21 43 PM
But if this is the case, along with converting the roles to admin we also want to show a warning about it. Maybe something like this 

`Please note that on the Free Plan, all team members are automatically assigned the "Admin" role regardless of the role specified in the CSV file. `

**Comment by anikdhabal** [comment]
Thanks @Dhruwang for the review. Let me fix them quickly.

**Comment by jobenjada** [comment]
Pls change the button "Template" to `variant=minimal` and text `Download CSV template`

**Review by Dhruwang — APPROVED** [review]
Looks Good 😊🚀

**Comment by jobenjada** [comment]
UI / UX looks good, over to @mattinannt

**Review by mattinannt — APPROVED** [review]

**Pull request merged**
