### PR TITLE
Fix: Animation on adding duplication tag

### PR DESCRIPTION
**Pull request by pandeymangg**
## What does this PR do?

Fixes # (issue)

https://github.com/formbricks/formbricks/assets/54475686/8c5ff2de-dab9-456a-8134-fd4394f299fd

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist

- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — CHANGES_REQUESTED** [review]
@pandeymangg thanks for the PR 😊 The shake-animation looks great 🤩

My only issue is that if the tag already exists, an error is thrown (and not caught). This leads to a message in dev and in production it would lead to a fullscreen client-side error message which wouldn't be great. Can you please fix this so that the error is caught before it reaches the user? 😊
Screenshot 2023-06-29 at 17 13 29

**Comment by pandeymangg** [comment]
Hey Matti, thanks for reviewing the PR 🙌 
The docs for the swr library recommend throwing the error from inside the fetcher if an error actually occurs, this way, the error is stored inside the `error` variable and in the `onError` callback that I'm using. It's covered here:

https://swr.vercel.app/docs/error-handling.en-US

I'm doing the same thing and it shows a message in dev, but nothing on prod because this code is working on prod right now without giving a full-page client error. What can I do differently in this case? 🤔

**Comment by pandeymangg** [comment]
@mattinannt I got it! The fix was to just set the `throwOnError` flag in the mutation to false. It works now by not throwing the error and displaying the toast.


https://github.com/formbricks/formbricks/assets/54475686/6977529f-2b0c-4f20-849f-b029ca4554c1

**Review by mattinannt — APPROVED** [review]
@pandeymangg Awesome, thanks for making the changes 😊 Everything works great now 🎉🚀
I will merge the PR into main now 😊

**Pull request merged**
