### PR TITLE
feat: connection states on integrations

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
## What does this PR do?
Adds Connected/Not Connected states to detectable Integrations

Screenshot_2023-09-20-07-12-57_5760x1080

## Overwrites from the design:
- In the designs, we had more rounded borders but I went with the same border radius as that of the card and the internal connect and docs icons for similarity
- The text size is "xs" from tailwind to stay consistent
- How can we detect the `n8n` and `make.com` integrations? Should they be added as a source in the webhook DB and update their apps accordingly?

## Type of change
- [x] Enhancement (small improvements)

## Checklist
- [x] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@ShubhamPalriwala Wanted to test it, but I'm missing the `Connect` / `Manage Webhooks` Buttons ;-)

Screenshot 2023-09-20 at 23 00 09

**Comment by ShubhamPalriwala** [comment]
ahh, apologies! gpt missed it when I asked to rewrite it in a cleaner way and i overlooked it, please take a look now

**Comment by jobenjada** [comment]
Looks great! 🙏  I think n8n we can leave out of the picture for now, make.com should work similar to Zapier. Whats the difficulty here?

Please:

1. Resolve the merge conflict and 
2. Make a suggestion on how we can get make.com correctly indicated

Thanks!!

**Comment by ShubhamPalriwala** [comment]
hey, apologies for the delayed response! was caught up w other tickets and missed this. for make, the issue is, currently in our DB, the webhook source is of type:
```
  source: z.enum(["user", "zapier"]),
```

So I was not sure if we want to handle the addition in this PR. I preferred to tackle is separately when we do the same change in our Make app and then update it here. But if you want, I can include that in this PR itself.

Because, if we do it right now, it will not show the true state since make does not send a source field.

**Comment by jobenjada** [comment]
Hey!

Makes sense, please resolve merge conflicts and open a ticket for yourself on Linear to keep track of the make.com issue :)

Happy to get this merged quickly 🚀

**Comment by ShubhamPalriwala** [comment]
Hey, resolved the merge conflict, tested it locally, and create a ticket as well on linear :)

**Review by mattinannt — APPROVED** [review]
@ShubhamPalriwala thanks a lot for solving the conflict, ready to merge :-)

**Pull request merged**
