### PR TITLE
feature/pause link survey

### PR DESCRIPTION
**Pull request by moritzrengert**

### CODE REVIEW

**Comment by mattinannt** [comment]
@moritzrengert somehow changes from your other branches ended up in here. I first thought it was just a github mixup with last changes from main so I rebased the branch, but then I saw the light/dark button changes from `fix/empty-preview-on-delete`. So I will wait until the `fix/empty-preview-on-delete` is through & fixed and then review this one 😊

**Comment by moritzrengert** [comment]
> @moritzrengert Now that the `fix/empty-preview-on-delete' PR has been merged, is the code now as you intended? Can you please provide more information on what problem this PR solves and how it solves it. Also, please resolve the merge conflict. Then I can review the PR 😊

I resolved the merge conflicts. This PR adds an improved UI for inactive link surveys, e.g. completed or paused surveys, as in Ticket https://linear.app/formbricks/issue/FOR-622/as-a-user-i-want-to-pause-or-close-a-link-survey. 🙂

**Comment by mattinannt** [comment]
@moritzrengert thanks for the changes, works great 😊
I would like to add @jobenjada for a UI review and invite him to make changes to match the rest of the apps UI.

Different states:
* Survey paused
* Survey completed
* Survey not found (e.g. wrong ID, survey deleted)

**Comment by jobenjada** [comment]
Updated UI and merged main on it. Ready to merge I'd say :)

**Comment by mattinannt** [comment]
great job @moritzrengert  @jobenjada 💪
Changes are merged into main now 😊

**Pull request merged**
