### PR TITLE
[Feature] survey back button and local storage

### LINKED ISSUE #486: [FEATURE] Go "Back" Button on Link Surveys
**Is your feature request related to a problem? Please describe.**
As a user I want to allow my respondents to go "Back" when filling out a survey

**Describe the solution you'd like**
Because we are reworking how the JS Widget handles response data locally, we will start with the Link Surveys.

To make it possible, we have to take into account that currently the response data is not stored locally. This means that if a user goes back the data cannot be displayed correctly.

This is why this ticket has two elements:

- Write a short concept and implement a local storage for the response data in Link Surveys
- Add a back button
- Make sure that all data is always displayed correctly if people go back and forth in the survey
- Make sure the data is updated 
- Bonus: Ideally, we don't have to update an answer when nothing changed to keep the UX smooth. Only build this if it doesn't make the code too complex and this check is significantly faster than just sending the update to the backend

### How we code at Formbricks 🤓
- Everything is type-safe
- All UI components are in the package `formbricks/ui`
- Run `pnpm dev` to find a demo app to test in-app surveys at `localhost:3002`
- We use **chatGPT** to help refactor code. Use our [Formbricks ✨ megaprompt ✨](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) to create the right context before you write your prompt.

### PR DESCRIPTION
**Pull request by ty-kerr**
## What does this PR do?

This PR adds a new feature that allows users to go back and fourth between questions in the survey that has been answered. 

This feature create a localStorage item that saves each questions answer, and upon navigation back and fourth between saved questions. The saved answer is retrieved and set using a useEffect.

localStorage object schema:

`formbricks-<surveyId>-answers: { 
    [<questionId>]: <submittedAnswer> 
 }
`

When the user  goes back to a question and resubmits, if the question's answer is not changed then a call to the submission api isnt made, else the answer is updated via the api. This is done by checking if the answer is different from the saved answer from local storage.

When the user finishes the survey, the localStorage item is cleaned up.

Fixes #486 

https://www.loom.com/share/d7d406b6174f4f93a13624200d58878f

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Create a new survey, with all the available question types. Start the survey. Complete the survey as usual but now you are able to go back and fourth between saved questions. When navigating back and fourth. the answers display be updated accordingly. Test with both optional and required questions.

## Checklist

- [x] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by moritzrengert** [comment]
Works as expected for me, the same needs to be added to the packages/js widget and the current main branch needs to be merged. 🙂

**Review by moritzrengert — COMMENTED** [review]
Works as expected for me, the same needs to be added to the packages/js widget and the current main branch needs to be merged. 🙂

**Comment by ty-kerr** [comment]
@moritzrengert thanks! ill update the js package hopefully over the weekends. busy weekend ahead

**Comment by ty-kerr** [comment]
in the formbricks/js package, 
- added a back button component to use for navigation back to previous question.
- added a localStorage.ts file in libs to put all the functions for saving, getting and clearing saved answers.
- In SurveyView.tsx, I added 3 local states, savedAnswer, finished and storedAnswers. 
- In SurveyView.tsx, separate the logic for submitting an answer and going to the next question. Added functions to go to previous question.
- In each of the question type component, add throw new properties to help with the feature, savedAnswer, goToNextQuestion and goToPreviousQuestion. Also added the same logic from the web app to handle the logic to show saved answers and to handle navigation when going back and fourth between answers. If the answers are not changed from the submitted answer, then the api to update the response will not be called.

**Comment by moritzrengert** [comment]
It looks good and works very smooth. I especially like the way you implemented the CTA type, so the user is not forced to follow it twice. 🙂  The widget is now working as well. 

I've noticed an issue with LinkSurveys where, upon reloading a page, the form isn't cleared properly except for the first question. This ends up restarting the survey from the first question, which can be quite confusing for users. The form is cleared correctly when a survey is completed. To improve user experience, it might be beneficial to implement a feature where all questions are pre-filled correctly upon reload, and the survey automatically navigates to the last answered question. This way, users will be able to pick up where they left off more easily. If this proves to be too complex at the moment, another option could be to simply ensure the form is cleared properly upon page reload. 🙂

**Review by moritzrengert — CHANGES_REQUESTED** [review]
It looks good and works very smooth. I especially like the way you implemented the CTA type, so the user is not forced to follow it twice. 🙂 The widget is now working as well.

I've noticed an issue with LinkSurveys where, upon reloading a page, the form isn't cleared properly except for the first question. This ends up restarting the survey from the first question, which can be quite confusing for users. The form is cleared correctly when a survey is completed. To improve user experience, it might be beneficial to implement a feature where all questions are pre-filled correctly upon reload, and the survey automatically navigates to the last answered question. This way, users will be able to pick up where they left off more easily. If this proves to be too complex at the moment, another option could be to simply ensure the form is cleared properly upon page reload. 🙂

**Comment by ty-kerr** [comment]
https://www.loom.com/share/601a18bb3de44f68a61796f873910734

I fixed the issue regarding reloading the page. The current solution is that when the user reloads the page, it will take them back to the last question with an answer. For optional questions, if the user skips it, it will count as a answer question too.

Changes:
- add default values when goToPreviousQuestion function is called by pressing the back button in web's MultipleChoiceMultiQuestion.tsx
- add null as default values instead of undefined for  web's RatingQuestion.tsx and NPSQuestion.tsx when user doesnt submit and answer. so it will save in local stage as id: null, used to check if they had answered or skipped that question.
- in LinkSurveys.ts, add a useEffect to check if how many of the questions have been answer by comparing the questionId in the localstorge against the id's in survey.questions. Add a function to get all of the storedAnswers from local stoage.

**Comment by ty-kerr** [comment]
> It looks very good now and works smoothly! I especially like the way you implemented the CTA type, so the user is not forced to follow it twice. 🙂 The widget is now working as well.
> 
> I've noticed an issue with LinkSurveys where, upon reloading a page, the form isn't cleared properly except for the first question. This ends up restarting the survey from the first question, which can be quite confusing for users. The form is cleared correctly when a survey is completed. To improve user experience, it might be beneficial to implement a feature where all questions are pre-filled correctly upon reload, and the survey automatically navigates to the last answered question. This way, users will be able to pick up where they left off more easily. If this proves to be too complex at the moment, another option could be to simply ensure the form is cleared properly upon page reload. 🙂

https://www.loom.com/share/601a18bb3de44f68a61796f873910734

I fixed the issue regarding reloading the page. The current solution is that when the user reloads the page, it will take them back to the last question with an answer. For optional questions, if the user skips it, it will count as a answer question too.

Changes:
- add default values when goToPreviousQuestion function is called by pressing the back button in web's MultipleChoiceMultiQuestion.tsx
- add null as default values instead of undefined for  web's RatingQuestion.tsx and NPSQuestion.tsx when user doesnt submit and answer. so it will save in local stage as id: null, used to check if they had answered or skipped that question.
- in LinkSurveys.ts, add a useEffect to check if how many of the questions have been answer by comparing the questionId in the localstorge against the id's in survey.questions. Add a function to get all of the storedAnswers from local stoage.

**Review by moritzrengert — APPROVED** [review]
Thank you for the fast changes! Works perfectly now, I think this will improve surveys a lot! Great work! 🙂👍

**Review by mattinannt — APPROVED** [review]
@ty-kerr thanks a lot for the PR and the changes you made 🤗💪 Sorry that it took a bit until we were able to finish the review.

The feature is really great and works perfectly 😊 So cool that we can support different use cases (page reload without loosing progress, option to go back and correct answers,..) with this big PR 😊 
I just changed the naming of states and functions a bit to avoid a mix of `response` and `answer` in the code base.

I will merge the feature into main now 🎉😊

**Pull request merged**
