### PR TITLE
feat: implementation of requirements logic

### PR DESCRIPTION
**Pull request by PaoloLeggio**
## What does this PR do?

Sometimes, the `jumpTo` conditional logic is not sufficient to achieve our goals without forcing us to branch the survey and/or duplicate questions.
Our goal is to control the display of questions based on previous answers, while keeping the question order simple.

This PR introduces a new `requirementsLogic` feature and refactors the `getNextQuestionId` function for improved readability and maintainability. The new requirementsLogic functionality allows for dynamic question visibility based on specified conditions, enhancing the survey's interactivity. Additionally, the `getNextQuestionIdByLogicJump` function has been moved to `logicEvaluator` for better organization.

feat: requirementsLogic option for question

## How should this be tested?

To verify the changes, please perform the following tests:

- Test A: Verify that questions with requirementsLogic conditions are correctly displayed or hidden based on the specified requirements.
- Test B:  Ensure that the survey flow follows the logic defined in `getNextQuestionIdByLogicJump` and that the refactored function handles edge cases 

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

https://github.com/DavinciSalute/formbricks/assets/151516329/82b0e058-c210-4b38-8f9d-aac29b8cc086

### CODE REVIEW

**Comment by mattinannt** [comment]
@PaoloLeggio thanks a lot for the PR :-) 

What would happen if the question did not meet the requirements? Would the next question be displayed?

Would it also be possible for your use case to extend the logic jump logic to allow things like:

"If this question was answered with A and the previous question was answered with B, then skip to question X"?

So the logic is not only depending on the current question value, but also being able to use previous answers or even hidden fields for the logic.

I'm going to dive a little deeper into the feature you're building and try to understand how it works and what it can do 😊
But my first intuition is that I would rather extend the existing skip logic to make it more powerful than introduce a second logic that essentially works the other way around.

**Comment by PaoloLeggio** [comment]
@mattinanntthank you for your time and for the work done so far. 

I'm glad you looked at my PR. I hope it can help make the current survey structure more flexible. I'm happy to discuss it and maybe adjust the PR based on our discussions.

The requirements logic works exactly in this way: you define a list of "requirements" that determine whether a question should be displayed or not. Each requirement specifies the question to check and the value that must have been entered. Hidden fields can, of course, be included in this check as well. This has been called requirements logic, but it doesn't overlap much with the current "jump to" logic. It's more like a list of conditions to determine the visibility of a question.

For example, if we were to create a form where one of the first questions is about gender (male or female), we could continue to ask subsequent questions to everyone and at any point in the survey decide to present a question only if the respondent answered male or only if they answered female. I would already have difficulty setting up this simple example using the current logic.

**Comment by jobenjada** [comment]
hey mate! Appreciate you taking the time to write this addition to the logic 🙏 

More advanced logic has been requested several times and its probably about time to ship it 🫡 

Would you be willing to work closer with us to get this done? You're approach is interesting, but we'd like to take a step back and see if it's really the easiest and most intuitive solution. Secondly, we'd look at a variety of different use cases logic jumps are used for and test your design against the one we have in mind.

Since we are a small team with a lot to build, we'd love to have your support getting this through the door 🤗 

What do you think? Are you already in our Discord? formbricks.com/discord

Cheers
Johannes

**Comment by PaoloLeggio** [comment]
sorry but i didn't see the last message. i noticed today that you closed this pr. what did you decide to do? did you do the merge? i am available to collaborate.

**Pull request closed without merging**
