### PR TITLE
feat: Improve preview of Surbey shared on Social Media

### LINKED ISSUE #3854: [🕹️] Improve preview of surveys shared on social
### Is your feature request related to a problem? Please describe.

Currently, if a survey link gets shared on social, it sometimes looks like this:

image

We have a different preview:
image

### Tasks

1. Find out what this card like preview is (the first image)
2. Look at how we built the second preview
3. Combine that knowledge and do the following:

- If a survey has a logo set, take that logo and place it on a light grey background (#f1f5f9)
- If it does not have a logo set, take the brandColor and add the Formbricks logo (attached)

white-mono-base

This is a research intensive task. It gives quite a lot of points so make sure to take your time, work closely with GPT to refactor your code 🙌

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Khaan25**
## What does this PR do?
This PR fixes the glitches with OG Image as mentioned in the issue below

Fixes #3854

## How should this be tested?

- Create survey
- Share with on Social media plateform

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Enhanced metadata generation for link surveys, including detailed `openGraph` and `twitter` sections with structured data.
	- Introduced error handling for surveys not found, not of type "link," or in draft status.

- **Bug Fixes**
	- Core logic of the `GET` function remains unchanged, ensuring existing functionality is intact.

- **Documentation**
	- Added comments for clarity on upcoming features related to logo checking in the API's `GET` function.

### CODE REVIEW

**Comment by Khaan25** [comment]
This is initial commit - working on it :)

**Comment by jobenjada** [comment]
@Khaan25 pls make relevant progress within the next 24h :)

**Comment by Khaan25** [comment]
Hey @jobenjada,
image

Are we gonna place the logo here? If a user has a logo, place it here else formbricks logo ->
image

Could you please let me know the placement of the logo? and card color change as mentioned in issue? :)
I'll iterate over it and wrap this up

**Comment by Khaan25** [comment]
A small sketch or screenshot would be helpful

**Comment by jobenjada** [comment]
image

this is what you're supposed to fix. the other one is good, we wanna keep that.

so you need to find out what that first preview exactly is to understand how to improve it.

**Comment by Khaan25** [comment]
Okay, Got it! I'll find out

**Comment by Khaan25** [comment]
Hey @jobenjada, I've fixed the issue. I faced this issue on my portfolio: https://v2-zzia.vercel.app :)

I've pushed the change and I'm using few extensions to test frontend thoroughly and here's an image of OG image locally: 
image

All social links (facebook, X, LinkedIn and pinterest) are working perfectly!
Let me know your thoughts.

**Comment by Khaan25** [comment]
One more thing, We need to have fallback image if the survey link is deleted, I've also handled that case on my portfolio where it shows not found image :) Clever huh! 😅

**Comment by jobenjada** [comment]
what was the issue which led to this preview?

image

If you have solved the fallback image issue, pls add it to this PR as well :)

**Comment by Khaan25** [comment]
I mean about fallback, is to provide an image for 404 page, I can add try catch block and if for whatever reason, it fails, it's gonna show 'survey not found' in the OG Image

**Comment by jobenjada** [comment]
hey! You haven't solved the issue as I describe it, you just improved our current images a tiny bit. Not worth 750 points. What do you suggest?

**Comment by Khaan25** [comment]
Right. It's upto you but as I mentioned above. I faced the same issue on my portfolio, sometimes it's OG image showed up, sometimes not, I spent well over a week trying to find the solution.

At last, found this solution, it won't happen again. You can test out my portfolio as a demo :)

I solved the issue of OG Image, whether it's tiny or big change but worth it :)

**Comment by Khaan25** [comment]
@jobenjada, any update? :)

**Comment by Khaan25** [comment]
@jobenjada, sorry for tagging you again :)

Any update? Last days for hackathon to end sooo excited.

**Pull request closed without merging**
