### PR TITLE
Patch/smooth animation

### PR DESCRIPTION
**Pull request by jobenjada**
## What does this PR do?

Adds a few UX tweaks:

- auto focus first field on login / signup page after button click
- add auto focus to "add option" btn on select questions form
- add "Responsiveness Check" to PR template
- Add animation for Progress bar
- Add smoother animation for countdown bar
- Close survey preview after countdown and reopen (on first question)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

Create an in-app survey and toggle "Auto close on inactivity".

## Checklist

- [X] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Commented on my code in hard-to-understand bits
- [X] Ran `pnpm build`
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by mattinannt — CHANGES_REQUESTED** [review]
Mostly looks great 😊

* The auto-close timer and progress bar animation in the preview looks great 🤩 Can you please add it to `@formbricks/js`, too? 😊
* When a new Multiple-Choice Question is added, the last choice is focussed. I think it would be better if (anything) the headline is focussed. What do you think?
Screenshot 2023-06-06 at 20 30 25

**Comment by jobenjada** [comment]
- Added to /js and also added the autoFocus to /js
- Good catch! Added auto focus to all questions (exctep CTA, dont know why it doesnt work) and fixed Select questions

**Review by jobenjada — COMMENTED** [review]
fixed as discussed in comment

**Review by mattinannt — APPROVED** [review]
great work 👍  I will merge the changes now 😊

**Pull request merged**
