### PR TITLE
mark survey as completed after x responses

### LINKED ISSUE #389: [FOR-797] Mark survey as completed after X completed responses
**Is your feature request related to a problem? Please describe.**
As a user I have to manually mark a survey as completed when it hits a certain count of responses.

**Describe the solution you'd like**
I would like my survey to be automatically marked as complete after a certain number of completed responses have been received.

**Tasks**

1. Add UI similar to auto-close:

*( o) Auto complete survey*

*Automatically mark the survey as complete after X completed responses.*

---

(default: off)

Please rewrite the existing component `ResponseOptionsCard.tsx` to include only this trigger and reenable the card in the `AudienceView.tsx`

1. Extend the `Survey` model in the Prisma schema with the field `autoComplete` (Int?)
2. In the Pipeline API (`app/api/pipeline`), add a check for the `responseFinished` event to determine if `autoComplete` is enabled and the responses threshold has been reached to update the survey status if true.

**Notes**

1. On in-app surveys it will work fine. We will run into the issue that the survey has been loaded by the Formbricks Widget before the survey was completed and will be displayed despite that. This will lead to additional respones above the response limit, which is fine.
2. On the other hand, this could cause a problem with link surveys: If one user fills out the survey and another user marks the survey as complete with his response, we need to check to see if the survey is blocked by the new completion status during the fill-in process.
3. Test if the Xth of X link surveys can still be completed without problems

## How to code for Formbricks

1. Make sure everything is type-safe
2. When your code is done and working, paste it to chatGPT and ask for refactoring ideas. Apply what makes sense to you (GPT-4 is a lot better)
3. Try out our new [Formbricks-Prompt](https://github.com/formbricks/formbricks/blob/main/megaprompt.md) ✨

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-797](https://linear.app/formbricks/issue/FOR-797/mark-survey-as-completed-after-x-completed-responses)</sub>

### PR DESCRIPTION
**Pull request by surendhar-palanisamy**
## What does this PR do?

Allows users to set a certain number after which , the form stops accepting responses

Fixes #389

Loom Video: https://www.loom.com/share/60e579c62a614cadba9a0b00e4b893cb?sid=265c85d8-03d6-4654-840e-4d5499f297f2

Screenshots

image
image
image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

## Checklist
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
hey mate!

Currently, the option is disabled for link surveys. For link surveys this option is also available:
grafik

Please update the description to: "Autocomplete survey on response limit"
grafik

Lastly (this wasn't part of the ticket but would be great to have):
grafik

The debugging logging doesn't show a hint that a survey would've been shown but isn't because it reached it response limit. Is this something you feel comfortable adding?

Thanks a lot!

**Comment by surendhar-palanisamy** [comment]
Sure 😃, Let me adjust my PR to include those changes

**Comment by surendhar-palanisamy** [comment]
Hi mate @jobenjada 


the code action triggers the survey widget for active surveys that are collecting insights 

since we mark the survey status as complete after x responses

completed surveys are left out from the trigger queue and are not displayed in `:3002/app` page 🤔 if we trigger them via actions

so since marking survey status as complete is the reason for the widgets not showing up i went with a more generic debug message that reflects the cause (status : completed)
image


should we change the message in logs to sound in similar tone 🤔

`All surveys have been marked as complete and are not available for display`

feel free to suggest changes, let's re-iterate few more times if we have to

**Review by mattinannt — APPROVED** [review]
Great work 😊🎉 I will merge the changes now 😊.

**Pull request merged**
