### PR TITLE
style: #1343 Added Jost Web fonts

### PR DESCRIPTION
**Pull request by SumanKisku**
## What does this PR do?

I have downloaded Jost font, converted and  included in the repo. I have included the license file also.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by mattinannt** [comment]
@SumanKisku thanks for the PR. I'm not sure about the fonts folder on the root level. How does the font needs to be embedded (and included into the tailwind config) later so we can use it in `apps/formbricks-com` as well as `apps/web`? can it be in a private folder or does it need to be in the nextjs `public` folder to be accessible by the users?

**Comment by SumanKisku** [comment]
Hi @mattinannt I think making a `apps/public` folder will be good. So `apps/web` and `apps/formbricks-com` both can use the fonts. But I have an another suggestions that can't we google fonts? I think it would be better and cleaner. What do you think? I have a pull request ready for that. Wanna see?

**Comment by mattinannt** [comment]
@SumanKisku We can't use Google Fonts directly since it doesn't comply with some privacy, e.g. GDPR in Europe.
But we can use the self-hosted font functionality by nextjs: https://nextjs.org/docs/app/building-your-application/optimizing/fonts#google-fonts
A shared `apps/public` folder wouldn't work since the public folder is a fixed folder in next.js being located inside the app, e.g. `apps/web/public` ( https://nextjs.org/docs/pages/building-your-application/optimizing/static-assets )

So I think nextjs self-host Google fonts will be the best option :-)

**Comment by SumanKisku** [comment]
Hello @mattinannt I've made some changes but to propose those changes in this pull request? Or I need to create new pull request?

**Comment by mattinannt** [comment]
> Hello @mattinannt I've made some changes but to propose those changes in this pull request? Or I need to create new pull request?

nice, thank you 😊 you can just update the PR and push your changes innhere.

**Comment by SumanKisku** [comment]
@mattinannt I've changed the as necessary. And removed the fonts folder.
And added Google Font as it stated in the site(https://nextjs.org/docs/app/building-your-application/optimizing/fonts#google-fonts) that - it automatically self-host any Google Font. Fonts are included in the deployment and served from the same domain as your deployment. **No requests are sent to Google by the browser.**

**Comment by mattinannt** [comment]
@SumanKisku thanks a lot for the update :-) Looks great, thank you ☺️
Ready for merge!

**Comment by SumanKisku** [comment]
Thank you!

**Pull request merged**
