### PR TITLE
feat: Full RTL support for Multi-Language

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
Full RTL support for Multi-Language

Fixes 
https://github.com/formbricks/internal/issues/208

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Review by pandeymangg — DISMISSED** [review]
Thanks for the PR @gupta-piyush19 looks good with the `dir="auto"` changes, works pretty good as well. As we discussed, please also fix the issues in the recall functionality 😊

**Review by jobenjada — CHANGES_REQUESTED** [review]
I'm getting the following errors when I try to open the survey editor:

image

image

everything worked for you?

**Review by jobenjada — CHANGES_REQUESTED** [review]
Hey Piyush!

Thanks a lot, this is great start :)

Here is what I noticed:

1. Radio and checkbox selection not RTL
image

Pls make sure to also include the checkbox in the consent question:
image

2. The placeholder and cursor are still LTR by default:
image

3. The question ID field doesnt respond to RTL input:
image

Unrelated to your PR but still multi lang:
The icon isn't centered left of the input field in the "Translate" text is shown:

image

The rest looks good, thanks! :)

**Review by jobenjada — APPROVED** [review]

**Comment by gupta-piyush19** [comment]
@pandeymangg Can you please take a quick look at the PR for the recall-related fixes?

**Review by pandeymangg — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
