### PR TITLE
feat: cal.com embeds in formbricks.com

### PR DESCRIPTION
**Pull request by kremedev**
## What does this PR do?

https://github.com/calcom/cal.com/issues/10811

/claim #10811

implementation cal.com embeds in formbricks.com

"@calcom/embed-react": "1.3.0" added

image

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [X] This change requires a documentation update

## Checklist

- [X] Added a screen recording or screenshots to this PR
- [ ] Filled out the "How to test" section in this PR
- [X] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Breaks our widget, will pick this up when our new survey package is live :)

**Comment by mattinannt** [comment]
Thank you very much for the work 💪 The PR had some issues with the calcom view not working in In-App surveys. Our developer @pandeymangg in taking over an opening a new PR for this since a lot changed on the infrastructure side since then.

**Comment by geoHeil** [comment]
where is the new PR?

**Pull request closed without merging**
