### PR TITLE
feat: improve configurability for upload storage

### PR DESCRIPTION
**Pull request by DavidSeptimus-Klotho**
## What does this PR do?

- Improved AWS environment support by making all S3 environment variables optional other than bucket.
- Added support for custom uploads directory via the UPLOADS_DIR environment variable.

Context: 
https://discord.com/channels/979077669410979880/1212076001039884288

## How should this be tested?

1. Added temporary log statements when getting the S3 client instance to print the current configuration.
2. Launched the Launched the app with multiple S3 environment variable variations to ensure that S3 client configuration is being picked up from the environment when not explicitly set.
3. Attempted to upload background images to survey steps to trigger and verify the s3 configuration logs.

- Launched the app both with and without `UPLOAD_DIRS` set in `.env` to ensure that default behavior is maintained and that the new custom path works when specified.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by pandeymangg** [comment]
Hey! @DavidSeptimus-Klotho Thanks for opening the PR 😊 
As you mentioned, the AWS SDK picks up the creds and the region from the environment variables, I've just added the same environment variables to turbo.json and the env file and updated the condition which checks for S3 configuration. Rest looks good!

Reference: https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html

**Comment by DavidSeptimus-Klotho** [comment]
@pandeymangg The reason I didn't add those environment variables is because the SDK checks multiple sources for credentials via its credential provider chain -- not just those environment variables. In a scenario where the application is deployed to an AWS environment, the credentials will most likely come from alternate provider.

See:
- https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html#credentialProviderChain
- https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CredentialProviderChain.html

**Comment by mattinannt** [comment]
@pandeymangg Can you please check if with these new information changes need to be made to the PR? 😊

**Comment by pandeymangg** [comment]
Hey @DavidSeptimus-Klotho thanks for sharing this new information 😊 but I still feel that a check which figures out if S3 is present or not (in our code atleast) shouldn't just be dependent on the S3 bucket name, even if the sdk can figure out the creds by other providers.
Also, as I can see in the reference you linked, the sdk looks for the default providers if the providers are not specified, which does check for the environment variables. I'd argue that this new check is good for checking if S3 is available or not 😊 Can you work with this or is this something that will block you from using the application on AWS?

**Pull request merged**
