### PR TITLE
fix: Issue with discord icon at the bottom left organization sub menu

### PR DESCRIPTION
**Pull request by itzabhinavarya**
## What does this PR do?

This PR fix the issue no. #3320 . Need to update the Join Discord icon. For more brief details head over to the issue no. #3320 

Fixes # (issue)
image

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced a new Discord icon in the Main Navigation for the "Join Discord" link.

- **Enhancements**
	- Improved type safety in the Ranking Question component by refining state initialization.
	- Enhanced validation logic and structure for survey-related types, including new types and validation functions to ensure survey integrity.

These updates enhance the user experience and ensure robust functionality across the application.

### CODE REVIEW

**Review by mattinannt — CHANGES_REQUESTED** [review]
Thanks for the PR :-) We also have the react-icons library in Formbricks so you can also use one of those icons which would be a better solution than custom code: https://react-icons.github.io/react-icons/search/#q=discord

**Comment by itzabhinavarya** [comment]
> Thanks for the PR :-) We also have the react-icons library in Formbricks so you can also use one of those icons which would be a better solution than custom code: https://react-icons.github.io/react-icons/search/#q=discord

@mattinannt Ahh.. Actually i had thought that i should use the react-icons here. since i do not see any react-icon deps in the meta data of the repo then i hadn't installed react-icon for only one icon. henceforth i had made a custom icon. Now I got to know, I'll modify the changes and again raise a PR for the same.

**Comment by jobenjada** [comment]
@itzabhinavarya pls solve the merge conflicts (the gitpod issue was solved in a different PR)

we can then go ahead and merge this :)

**Pull request closed without merging**
